apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-gitea
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 100.96.226.96
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                  - key: location
                    operator: In
                    values:
                    - fsn
          containers:
            - name: renovate
              image: renovate/renovate:41.32.0
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-gitea-env
          restartPolicy: Never