apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epicgames-freegames-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
