apiVersion: apps/v1
kind: Deployment
metadata:
  name: anko
  labels:
    app.kubernetes.io/name: anko
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: anko
  template:
    metadata:
      labels:
        app.kubernetes.io/name: anko
    spec:
      containers:
        - name: anko
          image: "git.prettysunflower.moe/prettysunflower/anko:main"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: config
              mountPath: /anko/anko/local_settings.py
              subPath: local_settings.py
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /user/geneve_encheres
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /user/geneve_encheres
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /user/geneve_encheres
              port: http
            failureThreshold: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: anko-config
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 100.94.59.38
