apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: n8n
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
