apiVersion: v1
kind: Secret
metadata:
  name: outline-secret
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:EUccuBLeq1CvMYoGlGImPjrQ297/ICC69byJJDXc3T2C6HZP9h7iXixsxcJEKXu4QYJ1LzWAG0j67yc4+Wm+5g==,iv:zpIb5mlGwv6sinFODzvjVlJbBB47jWG+nEUuHrIGBSg=,tag:40IZE0vk+f6AQXQ9+fOZWQ==,type:str]
  UTILS_SECRET: ENC[AES256_GCM,data:3mNw7QhNC7kqRrDKl0VijF0pGHv3bJpsJnsPUPAJ5uSa95acHxxtBvomsTt37wXkdss9P5HjTw244eVBwwxrBw==,iv:Oogr+QoRhenKlo6B9pAYvC6b9gfwYv3V6jKty3RhS9s=,tag:XN1mUBEHLb7gywlhu1mbRg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:i3e4a9LGUgRqfa8Cjr3sriOD0qkRtg5NqwuYuwblcUSKt3hQ0pcIgpRgzO+6HaycBYK2KlPJ,iv:7piaNW/XQ4OsWuTNCOhSMsjXyeYPrOKDbv1vYpRLuc0=,tag:YEP522mjzLBHGiViU+wcrQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:7ILyRtAL5GPLTBsW6iasrlZKP2368rtWxuep8GK91URPlzf4Muduo0x8Qts0KA2hgkopNWubc3Ee2UBejLCHlwdo7YUzCJuqfBP4,iv:L/4MhbJnqZc+uv+Mnw2wyBx9qC++SJHbfUY8CLzN6zo=,tag:6DvJtYnHkSU344lq7WXaWg==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:62VrM7oeDS83uC6serKW4aJsj7vsOoBp38UM/4yLQaIxP7kt,iv:lxoHDGQLC6HkLgoT3r8omYFV8FL4mwpjji8hdw7iTX0=,tag:2uwI9144KtTD1N5q6V7/iw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:we8BfezM0E8NaeZmN9NQZil35+LYhqqlcXzgtK7ycRc=,iv:oMt4+ZrxaWix+GWG+qtqa4+U+zfGl0r7vyMe4bNi/4A=,tag:DTVQGDnS67+xI+DoI/TzYw==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeWk2Y2dDYWlYRllvalI5
        ekRIQ1BuTUt1YkRsdGtkTjAxNW1tOXBWZ0JzCjV2NDVXMCtGYmFLbWN0M1luZTJK
        WXJBbkZ1R2JBWHh3TWlzSWxCUGlzbDgKLS0tIEU3aDFZL0l5T1lGUG1BSWtWeE9H
        UlVtWmI0UGQ1K2R0K3V1MllMY1RuUEUKJDCN2kVm9D7QosLx2VHjO+VsuyIip1KJ
        k4qkOo7BNzaHN4COI+YPgmV242ZRWPgOQgW76Zyw6G9mRGWcKxwY5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T23:09:10Z"
  mac: ENC[AES256_GCM,data:dAwU/t343C2Yamyp6aKhA5/0K6r7kDAg7P9dKqCyrSt7/6DDMHRWHIsayK4jjdFrW5iS65sRkjN9dtgPzfXKrBVM+SlRwJxqB3vgp0YQeg7IM8w0jOs7wrhJRbesfQfyHAiTIoeXeX80vZsnyBN3k108TiRvfP6oRjvUVidpk8k=,iv:+QSj2fnnCKZ5TzXbGwoNAgTuFA9nfkviYfxL4Hn1Gfw=,tag:aUUzyDC3aFEi4X4uKP6vvA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
