apiVersion: v1
kind: Secret
metadata:
  name: outline-secret
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:GkZ2Y6vDLyl6j21MQe+wSyIg8qogcb3uJc/tcqSqzS7W8MHTTULWPaWYvMI4pQDFaZm5NvkDH9rOCWScuJa8Sw==,iv:rno0/6LD3wd7aDB9EYSufc6La809bjYeYyVqU7iYlRM=,tag:1ykcbKyEs27rxhJGiy1Y1Q==,type:str]
  UTILS_SECRET: ENC[AES256_GCM,data:PjATyzrs94nmKfUghY94g57U8c2KgMrpbjJ5tpT2zuKM9T2tEzJiZyOxzbVY0TtTnB0gdqX2p1YHcAfI8aAaKQ==,iv:IOm4O1R9Vy5UsuLMmglhk6Pshli6/wJOgCRMuCQ8gkY=,tag:Enqd+dUDlMRwcIHF6TlFEA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:B0huqrG7QGFUj+sGnulUO25TPo9Uj8wE9o5YVgPo1Wa28Lsm3fIW7wpliECOXFmbn7sdRZ0W,iv:n0wCeoqkk7MXJOOL9YPzCm6mYdDZqIzkHX3k/aI44j0=,tag:9ASk8+wAx0XYE5mK+yC1QQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yNPUK+9MrXxBTSjqyyHHz3olbJeQreN3x2IXQCUcXZ/UMbNHBVoTyDmZxPyvZiX9a44dLS2eenzo6DnBZv3LcQr4tN1nk+eScRdZ,iv:2BAxa3WgU5867PKZJYMT7gAoUXuzqFj4VGqWSsw2MPo=,tag:yN6BiNlBc2BERte8t6sIPQ==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:b6mXuZ1RAO1am2jpW58PQAT6Ud90vIzuRSnLjiJgsWXxsFMx,iv:I+bBpIFUaDJ28z9uPrPfODoDcdZmwiOxljQJE4qD3RE=,tag:WyadLeoF1HhpYOunp9ROAA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:xI5M7WYFdgqRLo/Sybon3K0z8g7nP6z3YuwD0FoqcaQ=,iv:QqX84kZCEmDZcIeNRoS5Fmwfs8k4O/SH2Qqi3jPEGng=,tag:azKYukVaXykXtgmoL3sUOA==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVEVjRnFuMktKbWlPcXYz
        eUlmUkdzd3ljVUxhTFhCQmxpOURpWnR2U3ljCnVIQ1dGcjFOeWhNK0FoT1V1Y2p2
        QXZ6ZzExN2NpeU42eTh0ZTlpbmhGd0UKLS0tIGwrVTNseExrSTlRMm1RUU9Vb0hK
        YUdaY2lSOXRkUU5XclZYZ0JUZHRsNUEKOwq4SE71H0DfswNrhA1OHcT3wXhFfAw1
        ePljohOjAZwiUhMTi7fK0F6km4LseDC57F8YQrb7uIQEWMqBMgO6Rw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T14:05:00Z"
  mac: ENC[AES256_GCM,data:rXDptJ0m3dW2dYZUrEwa5n0fBteRWt5WEbzEC2lzXr2ZfqBSucTD4HC5Y3H3v7gp8kc36NOdGJmNOnfhFj0f+rYSjTZ8o8N0T8hgdh2WI5T7n+XXq/4YrqabF702CWbhvztmJ/piTWnCzyYlhUFDz2R36XLrIqQZaCcBiqFH2Aw=,iv:u8PwU3GDMwNPNGj8XclXUBYsgI/I4bEAjBgzlbUY8XY=,tag:93KJfqT1XO7CoE9LwasO1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
