apiVersion: v1
kind: Secret
metadata:
  name: outline-secret
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:qDUIpiNITPAQawdhq8VzirGuH83nElDJM4KSZJyu3LLDyvxl2BVJ6dTi81Ae4kG3jzYD4yozX3cnI3qnMmF5LQ==,iv:iLhk5Imr6ux2QDcWR5VfQaYWJ23mIh+kkhaM6gS3bJA=,tag:OoWf5QSGhhgD2+gTSZ/HfA==,type:str]
  UTILS_SECRET: ENC[AES256_GCM,data:xffpPpMQ9XoukXzunl2MtzSDd5HSBmvQkoAJRweH7Uoe+TKtIMd5kRmNMDraLbhB0z6QNBLlzWxQzcSd14mUNQ==,iv:JK0mg1UsZk4D047YQMROHGsRIYL4tIqQWQHYYCo1QOQ=,tag:BmX1ptZIwBbEGsGtm0Oayw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:IYRua+9K+1KeueV9eY77ZcE6LQn8jFbd5iSdbSgy2SDj2SBahaS8Ygb5XlIQweYRvl8XPLlzZoQJMQ==,iv:Non1F9D5FXg5Dw0yFLnyk5WHn1UtV+LrhmOmvPBGKRA=,tag:94hcHe7SQZaxDj16QMfZag==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mvLAGKuWbfI1VIwwsOAg2zxucCWrYgDXTMHmM6XtiDb2yfzZEDrZX6ITYyeMM2ShWXeVzdur,iv:oNUQjm2R8EMArfcxBP7laeT7vLNMN4UuYYUV116925M=,tag:grafnl5DQCL6UlcqSFh70g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:E8NmUM0YuRHTMVGvaz3oyfZNJRhNT+opJa9MKqI4YXkCgzNXrBKPlbTDMovv3j/Zr77XTFjup88RG76qXmGDyoGCN0vxluQGrdMH,iv:Y8Gtbq7i09S94HQ0odMgkkDRULIBwDiO7mBhplrEhgE=,tag:f0+nMcujqVAsemaMkUAV+g==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:xZFG/YXUxzrGnlybtPegwD8Pzs2bxOh/IUIXHvYZAVzdwCAb,iv:8ZjYixxvgu846pcYPoiBPNdebP7hyVVwFklD3vOGA34=,tag:whd2AUW5kcabgKWo5FMysQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:r0yk5P9+j7Wdtw8x1Y8y/hLoyK7Bv/0jTq3DlGya6Q8=,iv:8o/jNb6sAVpmjzWGE42R4JVjQuitluedzPPcWCHpgzM=,tag:jCu5xur7Dp9E911NHv0Acg==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOFVscnA1VUkxV2ZFaXll
        K2YyMkN0RWVXRytoRHhLUWNndUVoZ1ltRW5vCnZKSlN5MXpDbFU3WmtVMit5NFhV
        YXhTc3c4UTZLekNNOEp1MGZib3o3TUkKLS0tIGxlZVV4b09zRUx1dEtUZHRFazdx
        azF3Sk5IWVBQeEFISEFCL3hjU3VHWm8KSSyaE7NO4HOp8vdETvuq3oPXV328h+1e
        bw0aLKWH+ogpATjN3PwgvwlaEFFsh2y7Gm6wixsQXdQZyWm8PSt57Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-25T05:47:40Z"
  mac: ENC[AES256_GCM,data:DiF7YHcmD6aS9mtAVjR6y+eZdHYJ2tuckrW2nEuNp3LHF92cA91+Y+hXNp+WGkPg5OLx5ec14zGeupB4ujJHxfzPSBLJHb7uG/WqeTJ23XuIwkzff4Qy7IzeuDLGue1OZZxjOgkCBIeVinsxJXfwVsj/wJJyfjJYhtRml1KS1vE=,iv:lw2rWaHayiINXDJR3f1q3tKmaHPlW11XSvISEbGFWBw=,tag:Ex0dooG3VAoAPpLpGmUi0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
