#!/usr/bin/fish

# Encrypt secrets

./encrypt_secrets.fish

# prettier

set FILES (git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

echo "$FILES" | xargs /usr/bin/prettier --ignore-unknown --write
echo "$FILES" | xargs git add

exit 0