resources:
- ../common
- anko
- docker-registry
- httpdebug
- kakigoori
- mazanoke
- miniqr
- ourfigurecollection
- pocketid
- prettysunflower-website
- privatebin
- uptime-kuma
- vlmcsd
- youtubethumbnails
- znc