apiVersion: apps/v1
kind: Deployment
metadata:
  name: privatebin
  labels:
    app.kubernetes.io/name: privatebin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: privatebin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: privatebin
    spec:
      volumes:
        - name: privatebin-data
          persistentVolumeClaim:
            claimName: privatebin-data-pvc
      containers:
        - image: privatebin/nginx-fpm-alpine:2.0.0
          name: privatebin
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          volumeMounts:
            - name: privatebin-data
              mountPath: "/srv/data"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
        - name: anubis
          image: ghcr.io/techarohq/anubis:v1.22.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
              name: anubis
          envFrom:
            - secretRef:
                name: anubis-thoth
            - secretRef:
                name: privatebin-anubis-key
          env:
            - name: "BIND"
              value: ":8081"
            - name: "DIFFICULTY"
              value: "3"
            - name: "METRICS_BIND"
              value: ":9090"
            - name: "SERVE_ROBOTS_TXT"
              value: "true"
            - name: "TARGET"
              value: "http://localhost:8080"
            - name: "OG_PASSTHROUGH"
              value: "false"
          resources:
            limits:
              cpu: 750m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
