apiVersion: apps/v1
kind: Deployment
metadata:
  name: mazanoke
  labels:
    app.kubernetes.io/name: mazanoke
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mazanoke
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mazanoke
    spec:
      containers:
        - name: mazanoke
          image: ghcr.io/civilblur/mazanoke:v1.1.5
          ports:
            - containerPort: 80
              name: http