apiVersion: apps/v1
kind: Deployment
metadata:
  name: mazanoke
  labels:
    app.kubernetes.io/name: mazanoke
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mazanoke
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mazanoke
    spec:
      containers:
        - name: mazanoke
          image: ghcr.io/civilblur/mazanoke:v1.1.5
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
