protocol bgp bgpexchange_yyz from bgpexchange {
  source address 2a0e:8f01:1000:33::128;
  neighbor 2a0e:8f01:1000:33::1;
}

protocol bgp bgpexchange_nyc from bgpexchange {
  source address 2401:2060:b109:156::13c;
  neighbor 2401:2060:b109:156::1;
};

protocol bgp bgpexchange_dfw from bgpexchange {
  source address 2a0e:8f01:1000:83::12b;
  neighbor 2a0e:8f01:1000:83::1;
};

protocol bgp bgpexchange_mia from bgpexchange {
  source address 2a0e:8f01:1000:40::139;
  neighbor 2a0e:8f01:1000:40::1;
};

protocol bgp bgpexchange_sjc from bgpexchange {
  source address 2a0e:8f01:1000:22::143;
  neighbor 2a0e:8f01:1000:22::1;
};

protocol bgp bgpexchange_atl from bgpexchange {
  source address 2401:2060:b109:90::116;
  neighbor 2401:2060:b109:90::1;
};

protocol bgp bgpexchange_mkc from bgpexchange {
  source address 2a0e:8f01:1000:32::152;
  neighbor 2a0e:8f01:1000:32::1;
};

protocol bgp bgpexchange_lax from bgpexchange {
  source address 2a0e:8f01:1000:3::132;
  neighbor 2a0e:8f01:1000:3::1;
};
