protocol bgp bgptools from nyallopeers {
  multihop;
  source address 2a11:6c7:f24:30::2;
  neighbor 2a0c:2f07:9459::b17 as 212232;

  bfd graceful;
  bfd {
    interval 10s;
  };

  ipv6 {
    import none;
    export all;
  };
};
