protocol bgp he_collector from nyallopeers {
  multihop;
  source address 2a11:6c7:f24:30::2;
  neighbor 2600:7000:1000::12 as 393338;

  bfd graceful;
  bfd {
    interval 10s;
  };

  ipv6 {
    import none;
    export all;
  };
};
