apiVersion: v1
kind: Service
metadata:
  name: httpdebug
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: httpdebug
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
