apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
type: Opaque
stringData:
  NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:Cag+NJEoLNHpFi1EQRaYzA==,iv:v45uo3DabYriCNJg+AA4kegD6VvK2f957Ip5lnLZ3S4=,tag:cM0YpeEOHLfzqhZ2MHQjRg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:0zcgEb0e9vt/Qsrvhf4sRA==,iv:O6Tn/sFNzf3VdNc4+5R55uas0n3Mx9zQva9DQXXxOFs=,tag:SasWW+RnfvMnneCH7vJCEA==,type:str]
  SMTP_NAME: ENC[AES256_GCM,data:Z5Q9ehSS0P4oUYMp0V+G90Yz,iv:tn8NN2gn6WxsAgiJXIkHAhO0KG5N8oEDWkkTpEWRBZs=,tag:k9GIE2I8BESNDMijHopFjg==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtekYyd1RkVkhBTzFNOE13
        OHlMcTE1N3JYSkJnZmxIY0Rac0UwUFRuRWl3CitHR3NNMkdlaGlWWUkwM2FacWhG
        cjFPeTV2cEhaUnA2cHZJa1hVNEQxSkEKLS0tIGhxWDAxdWRzNnRtM2RJU3FnWHVi
        L1hpc2tRbXJiM01QbWxxYmJ4ZWdWSGMKbxrL1PS5vT//CzUQquxMD26uPqc9Rbbi
        jhD8DOp/Rt/yDIoMJDyZsZJOHMdkvjAXUofZvfmQAHMu1fJgm0VC5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T16:52:32Z"
  mac: ENC[AES256_GCM,data:djyxjXC9Zx2GKmvkvuNi0AYnxJKWN2LIyvcRKXz1195DGpCR3kK54t9NVNm2Mn9eiGpxRihfYVcmUh3aPqDO6Tc1gaMBn5mCfFenXZEhembEjFrZjVPetLJhYL5XK+JgLOc/4/kf2yPEWgI3P62lq1Q7sZAJBtSupNrcDopAPSs=,iv:fdmoNGg2FFpWe15gJx/FLycku5TCVIgr135ibi3Kty0=,tag:fAst1F+mRNG9iO22oCmVKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
