apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.30/releases/cnpg-1.30.0.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/artifacts/f02378072682cdbb044e92f62e606ca8681ef02a/image-catalogs/catalog-standard-trixie.yaml
  - https://raw.githubusercontent.com/cloudnative-pg/artifacts/fc079891360644b84eb2434b08cf12f3ea4d4fae/image-catalogs-extensions/catalog-minimal-trixie.yaml
patches:
  - path: vchord.patch.yaml
    target:
      kind: ClusterImageCatalog
      labelSelector: "images.cnpg.io/type=minimal"
