apiVersion: v1
kind: Secret
metadata:
  name: enoko-secrets
type: Opaque
stringData:
  DISCORD_TOKEN: ENC[AES256_GCM,data:RwQYxOsLv0GRjdcZji+buSQbDjn3koxWvLBzPIEcGIyUs476qdLJclUTC1HQi0B4t+4WUEIP72BrdjnieIVAe19vecf4108B,iv:OUBFtYY6/Z62fP7Bwqpp3h+DF1+lRfuhvKQrdL8a/gU=,tag:Sh8Wc7d/Suamdf0gQQSpxw==,type:str]
  RATES_EXCHANGE_APIKEY: ENC[AES256_GCM,data:e5iMGSPABurmZIAzYzsMCIxbkBSW2TP2LdEMnDjwff/WjXsI,iv:47wFx5s0b4NPBy3S/ZllNTUjraBl6pVINx7yEMhnIZA=,tag:ZiE7iMcpwdM6qhr8QjlYAg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdUFuSlVObmNPdTNURyty
        T0hnNTBSWWJYWVo2OGNsVWlIcHFVWG5aN2lFCjNYSkllekpqNDFSWWwrNS9GM01M
        dDgxcXhzcndhL1VFV09kenozY2lVM0EKLS0tIEdyRlNPU0crS3l1ZWw3U0RaYU9B
        YVpOUGZoSzJMdTBQR1o2UzZ5RW9GZ2sKHHMZyoembrtnoLph2p4+acIQxKZk9vHO
        COgLyBgeLWM8hySnFZmO7S+GRkEtNvVGyY5dF+zYGL5ivisZgPJPgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T02:52:01Z"
  mac: ENC[AES256_GCM,data:Mi6Q7MKISl8HwtjcrLn1QMvx8hSunPlGNkgrF496C5nIzPMJ43FbS4ChPP5jEScHn1FP85e5mp6r3QFq3a7YREApN+vzbj7hxfNDIHvLy9nBd9ekzt2HxsSwzurjYqRZkp0yIIH4AbxLPYPeqz+OW9w/iNzBH4ZQmHvvUoQgFto=,iv:9ENN6HDrn3tNWc5SOJPTaQOWFviBLtTeA5uNsHbM48o=,tag:M3yvu/aJdshZAcmJ75ApSg==,type:str]
  version: 3.13.3
