apiVersion: v1
kind: Service
metadata:
  name: pocketid
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pocketid
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1411
      name: http
