apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-gitea
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 100.94.59.38
          containers:
            - name: renovate
              image: renovate/renovate:41.99.8
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-gitea-env
          restartPolicy: Never
