apiVersion: v1
kind: Secret
metadata:
    name: renovate-gitea-env
type: Opaque
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:xCHfRYyIIx8VBof2scqU/nr/Bsg6ml+HEdkjQnxPZONMHDfy4rK79Q==,iv:89e7lAlq5dvOtALSpspY+ijxo8ggwkVcz+03nL0x1Kk=,tag:logCdIcyqL3Noncs0wq8+Q==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:2KWrjg==,iv:ZIepDXmI1FLoqaZDXjMLSeLNScLtjcd89WE3FiOi70c=,tag:b5L4Mo2f+npy8taae4i+Vg==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:hO1yeTAUmTAxEnL14zegp3Y8PCpdonZeZnDoNZWAgEvgCyb4wIU=,iv:gEuyD2pgQZQlbe/f9SlgIfxKK9CCwr4LDtKwUO3Oumw=,tag:tPEgwXFI8IfWxonPyyW2vg==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:2B8oJ1tvsKrjmGFfgOJZm4UCsy0jMg/V6Vc3B/+eHPAG42KpSFccmVOZpt9R/Q==,iv:sDd2sgwk+fF0K0PAPm1Ip+IXBLVpfJns74mFq0uBwn0=,tag:VGtQ1NvccERz/N5hC/PzzA==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:CsMH1L8=,iv:ALXkPvVmbNN7R//l4PIc0Qg/ZUlsCfQbpz0UDo9xMnQ=,tag:59oTwoYA7hUkfz5XhtxSow==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:smlDkG0e/5CMLbYo3AqFRog1zYSM6Skuq+oY3oiSdajWze9us5mNbg==,iv:N2yUEhyTyqtD9dPMsi6ATrXDxXhAYJEWe0Qold+wOsY=,tag:4v//Zd1olma07uiAxC2sgA==,type:str]
    RENOVATE_KUBERNETES: ENC[AES256_GCM,data:kJ4i6+SLM3K/Ivgut2MXSVnJOxZK3KQvfNI=,iv:3K0rvbAC0VgAAPE2JcYkqvPZq9t0oAlj0dLoArRoBv4=,tag:kPkI0YcNSL/3aA/gFUxcwg==,type:str]
    RENOVATE_PR_HOURLY_LIMIT: ENC[AES256_GCM,data:JQ==,iv:cQ6btVncIo2gsYVOqU9TrmL0YWVii9pJuR8EGD7ngEA=,tag:BF6JFQqNoB0Rjq93mEJUMg==,type:str]
sops:
    age:
        - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObWJEQnoxT0tiWDdmNldO
            TzFXbnBHZzhUdWpVeERiTUpHbEduU1JKUHdjCktEeWdFZTZ5WnpYNUJORjBhT1Ju
            UUdlZTdaaEhNbHFwV0lRczhDYi9SQW8KLS0tIEowdnRrZkQ1RERvWVRwVTlqeFlo
            NEtFL3VtWW54bDBXbFZGVGJSMll5cjQKRdgKrVznnggziL1jx6dBZCTjh6lWBPBn
            4uJvWWiUdSmTkPfckXt0d2NSc+MRgNVZNx59Qp4n7SSKyefE8eghqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T06:53:46Z"
    mac: ENC[AES256_GCM,data:8M9VOOTbRrIq7F1Xb5jA1ZemBZ831BpmCCS3lpxzyQ3BgeKeF9OlXFIykLUjfdDhq997rY+I/u9wZ31eJUpcesLkwGNrvcWqlh/GTsqUi0KBdW7TVAcrAfEJ+7dnKrdJfjheo+YrukMaNhKh58YJoTaNJYgVakj2tSgbnum4LLA=,iv:JMkDn/MSt1lHSfJOxOt4YtNAdOmwL3lzrmH1e3eYk+w=,tag:1VPcG1Ebp9l/FUykZ/06qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
