apiVersion: v1
kind: Secret
metadata:
    name: renovate-gitea-env
type: Opaque
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:rjdZVm7v1J92HO+vRyKstQvUQpaoxWJir/+XajQSGxUDIQRQx5zHeg==,iv:2h9Xfu1/XpXmpgMXZOujljKM66lP4KWOnEqtzZEpgAk=,tag:yyjo4RvF8eGpITQNRtKyoQ==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:sKr2SQ==,iv:lf7TWx1VlWd7z5hY15NVDHBiL8y3LRchy+PImwwz08o=,tag:kxhf9WW4YqASbuQO+DkLGA==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:zSeFa5i9UVQiuUHesj6inNzkMz+yE1vdoIhwRzyA/CBLtijjM2w=,iv:a9RsFgxd9/n1gDp98IpI/0iWiYSx9ku85r4oaVw8McU=,tag:sIhslYXePuMrr7VSdgMWXg==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:YaPTlD3EI+TFaBpSyvhbLKttqTHF3gFakWKZfGwAswC7X4BtOkZErjtmOHn+gw==,iv:sMbz8LDWG6GoPr439iXp1xhfqI2zbIu2VjCOOF4fjHw=,tag:RzW1/bcJKwVPbXITdWuPBw==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:wR7/Mj0=,iv:z2U4rMPi1WU3owA6Kq2xKLOVNXne+8wni0n/NKCdadg=,tag:Dn0Ws9n5vTugrJLCgBfkbA==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:ko40amGGHmEa0KuEqRdmRy1l3F88YcAI4PTDtRPGhi6DNVFeT3nrHw==,iv:THAC5Mmq8TPeaFWh2Q76zmLAWOqKGM/tASGUr0n4Als=,tag:erJy89Pj35P7ubLTU6mBig==,type:str]
    RENOVATE_KUBERNETES: ENC[AES256_GCM,data:gjBvkhABeGoENrj4n8fSGO+ipW6zJrN6z+U=,iv:vBXfCMR9uPkmu8pmxyK27h0egZeLFibC0os3e215dXQ=,tag:YXTZx/odghk49l/qawWF1Q==,type:str]
sops:
    age:
        - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUDBFQ3VGcFQ2d1RrekdG
            N1lwclgyaWZ5REJ6d2YveURmYkwzTmI5K3owClNFclRwV3BRaGhONVFCSGFDWHUw
            dlEwU1dEVVBmdnBhVWpReXlUSXA2YXMKLS0tIGRqY0lIRGVNVFU2U2tYMVgvUHE2
            NlFzYkxLVUhKNzZBRVBZNWlBc3JvRncKEH2QYP0YUg8l6Eg8uSOPVgYKC3H8BKTP
            saq+3ncmqAq7sDBDThGumCCmK/gBONT+izbDlBuScCm5T0VQkhzJeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T05:47:40Z"
    mac: ENC[AES256_GCM,data:ozAuXkAGaqy/S8epsbQNdrBgkrtnn+eDk7G3elh9CecauvqBLeymhhBbvPdFspycUT1UgHEz1A2CuzaDDArm5EUObkQpe/IUfptRqJcJYFL2aq9Jg+DkAOrxJ0MVZPB44ktJo6OVtbi+lsBBz7cHn2x4sqOnFn/1qCOctfKN5T0=,iv:Zm6lm0fgsIuJMt1i83Rs4qsNsVichs3qyt7L3gl4WkI=,tag:xWkC1lq6+OOKQqY7rTaaFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
