apiVersion: v1
kind: Service
metadata:
  name: renovate-cache
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: renovate-cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379