apiVersion: v1
kind: Secret
metadata:
  name: kikimungo-secrets
  namespace: redmine
type: Opaque
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:Jilq5z8fPUZiUpLajmHQqulNnIC21MHGPjbUQVaQJwLhoQ4lXjXTKfKON0HnH3sh99d58nDpqluCHzipWe3KWBtv4uyMeTCgzVmbMOvgDTk=,iv:aEbFl6LMJY9e605J098ykVXAuZJPwivHNqJOe31RrzU=,tag:FG2kXaNBUiacR22ZF0ZueQ==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNlR1Zmx3NWZxendLT1Q5
        akxjcUViVDQrRHRqQ1dOaXJ6Zi9ZRVloaG5ZCm5GYkNsTjl3dHh6bWV3SmEvek51
        ZGphRFRIUG1hTDRQMXlNa2V2UDlyZmcKLS0tIHF2WDlUd0pmdVgyaVVkclZVL3VV
        clBudVFLOUVvOEVrRWI2dVN4dm5STDAKQ2G8g8bJNVSRbmkOQ984KFdetJO4vD3m
        D9q2IF439IrT035j1qfVWc4a1tMNETpQy3sszKRX8rVkAoeCWCiwOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-19T14:03:48Z"
  mac: ENC[AES256_GCM,data:9OuydQ72g8bLgkjSNvL3bfgb5hpBTyIOF0Zc2p6H9pxgxefoKhZubLjLkbdA6x2K9kHj2liIXEI3wynbbNPCBCMBLUznR8yFkUv315lxytpeyNTzITERaQ+owwFHFvYyDi94hhXmdi0LdhlGv+gFGaOS6aTJJ8yc0D7PuU2QzAE=,iv:ahq/K0jUBkCmLL9MaL3TPK0IA3j8ZC7vDXwJnZ9+GWE=,tag:kkLs0jqj8yZkEz6JbBWvXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
