apiVersion: batch/v1
kind: CronJob
metadata:
  name: paieperless
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          hostAliases:
            - ip: "100.108.98.123"
              hostnames:
                - "papers.prettysunflower.moe"
          dnsPolicy: "None"
          dnsConfig:
            nameservers:
              - 100.94.59.38
          containers:
            - name: renovate
              image: git.prettysunflower.moe/prettysunflower/paieperless:main
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: paieperless-secrets
              env:
                - name: GPG_CONTENT
                  valueFrom:
                    secretKeyRef:
                      name: gpg-key
                      key: key.gpg
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 250m
                  memory: 128Mi
          restartPolicy: Never
