apiVersion: v1
kind: Service
metadata:
  name: prettysunflower-website
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prettysunflower-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: anubis
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: website-static
