apiVersion: v1
kind: Secret
metadata:
    name: anubis-ourfigurecollection-key
type: Opaque
stringData:
    ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:7cjQAI7m+DAOZC3DIuh+WtcYuuGCicrYjalimHhykvta7tIbF6CnEZRlKuBcNu8FS4bfYI1ByL23x1g0C0euaQ==,iv:mmLl6G5hJfmVaiiXvD8TeTPDQZFv/VJYBg/DxqJz5Zg=,tag:Mn/HICC6Cl4Z/EFtH4gU6g==,type:str]
    THOTH_URL: ENC[AES256_GCM,data:/eWSgbxUMO78zu3OOtQ2kYtNNE7lkw75f0K1szcyiEHkqhnB,iv:bxaOv9u+AcI8W+o5FFUJ2poMWhk1n+xYztuQUEyq7pU=,tag:0IRrTtrq8KFpbVNNLTHVbA==,type:str]
    THOTH_TOKEN: ENC[AES256_GCM,data:KZ6h9tvKE+eADakFtthuDx1fi95dXFhtbiSFANCUEcE/kphMAM7RwnRgfR4hUQXmvUwkMzJbctkMLMot4tVgkGgbi8YFureUC05DYshPjFwqedCyi1P6kAiltlQPf7GB1cIvFuKiIiTL+wtoNSCEB7jiJ/4o11Iez9LsD45ZQuVo2y/FIj73yXi5TNjUOaA9brp90IM5J05lXbYnuFFXDZ4Z+lnijphpDFPVUk0kAMCzS3qV8Ikv2RoOWEdzjtjKMBsK4anSeP946P/F6srRyvdF2R0dTBynCOXdYrAvz3QNGqjlHQavtTky3SQGnhNU2kpeyo0ZsnV7wdn/s9UXbKZSItD/GiKFfOGnyCsW6MlKV5nXv6429AC70cnUE6313jn8RFllBc+dTD5o6PHP7nbJucu4R54nSjw=,iv:mOCW4YrQX34shSC0wfznhcIYDlr9Ptz1IN+TtK5ZtSo=,tag:eQoALAxXDq4Z0i4Js/pPjg==,type:str]
sops:
    age:
        - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZd3BhaVZ0a3BUaFIrZmlq
            K0tDUEpwRFZqRU84N2Q5Q0swNTBDbXZjbVhBCk5Na3poZlBmSjV3dGN4OXhqM0FV
            cHdFSEpDSDZicnpFczQvVWd4VHVySm8KLS0tIFZrNnhWOFFOOGp2YUxremw5eUJP
            ODh6Tm5UV1Azc0loQjVYZzhYSk1QOG8KFR6Nnu8Te6g55lJPERrAdn4uneHRFOg1
            d0P4MYIEcEODJPhTD4MnR2qmx3vj3Fyoa7aPS0EZntOfL8gn8wB3kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T05:47:40Z"
    mac: ENC[AES256_GCM,data:LDScnnqWTWDpZD+23cdTv3TqbD+VfVD5z+ObOQpnrflSD65jEPc6dReaHy606syqzVy4W30gBFEY0FIyPYnxYGnm1ArPMiLeBlOU/5kxbKREsPtqUDyLs6h/I3zrhVyfYVh9IF2dqr1D8vTtRJQ2mjwcONIQv/dMOIOJptFnNos=,iv:P+cbLgcJZHhi+a1Itrpyo6dzInmwubx+5b1sMqykI0E=,tag:qXba/DtN+K+wMm1FH3BMoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
