apiVersion: v1
kind: Secret
metadata:
  name: ourfigurecollection
  namespace: anubis
type: Opaque
stringData:
  ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:dQ2p5xXgmOs77cJMnUqctMsYmCmU3SdcCE/zoVeOhvS0lZ4fj/0EZk5725LOL7k/Ut2CU7qVnX6r6SjpYM3+vA==,iv:ZWisUjM6CY3Qffe7lS4PMhScEd5gLfwiAgQnNFb5oNM=,tag:5rh6qNMnarcmkHzLlgGLmA==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWW9WSGVkTFhLRFI2eVpr
        SSsyVUhqUUJQeTdzdW9ZczgyenRWSCtXOEVBCkY5YmJBbnV2c3JhNlBIQmx2dG1h
        TWMvQ2Y2S1pkQW1iMWxGSW1SWmoraDgKLS0tIFY1SmpjbkdqTkQyWGI2V0poUGVK
        L3VUVzN0STNPOXVFS3RQYkVObmZHUXcKJFxZGft2pY5OFXbMrcZmDPiXf8XaO8e4
        bTRVODc3aWwmbWxCOm35p1kunxh2BomScov99uiEbDWctj/LGodbzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-21T00:58:15Z"
  mac: ENC[AES256_GCM,data:vFGplw7eDJkth3spCwfmulaPndSusQZIUQSayY3QjI1BynM7bL43CuXlU0RIxvSsXI1f/+6cwf73pN4KY9RDfnIewk68VHqP0PsDqCJryEphYUnrcGcS+dUbOW004HA8pbJKD+Ho+2tQ3t0YjMml9U+bqirRMqYvhyxO7iZF8Mo=,iv:0uHrio0pt06xpdVEXlf0oLdKCtgjbGSal/5J+Qx3lmw=,tag:XALR0H/7T3Jp4ECCWLzMwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: ourfigurecollection-secrets
  namespace: ourfigurecollection
type: Opaque
stringData:
  PG_HOST: ENC[AES256_GCM,data:30CuCyyrmX7saCEX9A==,iv:4JRW3+fLo5L7wn1jJTsve+uEY+90syLdpBh3Go3SYoU=,tag:vdWcYBCQ3wUQ6QJEe+OtGA==,type:str]
  PG_USER: ENC[AES256_GCM,data:+o1kBTSKeYayxYjmKZ71iS2okg==,iv:o7EH6yhCefLVlS8G+fxn8SgpK1SLRv0rkjI+bHLM7qs=,tag:g8jS8oP5U27FCzoCTW4iBQ==,type:str]
  PG_DATABASE: ENC[AES256_GCM,data:McPPZpnsoL7ESeiwe3NWyqdBBA==,iv:tJ9KK3saAFR1SxkCcT2Vu5iEvFpFq4nIA0jOqWlOEls=,tag:xuis13aND/R8n/1k8vb4OA==,type:str]
  PG_PASSWORD: ENC[AES256_GCM,data:iMnGMU8Igx9PQNSaWOvf+g==,iv:mxCMqqFyUFm25KSAEq/5cuaiaJxw7jtOr/pJYvhZW48=,tag:IBEP4Uv7WlNQQeDgAQcuzw==,type:str]
  KAKIGOORI_API_KEY: ENC[AES256_GCM,data:zHP/00vUvujObz8FUrspkYdW2sPp5X1MEIgII3+M5F9YzSfe,iv:3orTJ5nLGolvw8wPksTMjRQ+IIBVXfvWijDLvv7t/ZI=,tag:nslVaQu2O8O8nYfPAK1v5Q==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:+jUU4dZjHf0P0aVFDWQRQoJs3J2dv053jH5TgYiwu0PaFaZX,iv:UQWj+aNPIKZRcvRAaFIO0cOygEt2gkPnHelWvG6G2gc=,tag:Nfnb7pgKApm5cNzatRuBTA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:War3sDUCiAp4a9TW/pCzGH3ipQEnDmoum0QGnhNPiPA=,iv:ukcNrxl8Rr0il8Hl+L0NOgIopEjSsKs9X39kAxK7GeQ=,tag:MnOUA2YfDKVQJfder75NnQ==,type:str]
  SENTRY_DSN: ENC[AES256_GCM,data:8eRtNsHYqtctnGoo9hmbIFCLA0qon2e687RNS+JjAwELD5/ytwXMC9KeaqeB+oBTtMSFf9kCY2XrfoYFLqSZOxIoeQAYeSz8i4LzBdYZhvBmtzZ9JQ==,iv:byQDkFq7njcZEtlo2y9P1S7TQfv3tnmmCTuunaMhlBI=,tag:Udk4ozG8nVe/Ir+/NpS1Vw==,type:str]
  DJANGO_SECRET_KEY: ENC[AES256_GCM,data:Ha89Sq/v3n20Sjgw9gDxZ/Cp7CLERgsXwxjxMrPCIWdYhU+uXlCxg65jgkVJBvoFOPU=,iv:Yha5oSwJh25TbILX2xt6I1btOy97pGwb8SuDzkMfIyE=,tag:ERBoJ0I2TeTGe3VAL199sg==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWW9WSGVkTFhLRFI2eVpr
        SSsyVUhqUUJQeTdzdW9ZczgyenRWSCtXOEVBCkY5YmJBbnV2c3JhNlBIQmx2dG1h
        TWMvQ2Y2S1pkQW1iMWxGSW1SWmoraDgKLS0tIFY1SmpjbkdqTkQyWGI2V0poUGVK
        L3VUVzN0STNPOXVFS3RQYkVObmZHUXcKJFxZGft2pY5OFXbMrcZmDPiXf8XaO8e4
        bTRVODc3aWwmbWxCOm35p1kunxh2BomScov99uiEbDWctj/LGodbzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-21T00:58:15Z"
  mac: ENC[AES256_GCM,data:vFGplw7eDJkth3spCwfmulaPndSusQZIUQSayY3QjI1BynM7bL43CuXlU0RIxvSsXI1f/+6cwf73pN4KY9RDfnIewk68VHqP0PsDqCJryEphYUnrcGcS+dUbOW004HA8pbJKD+Ho+2tQ3t0YjMml9U+bqirRMqYvhyxO7iZF8Mo=,iv:0uHrio0pt06xpdVEXlf0oLdKCtgjbGSal/5J+Qx3lmw=,tag:XALR0H/7T3Jp4ECCWLzMwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
