apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: prettysunflower-website
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prettysunflower-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: static
  namespace: prettysunflower-website
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prettysunflower-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: static
      name: static
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: prettysunflower-website
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: valkey
  ports:
    - protocol: TCP
      port: 6379
      targetPort: valkey
      name: valkey
---
apiVersion: v1
kind: Service
metadata:
  name: prettysunflower-website
  namespace: anubis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: anubis-prettysunflower-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
