apiVersion: v1
kind: Secret
metadata:
  name: container-registry-config
type: Opaque
stringData:
  REGISTRY_STORAGE: ENC[AES256_GCM,data:Oqc=,iv:ikjXym2c5KCDT037xhYjHe+GFy9T/QQUGqLRr4uhrBA=,tag:G+95VTW6UVVEgn7+DkThSQ==,type:str]
  REGISTRY_STORAGE_S3_BUCKET: ENC[AES256_GCM,data:MBZ3EIQ2nkGzKNvN+z5KUdx1hU6BHoFPSCAp3bSbdDD1DQ==,iv:rATRhVrof48p3TDKimKtKZ2Drxz//hmyEjJ5h46OjHY=,tag:DsFtGpcBYlDLuBjRbIUOKQ==,type:str]
  REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:N2BgzYNka9BTztGcWzTunW7lmwiPBR/AYy6gkXvJODTJDUAyIGgxFneqc2AOblB5yF740g1I,iv:X4ebl6JVbdqyo6JA9caTt6rcTldBF9kSOT1fu9WeSpw=,tag:+19rWtZXz19g5nU0OrnOAg==,type:str]
  REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:p1+ms2yxof+1UE1UOxHuUzxNq+uyJftw/QslxJJjdJYrEDAwvzyvhfsxKFs5vEBL19E5/xg4ZF3Un9ee3wfTuo+cJlRzpbFo7jG9,iv:35pO/Tz39vgg8xnR0HWCGp3eghbOa7NDdAa5G6SzNds=,tag:5UBzeT07zSqipqk6acohiA==,type:str]
  REGISTRY_STORAGE_S3_REGION: ENC[AES256_GCM,data:WlOPrw==,iv:iJois99Dybesl4/OPNNdJ+yMZE6jyLIYj1GEiY9+HvA=,tag:X7Mx+9/Ys3E+FWox7rfV/A==,type:str]
  REGISTRY_STORAGE_S3_REGIONENDPOINT: ENC[AES256_GCM,data:RQDF5cPVk0iyy4JWrEDr8J1mXimC7zH8beIy8KpI,iv:eszlXAvrwNzElbYuG+9ZJFvPuqDgqGy3mYhI+SZnMko=,tag:L/n8P9CwD3MVsDColiRPOA==,type:str]
  REGISTRY_STORAGE_S3_FORCEPATHSTYLE: ENC[AES256_GCM,data:vBCyIpY=,iv:S9EKlOvMUYB9hgzi0YylLbsz7Szv5ogy7/6XrjivWTI=,tag:XZZnwi3T/cpD7IaBmXS42A==,type:str]
  REGISTRY_STORAGE_S3_ENCRYPT: ENC[AES256_GCM,data:TDIH/zI=,iv:zgNeo1sr+P2uXs97K/64O6wbbgKSC0mpX4PP+c9jals=,tag:gwcblJepMbh4rK/D1/mOIQ==,type:str]
  REGISTRY_STORAGE_S3_SECURE: ENC[AES256_GCM,data:VLm76A==,iv:BWzbUVw3m6JCyoSga+bepn6Kiy9xyw1aLt3jg/v3F+Q=,tag:qvDFW9W8bCO40mzHVEm6iA==,type:str]
  REGISTRY_STORAGE_S3_V4AUTH: ENC[AES256_GCM,data:2rfvzw==,iv:DgSMQWdoO4STj1WIwljiMVm89+xMjb94rqH7iR60pP0=,tag:SLzvgRZoo+9xrKFJajnA0g==,type:str]
  REGISTRY_STORAGE_S3_CHUNKSIZE: ENC[AES256_GCM,data:yocFdZCitQ==,iv:fnwMRGRk12I5yNAZ65MVWOkRIiYmO+D2Xi5p9wa2yfY=,tag:QSZeS6U++ESYh4+u4yVCvg==,type:str]
  REGISTRY_STORAGE_S3_ROOTDIRECTORY: ENC[AES256_GCM,data:Ew==,iv:13kwn5EXd5yWSPXt/HYV4xOHTH05f+izdOCWW8XSqtM=,tag:klmqvBXiNxPAEmqX6rXhbA==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOFVROTJ1Szg4N1Y3a08v
        TDBJRkVhSndpR0lWVE5OcVBFQ2ZUb2Vta3o4CkNjQ1NZMWFVSnloZU5ZT1hXNFNW
        Rk1Pa1ZOK3VKc0hCeU1xWFU4b1VEY2sKLS0tIDBPcjlES1Y1TDlkL3YwcUFoSytj
        aXYyUU9yVlQ3TVNBWVJlLzUvVkJ2elEKl5I1efcuymKX9qQjCZB+pJs155qFIIdh
        4DhRdiqI/Modv0HlN4coa+7WTkPcw5Sq5cFWvTFYcPMBmJu8Ls4VNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-23T22:00:54Z"
  mac: ENC[AES256_GCM,data:Md7qu5enY6PbwWGr2DQ3eYD7Rlt7u3foJ4B9gyRaAeWYOqGSf/4n35jY79ypAUS3VsmJZ8ZHlb9FsIL90jx8EM+y3Xd0SXszCvGa/nWwVLlqHu/l1eBTAPjWBlkXEJCbpPf2vSIhW1WH0/LA/rTAeDNcIoAa6foqTuG2bBlXxb0=,iv:koRv5iczwnY1EGTieLiaaw+O91g8p1OVbBMw99f3pP4=,tag:vr3lVPhwfxYtfml1aaKWpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: container-mirror-config
type: Opaque
stringData:
  REGISTRY_STORAGE: ENC[AES256_GCM,data:IP0=,iv:6GpByFlzO3ZaKfcMTgsySOh1uBvXw9zYsGR5sCzuiKM=,tag:zyXsfX2M3GwxvDOIC4uYKQ==,type:str]
  REGISTRY_STORAGE_S3_BUCKET: ENC[AES256_GCM,data:WGjrFKhEwAzFEJ2LG+IVcPehB9dehS2BKtx1UqOnLVc=,iv:qI+vasrN+vBTWb+LC9E0vE7PqUKgSBWVFZWh/mS4Im8=,tag:o5EI7Ldw4EC1wXfWiCCotg==,type:str]
  REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:XfiDi1a6saRAWaKaVErSUPbNmSifQBL10ov/0RWwxvLvZv0adIpRqbBEzwCRq6xnI64jHd7C,iv:sXJvyZ/uFRXIRigX9hCs3rZQJ6QRYStRG14pVOPA95w=,tag:Mc/Vui+3tMvSxl4K1uSykA==,type:str]
  REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:HCcTe3iHL37it1uZ/Z3wo1aKY634dtC5uJaQ6DrkfPzKbLi06LhqXp6h+xhKt+Tj4hUwAaM5V6MdXmqX4rA7PWOJQlUs+PfF4czh,iv:hP3RnJnza4rtmXeP30rhm0a0hBFRRQq94i67d4pZRpI=,tag:1LRnEgDUN6NrDFFhlZduDA==,type:str]
  REGISTRY_PROXY_REMOTEURL: ENC[AES256_GCM,data:LjNCdknk39U4k6dEDq9NuaQxDtiw3/FSs7n3iQ==,iv:4WcmDB19WPqNZYUx/QXyiksmNctDXZwMyGifmLmPAwk=,tag:A5DEMBGs3a+UIE//LOwCtA==,type:str]
  REGISTRY_PROXY_USERNAME: ENC[AES256_GCM,data:kpE985aB19o60w1PoPx5,iv:a+xtfXhDc1Onh2JScvh+J5OgpU+nh+khixyciuNb158=,tag:yAmtDK0P8UkskMJE0+uzcw==,type:str]
  REGISTRY_PROXY_PASSWORD: ENC[AES256_GCM,data:iD5Ioeg4iTC20BpRluO6/+0tt6ZmSQrV1+OJUT19mA==,iv:rIoVuaXb3hL+GmjRPGa0AabgrB0iLvuqOgdTybsKerk=,tag:NQs7Z41/yI1N2ul5GIy+5w==,type:str]
  REGISTRY_PROXY_TTL: ENC[AES256_GCM,data:v9Q4Ig==,iv:MhrPmyZ7HQJmwo7G9+THCd5xg3ctOnaFJMuaiQP0yxA=,tag:w6KVlJq9w+HbGB6W2Uo4RA==,type:str]
  REGISTRY_STORAGE_S3_REGION: ENC[AES256_GCM,data:slXmSA==,iv:HVO3Rp4D+5gykjiV1Lc8I3jwHtlndtPuRGXN/Dj7+es=,tag:pDagSGGDePO4XF4H869gBA==,type:str]
  REGISTRY_STORAGE_S3_REGIONENDPOINT: ENC[AES256_GCM,data:Od9s2OG0QAN9s8HjJwZ+U3yBvKNjaVoQ8GX3J7y0,iv:BgA4j1f7CZw457hKA1I4xc5BSlFj4YJGBH2TeMqVT6g=,tag:HsEFxxHC6oCG+UfTkDul7w==,type:str]
  REGISTRY_STORAGE_S3_FORCEPATHSTYLE: ENC[AES256_GCM,data:5L0LreI=,iv:WdRoLdc14t/857bh6QJCzGYavmWnpidobf/vWikc9Cw=,tag:/6d754i56CZKKOAH1jMetA==,type:str]
  REGISTRY_STORAGE_S3_ENCRYPT: ENC[AES256_GCM,data:IGwKSs0=,iv:iyvbxfaluagKPizNXr1slHHYQXcJmFXRtTHpQ8OboPI=,tag:mBsoCohpa4pchfcG4TaGVw==,type:str]
  REGISTRY_STORAGE_S3_SECURE: ENC[AES256_GCM,data:LfkAhg==,iv:h95xlBNgBeQOaFzJ62S07GkNVGTQxixsFiHFckTFs7o=,tag:lLqacULdl5iLnBybYFElYQ==,type:str]
  REGISTRY_STORAGE_S3_V4AUTH: ENC[AES256_GCM,data:78fF8w==,iv:oxGWorPJ2k8ionCPCeMIhBMWnQmw7AvmLZtSvMu7Ylo=,tag:xSTjVFrVpOSjBA+LSQr1Hg==,type:str]
  REGISTRY_STORAGE_S3_CHUNKSIZE: ENC[AES256_GCM,data:6S2t/0NPYg==,iv:3emh0kz2rH6Z6o96rJ5hXyTXUt2WFL0wIaPwXTcseVY=,tag:kZcDfWrNsWD9Mn64k2BBdQ==,type:str]
  REGISTRY_STORAGE_S3_ROOTDIRECTORY: ENC[AES256_GCM,data:lQ==,iv:d2kvl9fR8GZUIgc4f1FXDDls6H+ASRxQuqHrJefu+CE=,tag:iF7w6hUwvnMTuW+WaIXz8A==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOFVROTJ1Szg4N1Y3a08v
        TDBJRkVhSndpR0lWVE5OcVBFQ2ZUb2Vta3o4CkNjQ1NZMWFVSnloZU5ZT1hXNFNW
        Rk1Pa1ZOK3VKc0hCeU1xWFU4b1VEY2sKLS0tIDBPcjlES1Y1TDlkL3YwcUFoSytj
        aXYyUU9yVlQ3TVNBWVJlLzUvVkJ2elEKl5I1efcuymKX9qQjCZB+pJs155qFIIdh
        4DhRdiqI/Modv0HlN4coa+7WTkPcw5Sq5cFWvTFYcPMBmJu8Ls4VNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-23T22:00:54Z"
  mac: ENC[AES256_GCM,data:Md7qu5enY6PbwWGr2DQ3eYD7Rlt7u3foJ4B9gyRaAeWYOqGSf/4n35jY79ypAUS3VsmJZ8ZHlb9FsIL90jx8EM+y3Xd0SXszCvGa/nWwVLlqHu/l1eBTAPjWBlkXEJCbpPf2vSIhW1WH0/LA/rTAeDNcIoAa6foqTuG2bBlXxb0=,iv:koRv5iczwnY1EGTieLiaaw+O91g8p1OVbBMw99f3pP4=,tag:vr3lVPhwfxYtfml1aaKWpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
