apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: gatus
  labels:
    app.kubernetes.io/name: gatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gatus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gatus
    spec:
      volumes:
        - name: config
          configMap:
            name: gatus-config
      containers:
        - name: gatus
          image: ghcr.io/twin/gatus:stable
          envFrom:
            - secretRef:
                name: gatus-secrets
          env:
            - name: PG_URI
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: postgres-app
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 90
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
