apiVersion: v1
kind: Secret
metadata:
  name: gatus-secrets
  namespace: gatus
type: Opaque
stringData:
  DISCORD_ALERT_WEBOOK: ENC[AES256_GCM,data:HOHPj3iiZfeuSJHS3UXMt/KTL9DTu3D7caB+CCYP/z04a2XMuUmc9qb1okPo3e+iQMdU0HkbHZUNwIH9l3OlfhGmE4iIw+tyIz4wTRSwFPLgciCmpjY0qpAPXnjwH+m/sKc1mKTn9eNs3KOJIG436WJ8MrmPM8mi8g==,iv:6X97Gg0BYHcaZ7Ifn/49CRFqZRUsut/7HO1T45iwfUM=,tag:iXxhltVD9bg4zI1MkjNGXA==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRjlsbzhJdWVFaVZQVlZ3
        SFp1STE2aXZHVHhHT0xxZW81bUNtbDc0bEVZCkhPNkdVbkJ0Snd3WFNRYTBjTXZS
        bDZaby94ZEVKeUhteEYxckRienR0VXMKLS0tIER4M2dKekp0c3AwdGhBYm9FM01s
        WndWMEliSnlqV2R5OE1xS3FsK0NRa0kK5Nv+UNT0eLPfacAXWrSSkv+SiEQVik4p
        65LsA4ctOXCduUIZGGIVyo8+k4Q0TGFYyGqFr1KEZLUjN1mhBMuNfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T20:33:10Z"
  mac: ENC[AES256_GCM,data:7O7wiNHzb3FIVs+wRA3vqu5VaZ4BGvlFkIaTx/sV6yKNAXQOtvlnbACmSfKD8Tdw6B7OP7JiBvOIALOocmDk+tFpSgKQxquXUyOLswpJcxIbgqQ/otP+EeSde6BhNAZj0hPn1Djo8fNOxTT3rK5liG1aAPkueY+R2HXNs5f4EYE=,iv:TirA49zdizUJA1V4qW/6MAZ/4L/JXuTDbCBrSlqxj98=,tag:bg2g7enev6M8YlUyyfYyKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.0
