apiVersion: v1
kind: Service
metadata:
  name: gatus
  namespace: gatus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gatus
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
