apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: prettysunflower-website
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prettysunflower-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: anubis
---
apiVersion: v1
kind: Service
metadata:
  name: static
  namespace: prettysunflower-website
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prettysunflower-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
      name: anubis-static