apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: grafana
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Iq2u5Nib6h/8q+a9EfqPiTax93RIe3zqBkfsHbN7jys=,iv:kaTL//g3vr2qDthY5i6B1b4AT30QgcO0sMdoM96QK34=,tag:0+h2pd/bzwgB9ATRdV2lRQ==,type:str]
  GF_SMTP_PASSWORD: ENC[AES256_GCM,data:rNfav0elVRqQTBSc1CY=,iv:EdQqbvP0she/fGb7Ym5Ag+qKuiB6Iw/6E5V6ecyVDM4=,tag:M4w+XR7LXEG5eE/a70l07w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTmVuM29oTmp5bFc2c1ly
        T1VzbWFVN2RZRERPTzBKYVhQdUlnMVhNYkRjClVxdmJlTWVSTnpPVHNGWEtNOHNa
        aWFlcERVRnhHajlOM3JMQkFWRmtaMk0KLS0tIFRhRDRqRG1EejRzUWRrcDJyeGFY
        QVh4MTBXdmQyM1NOWDVUR3o3L2VGZDQKcnWr1UDAOBnlDrkuBd0khqaWruNFboqU
        3qun6BbbYU/5pb5F5V3+VE8zzRlZ0ccismuhpB53bfNTKbQQAMaXOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T21:08:04Z"
  mac: ENC[AES256_GCM,data:MscEcAZR3fb+oDcTHE4kW14RDlc0E9lMAB7SxdOmTvcoTPZ/Z85HKBpJNsRMzMSxNHRD/q8jV/6MGBkHwSlGyqM1Lo2JM0FHgmZxr+qxLDuBfpjmWiDovuiR61bOmL4scIj1gyQ14WWFx8fenvBu9u6lNvdM3WBKwwkvwh0Zv6s=,iv:m8lzc7BesggZeW+Qr30e+r4/q0NR74kwgYCDaNntlWM=,tag:IuipcIcLSm8QWuuAi0rwzQ==,type:str]
  version: 3.13.1
