# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy Sekibanki

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - apps/common/**
      - apps/sekibanki/**

jobs:
  sekibanki:
    name: Deploy changes to Sekibanki cluster
    runs-on: ubuntu-latest-prettysunflower

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Decrypt secrets
        run: >
          fdfind -I "secrets.sops.yaml" -x sops -d --encrypted-regex '^(data|stringData)$' --output {//}/secrets.yaml {} &&
          fdfind -I "local_settings.sops.py" -x sops -d --output {//}/local_settings.py {} &&
          fdfind -I "key.sops.gpg" -x sops -d --output {//}/key.gpg {}
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

      - name: Kubernetes context - Sekibanki
        uses: Azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          namespace: default
          context: sekibanki

      - name: Deploy sekibanki
        working-directory: ./apps/sekibanki
        run: kubectl apply -k . --server-side
