apiVersion: apps/v1
kind: Deployment
metadata:
  name: thelounge
  labels:
    app.kubernetes.io/name: thelounge
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thelounge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thelounge
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 100.94.59.38
      volumes:
        - name: thelounge-data
          persistentVolumeClaim:
            claimName: thelounge-pvc
      containers:
        - name: thelounge
          image: ghcr.io/thelounge/thelounge:4.4.3
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: http
          volumeMounts:
            - name: thelounge-data
              mountPath: "/var/opt/thelounge"
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
