apiVersion: v1
kind: Secret
metadata:
  name: anubis-thoth
type: Opaque
stringData:
  THOTH_URL: ENC[AES256_GCM,data:00a3NQYXw6W9wT4FPkd+attgcyvzJS46ay2ho9v5rib8I7pb,iv:G/RpMXRQ8yeTlh3Ny9xaB+bv2ea9F6TmzfN3KFJdVWY=,tag:I3K2ZVwjeqlw1j/vsoqI7Q==,type:str]
  THOTH_TOKEN: ENC[AES256_GCM,data:IiR0ckwlJcXbDhaVX1uS+R37jGOfduX3CxD2OSVNhOWkrbKd03j5NcQDEFFuYi6Ac5EilaUjx9DGjhqGYYD6xmjswBvp7Et5YtCHEQszG/fV+tao5PYHTN47PVAU4eNRjJz0MaVdDy9szc+zaCpDRlU/qnJ9HkiNLlKUC+JexeRVlCLBRYGnDtcRuM4AmS1sZeIP/dhHN5WC86kmsZ2s/5zApdwkAhWzvM8kxRSvA082Dsulloqq69peK+5OBGC93tPe6MAiiBBtec98bFDkGEe+pQM4DPDi6zKGvP0MS2k5t7vBR/njomowJMiQcPCgyBhCwprK5r8EnQEH6KLXzP7XyAXvNqHDpmLD7Lr9uhR974RzboJzaAxVaW6S/AWNtYt2RWWc8dC2Pph70Ds8XjgnlOAoep2Hghw=,iv:DvyDRvcHRLGpWmj9kAZe85UtlFmlyzLtvhlTxs7n+/c=,tag:761k37aCysp3yWgO+ZFbpQ==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNXRIQm9WUlhrdWJJVjBt
        R3FCbWpNSm15UWczMEFXdG9JeGMvTS95bFRRCnhaNE5QV3lzVUcweTNnK2ZHTmtD
        L0cwZVZHdTArN2Q1WitKMXEvU3NOK0UKLS0tIDhydWJ2QmxJNzkwa3FqeFZYbDZt
        MEE1NlNDbmllZGNCWEJReFZSd2o4Y2MKokQynz30gFNjYzs1rNX9P5zaS5yzXYQ2
        sG821n0FLYRmDVVH79NDavzuzHKpg/QtWI2+YZ14fwMgJCej/dit1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-19T22:58:30Z"
  mac: ENC[AES256_GCM,data:gra/f819Xz1Vrs7kQwcMNoQZDwF3JDdE2ONLQE04k6Q03sYzKAxMa+kBnjQm08pRoRs96Itiq2XFGaJ8psCJ78RC75qu1cx/xtnruRVIg2iY0hUHWdbULNGcm+fhVPfe2epMtOrfYSCVVgF4jZdB7jhwoC2wdfUcFeHBtlLaT+M=,iv:epfXAZ47RROC9OFs2OXK+y4PJq5vMwVgASphJkSLdqw=,tag:sCiEoOwZdx7oiojkB/GKYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
  name: thoth
  namespace: anubis
type: Opaque
stringData:
  THOTH_URL: ENC[AES256_GCM,data:N5LCHGUgrr/B1ok4EdPbQ2zu56G8wtQUAOx7wyc3k558xKW5,iv:vlua9IV6wlPdT7zyrQitFKjMcxxdU87BtgofxYaT7Y0=,tag:Y1BS/J8/+zQDoo33RWxTdQ==,type:str]
  THOTH_TOKEN: ENC[AES256_GCM,data:/t8lP1rOszG0jz5VNU5i06bsK2pxOIZKOK6hAJZ923JVzG73vfkLzOGBy78jaFTVn0O8kLl5JSfkFWtyyQM755YXbXvLATUZ9ljFXSAnpwgf4w9Df1K8urdbgEP+bQdgg2TVw/LiHpcp20NQ8ua5fWKuGGqzgUJ4JYpwq5YQDxd/eMliYGZDFuxDqsByZMs3du5BuT1qGmdF7y+WntwQrZQFaK04yUuewbwzMgIR1sAWFwASVStd2sbzTPKMqeb6PJIDk8rtDRaSaV89PPDhuOCOCUkaq3vGnHMhz6vGhThD5SvPLljVxoX+PSe4mwkjwaACHX9wejzx1sW8a7qcIZNkMUiRI50JgxK1wa6pdHpFp0n9CB6uiOYRRtz//UlDV7cBEgquE8h1yHqHq+CahLKlrjkycz06UJk=,iv:ReQZPJmYDSbIz/WiilmWqBKf0l+3DauNtQBwpHeFL/o=,tag:Qkz+xwL/S5NY46HKO7wdQw==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNXRIQm9WUlhrdWJJVjBt
        R3FCbWpNSm15UWczMEFXdG9JeGMvTS95bFRRCnhaNE5QV3lzVUcweTNnK2ZHTmtD
        L0cwZVZHdTArN2Q1WitKMXEvU3NOK0UKLS0tIDhydWJ2QmxJNzkwa3FqeFZYbDZt
        MEE1NlNDbmllZGNCWEJReFZSd2o4Y2MKokQynz30gFNjYzs1rNX9P5zaS5yzXYQ2
        sG821n0FLYRmDVVH79NDavzuzHKpg/QtWI2+YZ14fwMgJCej/dit1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-19T22:58:30Z"
  mac: ENC[AES256_GCM,data:gra/f819Xz1Vrs7kQwcMNoQZDwF3JDdE2ONLQE04k6Q03sYzKAxMa+kBnjQm08pRoRs96Itiq2XFGaJ8psCJ78RC75qu1cx/xtnruRVIg2iY0hUHWdbULNGcm+fhVPfe2epMtOrfYSCVVgF4jZdB7jhwoC2wdfUcFeHBtlLaT+M=,iv:epfXAZ47RROC9OFs2OXK+y4PJq5vMwVgASphJkSLdqw=,tag:sCiEoOwZdx7oiojkB/GKYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
