apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stump-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gouyoku-s3fs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stump-data-pv
spec:
  storageClassName: s3yuyuko
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: stump-data-pvc
  csi:
    driver: ru.yandex.s3.csi
    controllerPublishSecretRef:
      name: csi-yuyuko-secret
      namespace: kube-system
    nodePublishSecretRef:
      name: csi-yuyuko-secret
      namespace: kube-system
    nodeStageSecretRef:
      name: csi-yuyuko-secret
      namespace: kube-system
    volumeAttributes:
      capacity: 500G
      mounter: s3fs-fuse
      options: --memory-limit 1000 --dir-mode 0777 --file-mode 0666 -o allow_other --uid 1000 --gid 1000
    volumeHandle: books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stump-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: s3yuyuko
  resources:
    requests:
      storage: 500G
  volumeMode: Filesystem
  volumeName: stump-data-pv
