apiVersion: v1
kind: Service
metadata:
  name: stump
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: stump
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
