apiVersion: ENC[AES256_GCM,data:LdBaQ49FW9I=,iv:Dka791FrFMJTnIECPtJ8GtPmuBzpVXfbJ7ol1dXQeUM=,tag:sJ6HlRiLSnA2lFNBlSvElw==,type:str]
kind: ENC[AES256_GCM,data:RBSp4QxgpSsAsGJnOkEITRuvezUn3w==,iv:wqz5uLglQedm9wWCSmzoDHzRUC5MQAJijqi/YKhCJus=,tag:kGuYIBMeH+DfeDD4rkXeRw==,type:str]
name: ENC[AES256_GCM,data:0W4SnAQUnTm2,iv:V1f2aXNq0Cs9lLZwASb/DHxb26lVg6xgA47NzFCtL6o=,tag:KEVExhVxWPVYhkHZAJTP7g==,type:str]
environment:
  - ENC[AES256_GCM,data:Zs9B4N9M0M4FNObkuNvXZ5q/zR2JuOGee0UtVEmJdnB1ywXKhtT7X7JSoXpCmllvsNTc5DmVZUD9wGhry7JaGGzyb6WNAqKg,iv:0cyJwvlRAoSvfkVG37yIpqZP8dsgBlh0Z8CwYuD0Zso=,tag:2Qmg12md3mdrddYVMaiUsQ==,type:str]
  - ENC[AES256_GCM,data:6rckiB2Rcm0PrOuw5LT+P9FVLKugFWX85xwAUYD0H7N1w1mt6w==,iv:cgVVtQ5JF/5Dmho9z4/EWHRQ7MyxKgNxzVMPrv53l3Y=,tag:AcRwQITqNhMuF1OVK8Da+A==,type:str]
  - ENC[AES256_GCM,data:2ozmUQqROiQ3IBRdxuzUJTw=,iv:rageLyEwWAS3ISF7MnCt2mxp2c6AABKCqNmcd9Qa7PU=,tag:kgQ7wMzcXamuHj8UHYeBLw==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZlVMS3IvSGVaTGhxSUhw
        NjZNV0xRSWZWMkc3Mi91UDVBcVhZRTlkQkVvClFhQ0xaYmlGL0dick5mMVpFck5t
        clJqdU5pUitubTdERGxCKzRNVStVRUkKLS0tIFU4cEYxQytDdXVOQlhMWnU5QUh0
        enBEM3QwakJWeG9GWlBzeFhkdk1LblUKFPevzCbkwtfRwevjBv/TsIQLffHTzbX5
        lLARU7KTdO+qzkjPcAhwiTRxGS7Fp1xEEtiWoTCehvM3cRhZ+HvwTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T00:48:24Z"
  mac: ENC[AES256_GCM,data:gFgvh3EZ88xeu3RPKTOD9BSHznToqnXBaaDAUiTTKSZTY4b3Pkc6f94UrJFeAcgTJYjC20oSA/TJ29bF8bmHPlT7lMF2PHDcRihnCyJ2k+B+6jEr+nD8V6Y2FrevxIOav/gscCzuNvqarZq1Y8W5oeAjdvDbe+YB6OzCuY3Y/u0=,iv:A2Tv8NeRgvQtEQhKEPeO4hY6XD9qBKCOXoflV0e01P0=,tag:yqPuZWzILHCmiv81KQdcBQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
