apiVersion: ENC[AES256_GCM,data:O55gj1+qVQA=,iv:fPHW6u8BtpLrgMdIeFgmDgNSAm/LXt0kHPm9MEAKH3o=,tag:HFMGgjIGuomGo7uN156bBA==,type:str]
kind: ENC[AES256_GCM,data:XwaRNHdEanVlHsm31C5BSEV46cs9sw==,iv:Zre5OOJplqip3EVsVL4G7A5gIqv0YiVTkokAstaKpgM=,tag:w/n3tkQF/J/x+hWCaQ2xSA==,type:str]
name: ENC[AES256_GCM,data:lCQXyiUaVCtc,iv:K5KGDrMGb/9R+erNQHQSKS4qhVvdtjYrBOCD5/fU2a8=,tag:QKZ406n/aJvwhXLlBWSlDA==,type:str]
environment:
  - ENC[AES256_GCM,data:wRkKKXi3bw4aNFx+P3U4uXP7+wHO0qQHPS+jvVMTg6TTPzQ2fNz0u8GKFcP9uLZYwWP8ydRg747vQbjmWrsqD8cBUwoPXFsb,iv:Zg2Webl5MW/8Gp+L5/feqMQ/QecXDH9B9zRI1m4z5Dc=,tag:2GBOK9/Z2sVm1vt82SYzgQ==,type:str]
  - ENC[AES256_GCM,data:/kGAxlfm4ZoSi7bqmo/0fjB1mIVi2dITuXp3oBGbifsx2ZsqSw==,iv:BWLxdMal6wzeEUGsWckABg1YQnh56P4VYgj0rJaeK/E=,tag:g9ZlbtJie+cRgjW5JWh8Jg==,type:str]
  - ENC[AES256_GCM,data:GvL14JJXin4KzPuvsJRT+cc=,iv:cWyx9iCLFlILgbGsFiZGtwuB+Dfn9hHbqTBPWLMhcTA=,tag:TPAeSQYA9hjvI2UZfX7T/g==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvenRWT2xyQ0pZZEJlenZH
        eWMzM0E0NGZvbkQwdHhGSmhBeU5wQVRkTzEwCmticXJLK2w0NjZodW45NzRtZVZW
        Ynp4am81MzIwVFJQSVEvS3ZBUGM1MUkKLS0tIGFIWkp3WitpRXhoV0gxU2lPYzR0
        ZUtuWERTdkZ3RzJETmV3N2FYbjlVQjgKn6jF3e4itsyq81ZF3D26IHVBxasPy8xh
        kHi+hmXg45tQhzyZuDz2pCOIP/pPRmIr1MpeQeNM5zeTLeHro4sgyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T20:01:33Z"
  mac: ENC[AES256_GCM,data:K+j09/OZfIQRAzRvy4FtK3BqC0O+NWW2eJVG1JLClPgUT9HRpTqQCg+Y0oy+FzVnsKHctbd5YbyeDoLBJijC8nLJMmG50kVn0qdIy+Z4hcTstCQs31hL+58eqs4k6sRLVFDM4Gl7K6rCyKCcU1K5uLPGm1co88NGAUxbpN/7Ppc=,iv:1mj6Jq3KVcucJ/iCFhekFjFLklo9NcXEzXL5wdArpyE=,tag:pg5uubVK8ohk3WvpEfjy2A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
