apiVersion: v1
kind: Secret
metadata:
  name: pds-secrets
  namespace: bsky-pds
type: Opaque
stringData:
  SSO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Q38aWxsabcM/1dNFj05CCiZv8DZA5X1C8EwokOPIUtw=,iv:T0IfOVq05gelYvcaeKexyqF1VfwhjMDFlGjyYPe5xBI=,tag:5PZGbyW6xy9w7ztYS/fUdA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:x7FlN/AcFY4ol2lJzjpsM1s9WlEUhvqLKBnRNxztHnuJaJKoNpTrU33qdZEugvGUcItTfEKebN7Yk09THqMC3w==,iv:wQ252kYlaXGLV5MpiMS2aWiZx+GhqSdK0DqalmBM4hs=,tag:XwyfzJTxU3al6UOZp1xcJg==,type:str]
  DPOP_SECRET: ENC[AES256_GCM,data:M0xNydJ8sMZcCwcWmEeccCaLsSUjQLKrS0otXxC0OtjgpZtCFYpDzkjnLhzsT7ReRGM18edPU9XNxzwWAsoxRw==,iv:4kabP6xIiPwztCBffto/N5MJMWLdGsUXGOFk0quLnwE=,tag:U3McqNb010I88iijWl0RBw==,type:str]
  MASTER_KEY: ENC[AES256_GCM,data:LQE3iYuaqegGts+CioA63Oma4BvOeJK370DmGPSoYP0IIyu7ZKWYiR//Ro/YbpIql0IY/n589X77JWos0rUlxQ==,iv:SXepLFRALCVkzldPphelSEzL3PkoX6h53tJl+s6xpk4=,tag:f2Mr3Hx4TormEUEAhxLekQ==,type:str]
  MAIL_SMARTHOST_PASSWORD: ENC[AES256_GCM,data:yc9QxI7qWQq00yVyUuvPSg==,iv:Ru6NA/SxusnGIhiGoXGhDssvD0V2mhP8LurWmw2/pDA=,tag:/AOco8d5ccLmfHnmF/gGvw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c2ZjUG9PQk9FSTBiUDRK
        eUpRNFoyZjVPZDN6MzRjZ2pEWjBGOXVuWlN3CnVKK0pLb3pHenVzbzlSMW4zM01U
        WVpieDFqRWwvT040am9QOElaN2x6ZHMKLS0tIHg0eG5ubWgyd2dOdVRTeCttTFNJ
        L1EvNVRWVVpSUUowaktvMDlHeFlsbzAKociA1/3ALIwJhfdRwZoAGtYxQUZnZ6Wf
        Ab5KtSt/UbhKcsCOLQaMmuIZHXEfxW2I70iWZXysmFrpT1nrARsEzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-24T21:35:54Z"
  mac: ENC[AES256_GCM,data:cBV6HrB/6ExIgALHjKn16MXgV96xN7Ye9Idnkwf9o53Ig5U5rk3H9cxxq820ks+IJ3dTnwmczofcazAZ2jrMFGmTm5wd4kSdTN2L8BK/R5Dt4StS4urv+0Jfklw/AHPN2jIZ8CdMnfzGZqYQ1xVpEVe72yo/n1VxYxeRDmW5Ne8=,iv:YyGwPqKtGfCIda6Igzayvwdm50Pu3Iwb+tECvDn/pKc=,tag:o5njR4X47tZktMZZqL/5EA==,type:str]
  version: 3.13.1
