---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: publicfiles
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/mnt/yuyuko/public_files
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: publicfiles
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  volumeName: publicfiles
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: semipublicfiles
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/mnt/yuyuko/semi_public_files
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: semipublicfiles
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  volumeName: semipublicfiles
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: yuyuko-games
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/mnt/yuyuko/games
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: yuyuko-games
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  volumeName: yuyuko-games
