apiVersion: v1
kind: Secret
metadata:
  name: caddy-secrets
  namespace: internal-okina
type: Opaque
stringData:
  SOPS_AGE_KEY: ENC[AES256_GCM,data:XfHl97io7HoToFkMejatEtSONoJsR9BRKFOw8bxp9vFCQ2me+nnhtAza/LIVDPCclxKlnWxy2/WIfIeB6K+P1Ky1UlMjZCt82No=,iv:WtzGaZSykZI0m/d9XbA08/3EHCdlmK+bDnDd5uRWqrM=,tag:lAZY0Gg3obGd+nDHBGoEqw==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpd0MyclNJSkxjQk1EYkc3
        TE5DQWtnNWpDaHdzZ3V0MUZLYXFSck9zODFNClF3azVCWmJhZUdjcEtWMTdIbW1q
        T25nWitHNkxNUzk0WkIrTHc1NmxXcDQKLS0tIGZISjBKQnFKUEJtQlZ6MjB3TmpK
        WjZua1lmWVVBdFN3cGxkNUJBQ1B3dm8KjnIUp6ittjCGkbjVQSCIj5dyVerHeVjF
        ELmtRekvYJyFSxZqBkmasD+jV2wrJ+gixEg8rELVUIc9ly7lGphiHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T01:27:57Z"
  mac: ENC[AES256_GCM,data:XmnXwtf+oeyNcCWQoUc6r6SubRxadDYXyDWRELIiZAoFU/9L6DyCRLByTvHWAXwOTNbi5YvnpZoJwKXaukwHffK1yxONxGVDz/T2c1WXO/3vGuiKaaCx3M6m75asgFWOCObw2uUInJp60JubyBSS+z7+EmZehIP4EiaDWYmxPsk=,iv:176UhiRdjPKLMO+qPmSb4v8lTuvWTsQ947kaRSZnNfM=,tag:PA5TjS0ngoO6oL3p4tJWrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
