---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etherpad-images-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256M
  storageClassName: nfs-csi
