apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-data-pvc
  namespace: teable
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
