apiVersion: v1
kind: Secret
metadata:
  name: teable-secrets
  namespace: teable
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:0cb3zMphu48gRNItaI6jS9h7JOu10g==,iv:LffcfPqpbVbbcDtv0TxqRixPa0UwOF0w+b+LzS129Rg=,tag:8ESwExuGKdE0AF5St8KOIQ==,type:str]
  BACKEND_STORAGE_PROVIDER: ENC[AES256_GCM,data:66Q=,iv:MkjzGlw7qdSDr4mGKGYKW5VprykOIz/5XyzBcinZDp8=,tag:zP0P84jLH9UUbQOeH2X8QA==,type:str]
  BACKEND_STORAGE_S3_REGION: ENC[AES256_GCM,data:mnYGog==,iv:cn6zjNcMSD06Frq0x7NhkZSJ0J0rcNSN5Fh6wesrsO0=,tag:qxnMWZTmTJKgTNjyGbTQ5Q==,type:str]
  BACKEND_STORAGE_S3_ENDPOINT: ENC[AES256_GCM,data:/oQJE2wVeQWh4HJLj1tNKO+ZjtZ96Q==,iv:Jim2H0ZBGOi/BBnlu7mOwNW1HQqrsaAu7WLruSR3+2A=,tag:JxWZix2oTVqFkCzsE1yOZw==,type:str]
  BACKEND_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:hUrzcR2jUGaEwr4y1KZwL9+8FWS3PhXf2mcsOXr7mR/IJV9I2WeqQT4DZGJEMb6NURbDZ1ao,iv:nfmT858Xm5+squRd62K7zZ+dF2Fd6gNDuiEjItE2Mrk=,tag:yKuPjg/uEE+ajFejwE6iXQ==,type:str]
  BACKEND_STORAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:lgQZCwo9vkzG5MtPutv1UyAle+ujkpi7TNpAp83NLlPc9F6I1xIgk5B2uDYW8sKykPor5FR1VGxo4lkRN/wgrGC+spKfVsdUfQ46,iv:J/zp67z6Js0k9ZRglXexXrfrgKfTTs+2KPOTC4uFdHE=,tag:g8oW4OC43GSwio2EXrBvwg==,type:str]
  BACKEND_STORAGE_PUBLIC_BUCKET: ENC[AES256_GCM,data:yrsKOwzf43x8pRYxt62GYoicIqAdTwsgIY3PaAg=,iv:UrAviRNydXKd6NX/tqU/y+6AxhNGVUn8k+XP18W3kx4=,tag:4NqxGqktw4AfRr2Y4oWCeg==,type:str]
  BACKEND_STORAGE_PRIVATE_BUCKET: ENC[AES256_GCM,data:jILA6koXpZX5f4QZs+W06PMj5FKJ9drazhVphCBw,iv:cYBCRmMPzXaJjXTUR+UffN2OYmyhPLfC0/G38UyUkHY=,tag:cptWqdnkPqXwtP97pC86RA==,type:str]
  BACKEND_CACHE_REDIS_URI: ENC[AES256_GCM,data:D2MYO0myWGwREDTG0/hXGS8e3WwQDQC2r27oqw3av+9zpiJsNm3nP7QUI7bDSqD00Vr/1yNNHdpTf+rztDMn2/NprK7OrjYULB45H6jIZQs+qOR3jupHzbH5a2Nh,iv:EB6mK9RhuA0fpHlxV1S4+gcs72O7YtHk4RrtPwxOtjI=,tag:Kvrw3++xkczHcJ654Qg4Bg==,type:str]
  BACKEND_MAIL_HOST: ENC[AES256_GCM,data:Wa9YLYuSCmV6yfJJtgpTyfZ8Ff0HpjeS,iv:1SZYeyMb2FB8Qs5lp1EStmgXuSCQ/eklVoxa976bOeo=,tag:fE+1ay6l5k1A2mtK8j9lfA==,type:str]
  BACKEND_MAIL_PORT: ENC[AES256_GCM,data:Ip3F,iv:dG6H1K0q9x+25bPrkyKukGveBXw16CV2qcuUFgXqg4g=,tag:PX5PBDS/3Hd9l5VBKEvlsg==,type:str]
  BACKEND_MAIL_SECURE: ENC[AES256_GCM,data:Pg+KbkQ=,iv:UA89G+oWNAml8dRx0Ec5PcoqO0YXPc2z0P36sTHLs8k=,tag:sC2QzuYpUuF9/IOV/MW2HA==,type:str]
  BACKEND_MAIL_SENDER: ENC[AES256_GCM,data:EyiB192+fL3uPWPmnnXrXSlpm0UXo4aEoGI=,iv:5LVlnONNxFyryi+POHP3ZD8tNr06WeJgyx3rhqF1zes=,tag:a+avI/y+GAqW1q1lXF5kGA==,type:str]
  BACKEND_MAIL_SENDER_NAME: ENC[AES256_GCM,data:LcCACg==,iv:UJji1wPj7EK3IoXWh8u42I8hw8uvcTGBERYkWt/8Hwg=,tag:/OiqxwfUvaHyidTDol4DrA==,type:str]
  BACKEND_MAIL_AUTH_USER: ENC[AES256_GCM,data:JJDuPvkxtbCc6YmIRloyPCFX1ayjew==,iv:NanzSTi3vSgCNAIbvKb3JDWt/UL+hApvKehLuTwsfHk=,tag:q3SWQh3+LZiIGThtj4qWMw==,type:str]
  BACKEND_MAIL_AUTH_PASS: ENC[AES256_GCM,data:O9yInh5lVDsC0Ho8/mcc5A==,iv:N6pmTglSem27c2y3dd3VuzJSUqnKM7QFdM9fB3/0wKw=,tag:aHaoM/iPAf25QMoaKsFQWg==,type:str]
  BACKEND_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:/K2Fbp9tzFtBXxe1NIQIEjQl7UWTKvTakaY4TwexdM0=,iv:pGmTE6QW87wrkofS05etgTsTEjrH0JSaxMgwGJI3ORY=,tag:B94soz1x4AWI8OR8cS7Vhg==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDenQvZ0x0TlVMMnlseFpt
        TnhGOVdoNS9ocFVEbGRuUkJmcUxVUUdPVkE4CjJjYU9mM05RT1hiM2hqNTd2UUh0
        VEErY3lWZzhYZjkzRk9XOEVsZTdyZDQKLS0tIGJMTHdyMnBBRUxlbVBYcDIrNENt
        YklVWkFGTlRDUU8rSzdwVWVkQjVMeDQKzuqaYmZe5Qnyala5WwBpoeiZC2F5nFTJ
        8yPSU5Mu/4YzZFiGhAGNeNH0EPrB4A7s9uawpBOTw+sqpAhzZRD36Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T14:05:00Z"
  mac: ENC[AES256_GCM,data:rl2vst+yXqiTl7wUquLnHGeOb7Ltw8oZyLR4AGdY8mRDV9VH/mhc9m8FKSZoW5MTdhtkCEDAMsvQf9lB+UmDzD6aEoV8Q6BvNvyrNv+yzNvNiXYdUNmmOCNSXR2yCHHtiQqYCkGMEUFj+zi5ZBN9uL4h2dmKPFnFLQc7D3M0U6U=,iv:llTttwoTC9zlbqV1jsq3/NjbwbMF3DZugRl6577YSpo=,tag:ijcN+t4Nzb9r4L6Czd7txA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: valkey-secrets
  namespace: teable
type: Opaque
stringData:
  VALKEY_EXTRA_FLAGS: ENC[AES256_GCM,data:7tpSv0o1wp9mDforvnJ1+NelhBkCC0VhugTAKlTy/IzOsKsnr56ZDazq06gNad6/DtWvJeGorug8ZsmF,iv:PGZaqgd1FV8oBaKo1emDpuRfGv7NLTkZevOPOIOwZrQ=,tag:oNDOWvBQYDyvMLGv+iHktQ==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDenQvZ0x0TlVMMnlseFpt
        TnhGOVdoNS9ocFVEbGRuUkJmcUxVUUdPVkE4CjJjYU9mM05RT1hiM2hqNTd2UUh0
        VEErY3lWZzhYZjkzRk9XOEVsZTdyZDQKLS0tIGJMTHdyMnBBRUxlbVBYcDIrNENt
        YklVWkFGTlRDUU8rSzdwVWVkQjVMeDQKzuqaYmZe5Qnyala5WwBpoeiZC2F5nFTJ
        8yPSU5Mu/4YzZFiGhAGNeNH0EPrB4A7s9uawpBOTw+sqpAhzZRD36Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T14:05:00Z"
  mac: ENC[AES256_GCM,data:rl2vst+yXqiTl7wUquLnHGeOb7Ltw8oZyLR4AGdY8mRDV9VH/mhc9m8FKSZoW5MTdhtkCEDAMsvQf9lB+UmDzD6aEoV8Q6BvNvyrNv+yzNvNiXYdUNmmOCNSXR2yCHHtiQqYCkGMEUFj+zi5ZBN9uL4h2dmKPFnFLQc7D3M0U6U=,iv:llTttwoTC9zlbqV1jsq3/NjbwbMF3DZugRl6577YSpo=,tag:ijcN+t4Nzb9r4L6Czd7txA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
