apiVersion: v1
kind: Secret
metadata:
  name: teable-secrets
  namespace: teable
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:sBWpVAjG41Ngzgk4IErG0UjF1gReiQ==,iv:xStYOjE39B96CZHKuD+fx7HbsTDFaRLMQUXPG+gS+Eg=,tag:UHNZ9JzHZnzHxQfIrfy4sQ==,type:str]
  BACKEND_STORAGE_PROVIDER: ENC[AES256_GCM,data:hIc=,iv:3MBnTgTzKcIn245lP7ZR1eA8KenhdkMS1A7KJ2Azpcc=,tag:ICvD9tlQoBJwonrC6Lu1sA==,type:str]
  BACKEND_STORAGE_S3_REGION: ENC[AES256_GCM,data:v4TXHg==,iv:ePvQ3PJ4F8olQjWza/XfVe0iVeaLe7tPL9PU+N/pO/0=,tag:iVZrAaXEIZSo3KEC/Ysaeg==,type:str]
  BACKEND_STORAGE_S3_ENDPOINT: ENC[AES256_GCM,data:Jc/Oc+wvHfOd5qyjm1YRe6r/pC0NlA==,iv:a3cfRIj35KgFwdvLDYtN8pEvS+2xHgOh2w6mzBLkRGc=,tag:nAe41HgCTzby1Bft11IHRg==,type:str]
  BACKEND_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:aQOimzOqacqRck+R/ccBVT8Zthqp1t5guiq/LbPW+8CUiBbTnYUWQ181iqg1y5qI9L/Kbbjr,iv:R9zKOP//8HKy9JEZ4s1Nf/srCV6Imnflwg+5QinWlGI=,tag:bUlPqevJ2zkovpIbuRhLmQ==,type:str]
  BACKEND_STORAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:fxX7/LjAkvnGXGRfv0LqUJszq/0c2Cc/y9jSPruhr6fKAazesMjN8GCgJxgXKG12dpUY6NUqSJ+lRiXKJCwvfLgvzkS9Wx/SQSHv,iv:D3vZx9QPSpxDlS/qDpRu63ommPJInnWH62aCd4zZ3rg=,tag:bESVGa4/h5WsEczpkQrIHQ==,type:str]
  BACKEND_STORAGE_PUBLIC_BUCKET: ENC[AES256_GCM,data:V3n48PwLHFxu/KrIAh+q4fqOiFpc8ufMYVuTnOU=,iv:V6IrsxtXTFwy6rS2632Dr945wxdz8/ABJlKfI2iatWA=,tag:liIHof8mti0Bc3AdB0GmlA==,type:str]
  BACKEND_STORAGE_PRIVATE_BUCKET: ENC[AES256_GCM,data:erCaCsNqc+ikB1ra7RSPDJCeqiguW003meZmugpl,iv:ONzC6IeWvZN8NJ7cZu62igGeMRf+DMQGdT2mo31Qd8U=,tag:DFBaGZDTFM08BrCWEUQ4cw==,type:str]
  BACKEND_CACHE_REDIS_URI: ENC[AES256_GCM,data:8KdffpvqPIDjrx0Rp8H59DmvsWI6QfWSUQZLVUFNjXbsMFTnWobDm2qAsoXLgV36+dG0LP54mE6q101WzibB+Y0ZJUqvi7udH27xdiZAq5MyJuEQxFKRuypWsgdt,iv:991mQtGS0UBHaVWA86AYpyE9UH7R6d+qIfBDs1Vl3KA=,tag:mt9RE6C2dROuPxfnAfH5mQ==,type:str]
  BACKEND_MAIL_HOST: ENC[AES256_GCM,data:vC39h9aXtQNLutbOKfMNGBA5+kBuDJRi,iv:VuTlJHEVZz0Jz/dn4Lf7iSlmUxt/Iq50Rx9PRM8cLvw=,tag:nRu/1MBIdj7cVj4VTSy96w==,type:str]
  BACKEND_MAIL_PORT: ENC[AES256_GCM,data:0L/t,iv:KGYUnOuR22EI4RoVW0p8HAO4E0lXdHf7pfzSD6WBxu4=,tag:qf2Z+n0sewxBkcAs1XJ+Jw==,type:str]
  BACKEND_MAIL_SECURE: ENC[AES256_GCM,data:YoWZfJs=,iv:wu5M5je4J9fKlQ83bMzwnz4UJuPoZ5HeQO3XK5/Oh5s=,tag:BR6tGN/Rc5avC7BWhOHwQA==,type:str]
  BACKEND_MAIL_SENDER: ENC[AES256_GCM,data:jRvoI8bLqNp/iDkIRNvqh2dPK72kX8e/bCI=,iv:MtimvGhWL6AFu7FvzTSDda07R/h/oO843cdh3AXW4CU=,tag:AfhNu35oUwJu98d76YdHfw==,type:str]
  BACKEND_MAIL_SENDER_NAME: ENC[AES256_GCM,data:xWfBMw==,iv:exjyFu2APQWJIVyT9KQTAFgSZzRvPo0JlcLyeQQxOIs=,tag:3lanAbgcYvQ0jGTiKUMghw==,type:str]
  BACKEND_MAIL_AUTH_USER: ENC[AES256_GCM,data:zU+Hp8qXjm3TDHu5M6Rk43tmUD5w5g==,iv:ofZWtLlzSfo7hlf9vlGEsfPiDQWfq21A8bl5zKHlD9Q=,tag:ByxbmKAuPyZFByLa6meikw==,type:str]
  BACKEND_MAIL_AUTH_PASS: ENC[AES256_GCM,data:RQs4Jqw4Y6H5Uky9K4UMnA==,iv:SIZH2osaITufcyQhmHCOZblAw6IDzYRen/CJVnscxlM=,tag:CmGF/eP55gra9gGLy6qwSA==,type:str]
  BACKEND_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:uWX7+k3i4fIfkciB+S57IsqGu+uA+FdrIG0VpQs4fA4=,iv:NarklDdAPAv6OrxdDBJ8RLoGS1cjtPw3RG4xNM6fdYw=,tag:p0EGoXuRIUXMCDHFCEMpwQ==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVWYrRkREU1dHWU51Qitu
        UkcvMFkrTVJ5cVNLei96RExEaGp4amJkUTJJClV5T3gwR0lNb1hueEZaYjgvcXlG
        Qmc5NDRxU3JWS204b21UcUo0Z0RKNkEKLS0tIHFzSWR1ZkpMRks4bFVtL1VQZGNJ
        SGtLMXBBa0dCakpMZ1h6eEpsaXQ5dTQKwVtkhYe8JEHbP2wSP65le7J2nDRDUHsF
        KekVYhJT7y6dWXzclHVoQZ9RGcm0RNMQI1btBWE/I+JDy8kYLKmr/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T23:09:11Z"
  mac: ENC[AES256_GCM,data:w55KM8afueYxdq1r+6GpoM1F8KeifiME1lV7pEwJaRvVe3Bb1Qs6kVLmPYIiMK/N4Y7OQphhsZnNofeqmIJJnURYftXuDJHNAWYIfzNs96vrpZXa9zaEYVmhKluABlTwr/Odobhf2Y/8zxSH5BPrsWjK0MV1XUK/NrlDHIgyHjE=,iv:usjDHvJePHMWOZNK6zhjCPJO3cGP1Dl73JfJQwO2s1o=,tag:t3GaY6fCTv3LYg/Gvm+2xQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: valkey-secrets
  namespace: teable
type: Opaque
stringData:
  VALKEY_EXTRA_FLAGS: ENC[AES256_GCM,data:lN/iy77TjJfLnvYQYVRQ/3zjoNtWDk6hl3aG0TdiJtiGKmy1Hze3L8kivCgugAQI+lBwMHgVAlKFDDD7,iv:6f0caQayS65Ix+uWHLH7VwtUjMW79Ol0HyholkdgrDI=,tag:07xAnp/IRRtx1UjXvFSZgQ==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVWYrRkREU1dHWU51Qitu
        UkcvMFkrTVJ5cVNLei96RExEaGp4amJkUTJJClV5T3gwR0lNb1hueEZaYjgvcXlG
        Qmc5NDRxU3JWS204b21UcUo0Z0RKNkEKLS0tIHFzSWR1ZkpMRks4bFVtL1VQZGNJ
        SGtLMXBBa0dCakpMZ1h6eEpsaXQ5dTQKwVtkhYe8JEHbP2wSP65le7J2nDRDUHsF
        KekVYhJT7y6dWXzclHVoQZ9RGcm0RNMQI1btBWE/I+JDy8kYLKmr/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T23:09:11Z"
  mac: ENC[AES256_GCM,data:w55KM8afueYxdq1r+6GpoM1F8KeifiME1lV7pEwJaRvVe3Bb1Qs6kVLmPYIiMK/N4Y7OQphhsZnNofeqmIJJnURYftXuDJHNAWYIfzNs96vrpZXa9zaEYVmhKluABlTwr/Odobhf2Y/8zxSH5BPrsWjK0MV1XUK/NrlDHIgyHjE=,iv:usjDHvJePHMWOZNK6zhjCPJO3cGP1Dl73JfJQwO2s1o=,tag:t3GaY6fCTv3LYg/Gvm+2xQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
