apiVersion: apps/v1
kind: Deployment
metadata:
  name: opengist
  labels:
    app.kubernetes.io/name: opengist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opengist
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opengist
    spec:
      volumes:
        - name: opengist-data
          persistentVolumeClaim:
            claimName: opengist-data-pvc
      containers:
        - name: opengist
          image: ghcr.io/thomiceli/opengist:1.10
          ports:
            - containerPort: 6157
          volumeMounts:
          - name: opengist-data
            mountPath: "/opengist"
          envFrom:
            - secretRef:
                name: opengist-secret
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 6157
            initialDelaySeconds: 30
            periodSeconds: 5