---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opengist-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: seaweedfs-storage