apiVersion: apps/v1
kind: Deployment
metadata:
  name: privatebin
  namespace: privatebin
  labels:
    app.kubernetes.io/name: privatebin
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: privatebin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: privatebin
    spec:
      volumes:
        - name: privatebin-data
          persistentVolumeClaim:
            claimName: privatebin-data-yuyuko-pvc
      containers:
        - image: privatebin/nginx-fpm-alpine:1.7.6
          name: privatebin
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: privatebin-data
            mountPath: "/srv/data"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
        - name: anubis
          image: ghcr.io/techarohq/anubis:v1.20.0
          imagePullPolicy: Always
          env:
            - name: "BIND"
              value: ":8081"
            - name: "DIFFICULTY"
              value: "3"
            - name: ED25519_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: anubis-key
                  key: ED25519_PRIVATE_KEY_HEX
            - name: "METRICS_BIND"
              value: ":9090"
            - name: "SERVE_ROBOTS_TXT"
              value: "true"
            - name: "TARGET"
              value: "http://localhost:8080"
            - name: "OG_PASSTHROUGH"
              value: "false"
          resources:
            limits:
              cpu: 750m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault