apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privatebin-data-pvc
  namespace: privatebin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi