apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privatebin-data-yuyuko-pvc
  namespace: privatebin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3yuyuko
  resources:
    requests:
      storage: 5Gi