apiVersion: v1
kind: Service
metadata:
  name: privatebin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: privatebin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      name: http