apiVersion: v1
kind: Secret
metadata:
  name: opengist-secret
type: Opaque
data:
  OG_SECRET_KEY: ENC[AES256_GCM,data:ALfoKPIbn0IC5A1PwMTMvt9PL41uDNX0CkHprxze13V1/cOL6yuuvo9BhqZsuUWE3Kle/GpvRQ8Bg4o7Jhmx+Pv8ShNw1qwbOEpC+GJzpjcFiGCRk85c9Q==,iv:KxzHv25AE5IrAq5VF4ZQwrpEImsumLkE5rRXi+7dFYs=,tag:DlpdSJXL60Y+pru/N4euRQ==,type:str]
  OG_OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:F1JqubcKwvL/D2t3r+nQycaxSg0=,iv:23jwYopiP/J8pe8hB/uksuahV7orSjOL28srFQkDgKk=,tag:io6BPsUSImGchQcSP0Bp8Q==,type:str]
  OG_OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:mzepB5fdceSfA9RWQdTX03R8Tynol3rQxJa48U38j1LnDSo20QDsk/cbfDwUUtGEU65qEnT+P151xp+X+PImZe1C0KFJSdrEBct+Dw==,iv:p8axNGvYc700lSmPmzi6zaBujPU7FHf2Ja31jPhe3Zo=,tag:cWg0PbCw2Uj3jjsH8c2fEg==,type:str]
stringData:
  OG_OIDC_CLIENT_KEY: ENC[AES256_GCM,data:pfCV16d/NsBHQWCe79/RGq1QYwVC+zUBpRKWYCiNLLgZiucP,iv:BofmqYQNK4iYb5v3dP8iFLUOuzgdgXK5k9+/3nZrLb8=,tag:jmR8/t1Y9H5k0KsQkYbu6A==,type:str]
  OG_OIDC_SECRET: ENC[AES256_GCM,data:vrsj6cqsVXC6L3PwgFjkXxjBlM1W9fyIxaAoqecsBjI=,iv:ZY08gr/9AB+hsEMSuL7gnIV4s1X/MGVS3xARNd46oUQ=,tag:gKRVGEGptP0XvZELFa9r/Q==,type:str]
  OG_DB_URI: ENC[AES256_GCM,data:sKu3WR358mQDEvQT1F1ynYtXjNEj6SNPvCKrAF2+pZ+80CnUdlMndzdtyNXPNy+jAcC15q6spyi/7fZYQoIk9S/5FESUarbEmxN6qA==,iv:N7VY7Eyxg/JinrhpkVEwQNNCBQKSFcOaEU/cMLkXcAU=,tag:u+RZUp50CFimvmZ9eY01jg==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYnBLTWJqNkNNRS9La0V4
        K3pRdmozSU1ncG1kZVZvb2lST1BXUXVXaWtNCmVCcWtmMGx3c2R4ekJ3MWY3eTZ4
        NUhMaTNRUFVkRVgwODRDS1c1Q29GT2sKLS0tIGxTSjZIbXd1dlVBaUtFanVJWDhW
        S0lkUjUyUVNOYU9ja3hpSDJCZW1ERlEK2cSKUHb0DaizKCnrqGNswQK2nNlgQRmw
        pILnpUQSBfKsUe/Uody/yOA58QG854kF3Mjf7KGCX7I9BoBjdXNT/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-21T00:58:15Z"
  mac: ENC[AES256_GCM,data:nO9CFRAoqfG5vEvh2arCUXGlH80yZ4Hs4BK8m03WAWUE2SB7nXGvuc9nfJsskvA37MX1G5/vKbHgZ5II/FtPXjbT1EEpV2N6grsHlVEGapiQNgX575hWwQnYLDjbaQy79lf3LpR6QVG/MYEYKX/OG5ksDfT8nfF6P4rD5xgZo24=,iv:pY1Dy4QZ6PkOabaUMJVMZn2m88uHDuvf9nF9VIuhMSY=,tag:Je1U5mFl+GzNuqkhB9W4Ng==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
