apiVersion: v1
kind: Secret
metadata:
  name: opengist-secret
type: Opaque
data:
  OG_SECRET_KEY: ENC[AES256_GCM,data:cpipf1P3ZQZbA4jNoIntwGFCBAbrfQHddrxaCRCUZCXe05BkMep3ouW9zh2YVSR7E0fUdNs4re7T4u5/6fDuZ0UeY6jn3xR9skcPtBzsi9rjswMIVc+gKg==,iv:xixWMBjfD8VGBw7I1ylhxsBbC56THfHQXb2Zj8xJP50=,tag:rmtOm7urHoT126IcfH0m7Q==,type:str]
  OG_OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:AG90RIOFwu/4+AXn1EPn7Xln1cE=,iv:/Y1sNL7rCMPYSES9rx5adkSgw1+t5S3h8bEGzMAlIzU=,tag:1rNkInK6n1SOS542sk8zeA==,type:str]
stringData:
  OG_OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:ubABxaw2pODmzQ==,iv:ytxiMZcNP5qcL1ewH1ITlSwGG1eOlT09Kgd4GU+3NpA=,tag:8914tMQSBKYVqG8B9x/q7g==,type:str]
  OG_OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:c8BZGlml4TV10D/Q7DCwcZdfe9qarNaEBcvVkhr0GVkzkxRmUdKQwq46GVBwK4zVy+9WyfJHqWhKr5F0oA==,iv:xbSUsD9AfsCsGQLdpyGygBj9w1vvnroO6dsX6fHiBH8=,tag:Yt7acPDqRgM+5JtjxGATNw==,type:str]
  OG_OIDC_CLIENT_KEY: ENC[AES256_GCM,data:RqrX3k8OWhe6BfgJj9K0t9EFshozCjmRRsN9PV5WKvLgqA93,iv:vZ4qiSPqGENQPiNX+wD4y6igdlGfEv3G0UqLQhU7LQ0=,tag:u7ynYAz7bXgCPQsviO5Flw==,type:str]
  OG_OIDC_SECRET: ENC[AES256_GCM,data:688d4DrPVeSFJu6RNuinxiQnDfXk0CRtbfN8z7Qj2X0=,iv:uydbcjPAWwA+15Bb/XjlhFc5f2hP4xmXKStCOQh2TtU=,tag:un2PRNzpLlTmMDlxX0SPRw==,type:str]
  OG_DB_URI: ENC[AES256_GCM,data:1SxLQN77xdrvi35FioEmHGKhvcXaDy9tm3DKCjgymOPNeNAMUmw52yYmDdmmc1ozA/cOtwDO6vnSxK6FIYGrWq7GCSlDdw0LFGEYnA==,iv:pmIIY5XfSptn9CfUTlD4I9wRSot20pi3kDQwxeJ7JDk=,tag:QooenCNGm++Ib3SZntlaRQ==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbWNxYTNSNDNpYUN1THRE
        aGdia0J1RmpqTk9SSHVPN21hTU9tZGtVaDBZCjk4TGZsakx6VU1HNGNjeG9DTTVR
        WVprbFdGYWtBdjB5S2dnanZrei9DU0UKLS0tIGQ4cUthanRVTk51eENkK3Avb1lH
        UmZFc0FTcVlhMUNHSjIyaVJ5WHFTWW8KoQNJXrJ65yTTQR1GbkkgdwUFBP8Gnnx8
        nogS2/bb+RPBowCcAF5tiik7Y9Wujrdxi2l07Y7deRQYYRzQIOjL2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T15:28:30Z"
  mac: ENC[AES256_GCM,data:orq3VZ5SohXCWWw2g/M9JQ/DWYYmpmHTvaKw5PEwewXPZX58TEKrHNEx364jtUI/TvbCwWznZOhL4R0M7jMKA1ZPr7U1BTtJejIPDSXtnCMIEPorm8cLbEIrtu0S5pvTHjKu7VPh5wv5PrhXlqQTyOpCycDVv9N/YgQa2iQfNVQ=,iv:hku0TuIQmdjLii2tvzyDOMNqnN0kdtfxBpAqYgzt6V4=,tag:O1b2erAe9jRabF9lBlyOvg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
