apiVersion: v1
kind: Secret
metadata:
  name: opengist-secret
type: Opaque
data:
  OG_SECRET_KEY: ENC[AES256_GCM,data:lNqLucjiiuMmisaBKeVIGHy59f21PM23PlhNSYLisqzpjwhbXzQDkn0z/Dyg76TO3ootowYPCPRu/ogVB6pluNMH+C6ooy4VLHFn2qRTn2iEw2XFlO+4Ig==,iv:22i0fAjtfXcnNqXGLckYKV82ABdYHxDGZMSnsT9eA8s=,tag:yGypfWW3sYdv6btu9ht3Eg==,type:str]
  OG_OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:UEFdbMKKsaq/Ce12k2CxWpWZPqs=,iv:O+Aqj94f8z52rqVLtBLIY+1Eqh9uCMDTILmwM+IUPwc=,tag:FFyWM+ctgtcVsp7kdHsM+A==,type:str]
stringData:
  OG_OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:NAZKJktDMcyuYg==,iv:FKx3GRUyJZtxqp1QxWwgoMsbzwFyqIHVozlvHC+SiqQ=,tag:JgdIpmhuNWqol/E5+VcSLA==,type:str]
  OG_OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:1lfeVSqjvpW0yw4TD+NfvtgpA4zvpl102vkTFjYOHDTiokFF1uqR2GNPvBaJNspMANYLkQVDTBgtX+/CSg==,iv:Dx9bpOlZmzXTmAZnv/6GiEzJfir2ylHM0AmQ/u4etcU=,tag:gXHpaNXcpW9/o3t49Nn0SA==,type:str]
  OG_OIDC_CLIENT_KEY: ENC[AES256_GCM,data:mQi2A2v7MXUhFBV8FcZY0X2X2bvRJo2jtzxEL3yAKB8COAWU,iv:IJcaxt4h3Ykrt0SXZGZsffrvd1vM/JyWP/IwAeBkguc=,tag:xmWUzhFqfoudEYXnRN7yeA==,type:str]
  OG_OIDC_SECRET: ENC[AES256_GCM,data:q0/0iGR8D8r/6+9eggI4+RSeUZx7dNfVjzUOX/d91RE=,iv:czLW3nydMJyEFDVpEHdYRT+HqR4NEbcxOKJtLbsvjOg=,tag:BN0YTedPJIcjwD2XHN3xAg==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOVpySXpSd3ZDOVVpSWYz
        NmMwZ1JWK3o0RlBna1pKTWJyREFjNm1vL0dvCkI1NWlZRy9JN0c4UFRYbGNyc1p3
        dGZZcENISi9KTHpROG14MStZSGhNbGMKLS0tIGlncWV3aks5YkgrWHcraEVYM0NM
        Q2R5eUpIRDdYQ3dqajZYTHBjMUVzcncKvlmpzrtl3/fvvBko5f3uhfTn3G0kunuT
        pso4Y15ydQIfu9+1YbwoQMAyiIq8ha0bqwZ58m502zpamTcmuqcPwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T23:09:10Z"
  mac: ENC[AES256_GCM,data:yamG5RGQjRG//B2XiLZY65QnJpSPWLuP1xjnSbTZEYROQBROlTTF4QMgjdq3n/WqCDx3WgsPNbAuQtAn0tBVS6Is31etU40JIYXoTQAspW8AWzhRHilAhUfpao3oXkgmtjC0sSFtLHoEa90zdxSVslFHpKsMRHcHzcBSyncXrcg=,iv:FsU9iU0xc1+bounYFN+5r/xfWf1bH4PxVUXb04BHsho=,tag:0/y//qaGReXA/DtahlJNow==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
