---
arch: amd64

hostname: yuyuko.hosts.prettysunflower.moe

ssh:
  hostKeyPub: AAAAC3NzaC1lZDI1NTE5AAAAIOxz0n2dQ9mU7GMYBPQKGa8mIKRQ5FfEypWV943IAAiB
  keySignature: AAAAIHNzaC1lZDI1NTE5LWNlcnQtdjAxQG9wZW5zc2guY29tAAAAIEOqO37Un8xn8pFta52gOW0a/GOflhuWxJDuzLAitxUXAAAAIOxz0n2dQ9mU7GMYBPQKGa8mIKRQ5FfEypWV943IAAiBAAAAAAAAAAAAAAACAAAAIHl1eXVrby5ob3N0cy5wcmV0dHlzdW5mbG93ZXIubW9lAAAAJAAAACB5dXl1a28uaG9zdHMucHJldHR5c3VuZmxvd2VyLm1vZQAAAAAAAAAA//////////8AAAAAAAAAAAAAAAAAAAEXAAAAB3NzaC1yc2EAAAADAQABAAABAQCsRFCAgMVGqIQ9UJa0dGBOfaU32z7TdSo1+Ds40PRCwfVh378XK8Jxl6+nIQje3rMPme3yxz9MZAIww241NShfc6qGuKKAh0wtHcuc7OY1syBJovS7qRf+T9LXFqHxzlrq653c73Jm6ly5gM0YdCEZZtaoiWvAZ2ZGzdGGzqdEXzESNM3M59A7MKORwj93K0mgsBsvtNdHTh1aEWPuVSJtxQeUd5OPbNSidW+MkXqGWyqQtH/yAwFcRPLJi02qFRCFIWN6F7lDMrrlPe39ICDPtxZAmvPeZWbx8eqwKTeUj7ugB/nOAD+C0tgioWWKkB0Yoh+dEJX2sJvur4a6ScwLAAABFAAAAAxyc2Etc2hhMi01MTIAAAEAWctIJSm51FPBU/hiaKLjJr+HxOSnUsimj/MSj8Iaulk80+aI1tiZF2PsrHkmv1bj7byrEIfztYkPTycQcg2RGHxszOUmPHMZ+gMD4PboYwGXDQzMVn4I2VyizW/YZT3VHT2fZ1NLVguA39OGWjGbeJP98DzDKd5prcZ9uTfXbqg8R0h+3RELwqvPzzioRIk6EVXueZu9/6VV2avupFdASjdi2fN1S3kGku3C2mqsyN57jTScPB1gv2wy7kv2DG9rwMudLxrwaKd3AH/nz6LL4dhI+ap0MO8isF7YhmckluuZQq5OzA6bVbBcPSCfJujoh0Mjyv8rqctcwKQn6QxCAA==

templates:
  debian-trixie:
    id: 105
    url: https://cdimage.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2
    storage: local-lvm

vms:
  lix-test:
    id: 104
    template: 105
    cores: 2
    ram: 2048
    autoboot: true
    cloudinit:
      user: prettysunflower
      ssh_keys: "{{ ssh_keys }}"
    ipconfig:
      0:
        dhcp: true
    network:
      0:
    cd:
      ide0:
        iso: debian-13.2.0-amd64-netinst.iso
        storage: local
    disks:
      scsi0:
        storage: local-lvm
        size: 32
  media:
    id: 107
    template: 105
    cores: 2
    ram: 4096
    autoboot: true
    cloudinit:
      user: prettysunflower
      ssh_keys: "{{ ssh_keys }}"
    ipconfig:
      0:
        dhcp: true
    network:
      0:
    disks:
      scsi0:
        storage: local-lvm
        size: 32
