apiVersion: v1
kind: ConfigMap
metadata:
  name: karakeep-config
data:
  MEILI_ADDR: http://127.0.0.1:7700
  MEILI_NO_ANALYTICS: "true"
  BROWSER_WEB_URL: http://127.0.0.1:9222
  DATA_DIR: /data
  NEXTAUTH_URL: https://karakeep.prettysunflower.moe
  CRAWLER_FULL_PAGE_ARCHIVE: "true"
  DB_WAL_MODE: "false"