apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:DJbL7QPIcnf6wvqjOlDJIAODKacSMgtGLlydVeCdbNra63J2r5+18PHf4NEUC9sa,iv:K+LcU1rjAGI0acnlSWwkr82uH9ZzIrSDtRwIFcuxDSU=,tag:b6OE6y+2J7Dz4hQ0XBhKrA==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:UZh5TQukGvTDy2XLr4aQLzRDrXexp+XjBxdpTXVy9tpIZq4A8SfpNGfl/9H1B/3Z,iv:c70bZ2heTYQ6r5PTKEJgGSXwQG1qgItm191BXnxVPCc=,tag:zsyMTKbwOEHmt7fa+7gF3w==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:91ktpGcDB1KPFj17skHbRHC1DBrVmNCpaZ4j3T3Z9NvC4wpnmp598mvIF1TzpeVuKSMEAwi51/W//sc6i1sdc7oG9WzlsWK50DlvVTlMnyetnhGq6cnB0eeHP5T/1J9Ggl6649B7zx5fIOPTKNOFai8R9scyoLD9u7iQaqH5OHZJVRdedQDqDvn6a63CgPxoFIsAgPKphECDihZE/7Guv7ZJwLHh/Rg=,iv:kqyzsqZ5Oi07yEC66XOHPDp9mOnr/L6NuEDkPv19GHU=,tag:L2C2uBOmjageD+uv7ZXmlw==,type:str]
sops:
    age:
        - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVW1CQWtoUjN0RFRMSWQ4
            akdVTTl6UFpuaFYvWW9pdGoxSDVIZWpnbXhjCllJZkJTdmRnNVptc2JOQWEwQXhs
            TUgxQnRMRXRrc3JQUXpaWk5ub0s0NFUKLS0tIFFPT2hLenJPamhOZHdwMnBUWVFM
            blB1WVhhUklJTlVMa25MdmwwUGpvWXMKQ4+7CyJAfdMYevFDBE7mWdsWqCFQbEVZ
            BXGQfH4mbiQ8llNBIflLMNUWHtcYBy7szNA0LVuaqp4ceX8b6+eQEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T05:47:40Z"
    mac: ENC[AES256_GCM,data:S71mkH5O/BRQEOhn8OGDv8smPG+SsmyorNv+mdUcUOsnd/eigcS/vRB8AlkXosDCO0GJ9njPYwIpdkV6amBhV8StjqPv/O8Sm2prMRlmfifO2zrlL65kWapJMNP2SzvAuGOE6ZxEGTfaS4t+7mWhKMrQzhSyuHliuP4EPSG2cNM=,iv:7vdFGpVwJHI9f6OUxOEAptSsY9znI0rJC7iQhmmwKB8=,tag:eftGMYprCXSOLYH9KLsujg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
