apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secrets
type: Opaque
stringData:
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:2oP4c/esm6EcUg2fYu9RlG3TwyuhsmIS0j1wb9a7vZ9rkWA3wAxnlsPpNJN04j4b,iv:qVPykcenhjcSPz5kZ2oErXJiVK7iQkHBy3N6/lFUjWs=,tag:pQ9j3ZoKM3SR7Gma1ICrMA==,type:str]
  MEILI_MASTER_KEY: ENC[AES256_GCM,data:Y7VKlIrnqfPix9aJj5xyEcVURo2olnYhETf5rojDFZ1S94Vkq2ChOl8Vuugtgth5,iv:8loc5bwuupQzgdoFWpfR7Jdrj+fqs6DJilfhWi0luns=,tag:SAkNzfbq997/Q6b3lxszEA==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:jzBW52sqLiGKjO8hb22QdD+kW0gCp0PpDl4Wti3woN+rcFJaPehSjhb2iqUpRJog4r9Y1bCFDTeW4LW9/PVIwhkWrfkNlJFgRmCmKxnBVfr2iKqpUmG6QfF4RC6YgDnD9RUTczzZ+R2DdCaCIBVuMyRvhUlnMnF9vTIZ1iqou3oB6uQeGAdoZcYlOh6oDW/moAulB3x8KcHm0OZfRbe4/TjsWx5lajo=,iv:WAAxHljjH7tUVVw/rIU3Mnnsr2Qbrfg2ClMxegxK8mU=,tag:rgP7nVo2WPUCnz3p4zH/Mg==,type:str]
  OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:BbCjBB4tiarArY8BWfk3RacBeL80f1BxcVDq/H5MoeM=,iv:2aug0TuSJQx40tTBxRIZCPQywxHuaIrLCOpPpL7MQFA=,tag:dXMFK4prr0sMQt0p0xbxpw==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZy9KbHdqVnlXbjBCays4
        Wm8xRVBVM2F1TnNYNzJOU015bitBcDhoNWpnCjRQNEZrUmNuSHkzU3RiL0xNWjhq
        N3RqRCs4eUVKdEFuMW9tT3pMSkdzS1EKLS0tIGFaU2UrQm9oais0bjJKZUxPeVhF
        QjJEY2VHbFNWZXNESXBsTWhYMTVUWGcKUxpcYnGuFWbwKaQT1+8B0hLbigOvEVy6
        IwKC3/IY7P/5k/1wgQBmO2ZMVGKEOGa1I4knvgK3s9eBR1wPhpLdjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T14:05:00Z"
  mac: ENC[AES256_GCM,data:6wKjdI5b0XPtXOUwJ9BMKNzDWXk677DdPlmTvBkokn2vhjyxaKPd92dnkVrwtSdhdJEz0ecenI9reCJDHnnrWY4HGcdq3Tv9db4IjKHq0Hti/8xKO+0UnsLXrxkjBQ4KX8ZEkaxu96ki2J2roo73dQNMZhAYKYQwa127se07H7Y=,iv:vbWKmVO0+MJ4pNUGXZfhjhgWwj0j/Vml2PYD01P2Rkg=,tag:vCY0ySGRzRTj02KhnXprpw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
