apiVersion: v1
kind: Service
metadata:
  name: karakeep
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: karakeep
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http