apiVersion: v1
kind: Service
metadata:
  name: karakeep
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: karakeep
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: karakeep-meilisearch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: karakeep-meilisearch
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
