apiVersion: v1
kind: ConfigMap
metadata:
  name: changedetection-configmap
  namespace: changedetection
data:
  PORT: "5000"
  PLAYWRIGHT_DRIVER_URL: ws://sockpuppet-chrome.changedetection:3000/wd/hub
  BASE_URL: https://changedetection.sunflower.lgbt
  USE_X_SETTINGS: "1"
  HIDE_REFERER: "true"
  TZ: "America/Toronto"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sockpuppet-chrome-configmap
  namespace: changedetection
data:
  SCREEN_WIDTH: "1920"
  SCREEN_HEIGHT: "1024"
  SCREEN_DEPTH: "16"
  MAX_CONCURRENT_CHROME_PROCESSES: "10"
