apiVersion: v1
kind: Service
metadata:
  name: changedetection
  namespace: changedetection
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: changedetection
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: sockpuppet-chrome
  namespace: changedetection
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sockpuppet-chrome
  ports:
    - protocol: TCP
      port: 3000
      targetPort: ws
