resources:
  - ../common
  - local-path-storage
  - actual
  - autoupdate-teable-figurines-currencies
  - epicgames-freegames
  - flaresolverr
  - gitea
  - glance
  - immich
  - karakeep
  - opengist
  - outline
  - paperless
  - pixiv-notifs
  - prowlarr
  - radarr
  - sonarr
  - publicfiles
  - qui
  - radicale
  - renovate
  - suwayomi
  - teable
  - vaultwarden
  - backrest
