apiVersion: v1
kind: Service
metadata:
  name: technitium
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: technitium-dns
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5380
      nodePort: 30011
      name: http
    - protocol: TCP
      port: 53
      targetPort: 53
      nodePort: 30012
      name: dns-tcp
    - protocol: UDP
      port: 53
      targetPort: 53
      nodePort: 30012
      name: dns-udp