apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketid
  labels:
    app.kubernetes.io/name: pocketid
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pocketid
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pocketid
    spec:
      volumes:
        - name: pocketid-data
          persistentVolumeClaim:
            claimName: pocketid-pvc
      containers:
        - name: pocketid
          image: ghcr.io/pocket-id/pocket-id:v1.14.1-distroless
          ports:
            - containerPort: 1411
              name: http
          envFrom:
            - configMapRef:
                name: pocketid-config
          volumeMounts:
            - name: pocketid-data
              mountPath: "/app/data"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            exec:
              command:
                - /app/pocket-id
                - healthcheck
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 90
          readinessProbe:
            exec:
              command:
                - /app/pocket-id
                - healthcheck
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - /app/pocket-id
                - healthcheck
            failureThreshold: 30
            periodSeconds: 10
