apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtubethumbnails
  labels:
    app.kubernetes.io/name: youtubethumbnails
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: youtubethumbnails
  template:
    metadata:
      labels:
        app.kubernetes.io/name: youtubethumbnails
    spec:
      containers:
        - name: youtubethumbnails
          image: git.prettysunflower.moe/prettysunflower/youtubethumbnails:latest
          ports:
            - containerPort: 3333
              name: http
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 100.94.59.38
