apiVersion: v1
kind: PersistentVolume
metadata:
  name: znc-pv
spec:
  storageClassName: s3yuyuko
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: znc-yuyuko-pvc
  csi:
    driver: ru.yandex.s3.csi
    controllerPublishSecretRef:
      name: csi-yuyuko-secret
      namespace: kube-system
    nodePublishSecretRef:
      name: csi-yuyuko-secret
      namespace: kube-system
    nodeStageSecretRef:
      name: csi-yuyuko-secret
      namespace: kube-system
    volumeAttributes:
      capacity: 5G
      mounter: s3fs-fuse
      options: --memory-limit 1000 --dir-mode 0777 --file-mode 0666 -o allow_other --uid 1000 --gid 1000
    volumeHandle: znc-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: znc-yuyuko-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: s3yuyuko
  resources:
    requests:
      storage: 5G
  volumeMode: Filesystem
  volumeName: znc-pv