apiVersion: v1
kind: Service
metadata:
  name: znc-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: znc
  ports:
    - protocol: TCP
      port: 4921
      targetPort: 4921
      nodePort: 30004
      name: https
    - protocol: TCP
      port: 4922
      targetPort: 4922
      nodePort: 30008
      name: http