apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secrets
data:
  .dockerconfigjson: ENC[AES256_GCM,data:iNVZ4TvZP5DSTvAe19xyWl8T86VZztp21I9rWPqjtW+4Vwk01GchwPJPTXJ7F9UGQ1uFKUdlqM1F2g/872xS3TI5V4myu1VfFlXJpXS6Uv0dWkqbuKIwXTayL1ajmNUhvvLSWkO47YVFsnjDK1ngq3UD7yTsKXS0Xv91tQNEs/EwHILNpMyUPGDU3krzWsMMgH/vy54GqBn3PovV5jBAMcboyzCq2sgRZEqZ+ZPTp/DOr4V/d5W5NN07V3iP4+f5hq2ensJTaUC++PMMJK+n6/1dCOwOA+1Tpy/lsHtpMYAByP+MiJaJuF2cmAdSDw0DkP3GIV6h8GFkggXTp92jS5fpeTJU88BzUjW6ijvYCOD7Y1M2wYCjGzxN+YZOAzICGmAUbye/YR4eR9IVgUiSb4mFFjlguIjdRuuWGJqX7hqp8rWsNNCrvxmIA62UnwlTNpr3vkgriGTQmBsw/zHT6LS57jMXMh1K23FAtKwYNSOoceoYXWuJ1rFrgfxY71LjVj2jdWqMpuLjvIizHgMyKH8CZ31I9pQ8FybJOSKmeBzDlYI0ppbvJianKFFvei0B3iFnVqffn70eV7td99hobK/cLzLAZCiae3j4w1o9KxzbQlEbFCcTQaCkCsJMKUMhGK5mkAjn6V2ZhVHqQ1UvZq+jCLqo6NB0YXecmy9HoIMSIFZle1JCRQIZ/n4C6lR7C3W7E7pN4UJhXt7rwyEr1qhpuUqyrOQGbrdwLDaWap7On5Y3VPIWe2IVD722JJraT3Mv4sAcFWcgRDmGaVrgzsWtP2q0xojFeF7BHLUz0zHE8vgeLtpmdGsoIYscRkUATVq49kRVNSJYLF2NTBu9cegGJxwtZDYdv5pQgPEalvhD8MsaeVFGxzlcL+FBSFX/8/VikMS9mxJjhc0kxGs0RP1bLHRx264KyU0CzkRSStRFs2mQJlOJ0Ed1WRFfIg6zNPiC60kT8uf1v49WE/Mk6bVqjFZu28GrtqH3RH34/AbTz6wtsVWGmA==,iv:pH6k0c/BY7/LgJk3IG+A1OZSCkJ9+bHleP1vMHlynsA=,tag:6YZjmf6XPeJ4jyOueVptxw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ0V1aTRFVk5VZ2QvMEFK
        VHdzRTNlMitHOC8vTVdzTzR5dThnTHNHRFg4CmlEUnI5VDlUOG9mKzE4TkJ0cjRC
        VmtsTm1sN2lTRmNZMzA2YnFkZHVOelEKLS0tIHpDUTJXUTI2VFc4NXh1MG81d2N0
        L1FvbGhUOG9EdEtBL0NBc1IrZXZReUUKdV973LSEDcFQzkuIb4Xodkl//Xj/URFr
        /XupsTflza2Of8VFhvE4n0OzNocbTXy9dqDUeLWWu7yW2bPluN74Ng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-21T20:06:44Z"
  mac: ENC[AES256_GCM,data:mv8VZdG6cN01+LjpA+p/FiY+HMRs7bXitPIyMMxInSCt6t02ZyobXmOKItZKRT7Z79HuEitisLHYc3uutT+HY5stpePoIpuhcrZ4Wra7tppvn8NKufYBpSzE446DYnV3496IciZl/NhGClb0qXwucw4VhQ8UrVpErx28SE7QMYI=,iv:tbXvxzkZfJdiV40Gae1MVYaUD3ZIFYbK1l/WJ23GBvo=,tag:/fZbWii6HK1Vbi8GdF6l2A==,type:str]
  version: 3.13.1
