apiVersion: v1
kind: Secret
metadata:
  name: gotosocial-secrets
type: Opaque
stringData:
  GTS_DB_ADDRESS: ENC[AES256_GCM,data:rp9lzASbuvuUVdLQ,iv:wem6mWxcjEeNPfA2zLnI+R84VepDnk/7EPRWY6Ttbh0=,tag:X6vnwuZY1pC7TF14J1rhaQ==,type:str]
  GTS_DB_USER: ENC[AES256_GCM,data:YPNUJANgUY/Deg==,iv:tJgOnsYpatfP7CYz/Yk0aOlEgypxjG9gNAh/lcm7/gg=,tag:8vFEOtZJs+vKrXWRx1xGbw==,type:str]
  GTS_DB_PASSWORD: ENC[AES256_GCM,data:12PwPDFx38wAkUuR+8++,iv:QxSz4H4LEiXaAfvDRUNsOOJRbtafI5eQGxGSf11r7pQ=,tag:9rk1fzMA7LLCe5WC5DKJPQ==,type:str]
  GTS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:V8iHXQ1qceAgam2/EKHQkcRRfr5/jsNRSPYh/Z5mkIs=,iv:ENP6utPMADmz7/KAqW+kxQR7CvlnUbmBs9vTHDJEAwo=,tag:UkcM+MHTUJMuo2ECZCfiAQ==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeXJ4VzJ1bnFhSDBTT3Vz
        RjRTOEFuRXg4VGUrN0ZzTktRTmYvZVo3c2tzCmdRNFFBaE1jUmxQblNaaUFZeWU2
        S203Um9mZmgvZXNyMDlXQnhtSjJqNFkKLS0tIEl3a3MxVGdNZ3Q1V25GYUZmWHRj
        Nmd0VlhVMzJ4WWlVcytKSGpiRDFvVVkKNSO3aIJSIN+LmypH8HvsvDzqfC4bRlsL
        BBE4qm9yzjclr6OqwAMB7qb5M/v1Q0j3LUx6na2Glt0n/JyY3JS64A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T01:58:55Z"
  mac: ENC[AES256_GCM,data:qC2L0QJwtZBYwI1gxVau178hAK/1RwY/TeDvnUDwmAHwFFXM4SCnlOhxI9tqbLAIcDG6hzvLt+RALZp+ThniYENFsYo7HybiMYrDytg41l0TsVypWSE+yQTCFp4ho1xRPURLUJZnQuygL0I0ano4KWBEZZIAFMkWKiZG7y/RDQY=,iv:voajhTfRpbfVbD12LEDNvd7dZKoR7N3NpXsqc2+QyQk=,tag:kMIPKMQ4G7jE4oIh36M3Gg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
