apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app.kubernetes.io/name: miniqr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: miniqr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: miniqr
    spec:
      containers:
        - name: miniqr
          image: ghcr.io/lyqht/mini-qr:v0.26.0
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 100.94.59.38
