apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pixivnotifs-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pixivnotifs-gallerydl
spec:
  capacity:
    storage: 2T
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/mnt/yuyuko/images/gallery_d
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pixivnotifs-gallerydl
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2T
  volumeName: pv-pixivnotifs-gallerydl
