apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  namespace: vaultwarden
data:
  DOMAIN: "https://passwords.prettysunflower.moe"
  SMTP_HOST: mail.prettysunflower.moe
  SMTP_FROM: vaultwarden@services.prettysunflower.moe
  SMTP_PORT: "587"
  SMTP_SECURITY: starttls
  SMTP_USERNAME: vaultwarden@services.prettysunflower.moe
  SSO_ENABLED: "true"
  SSO_ONLY: "true"
  SSO_AUTHORITY: https://login.sunflower.lgbt
  SSO_CLIENT_ID: cfe9fc91-b926-41b6-ba6a-ebeca5bbbdcd
  SSO_CLIENT_CACHE_EXPIRATION: "3600"
  SSO_AUTH_ONLY_NOT_SESSION: "true"
  PUSH_ENABLED: "true"
  PUSH_RELAY_URI: https://api.bitwarden.eu
  PUSH_IDENTITY_URI: https://identity.bitwarden.eu
  EXPERIMENTAL_CLIENT_FEATURE_FLAGS: ssh-agent-v2,ssh-key-vault-item,desktop-ui-migration-milestone-1,desktop-ui-migration-milestone-2,desktop-ui-migration-milestone-3,desktop-ui-migration-milestone-4
