apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
type: Opaque
stringData:
  SMTP_PASSWORD: ENC[AES256_GCM,data:dpHiyzUxcc4Gpn9EIZw=,iv:Erz98SFIsX6/oLKQTOnn3gEXv8wzTuajsT0aCoDHG6Q=,tag:WJba+OzK7YhtVQ1DYoFh0A==,type:str]
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:6xoXbJ+vM8P+2iJXakI1UzOSSIVVgyKQZtU0L8Z9kKU=,iv:FzHe/ivecTYyGP0+ssFtkA2OLw8bTyMLACRTLtZFV/k=,tag:wDpePQ5pmEeI5Ix9QT02sQ==,type:str]
  PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:g1TSu3rzCcPduILYxcBP1Mm8V1/LNVnJxT219N5QDXh+lG5Z,iv:SqpcsDL0OEmq1ulZaPSlPVHTBQwmRkErq/2jgQT5RCI=,tag:T/3fFTO3FdJR5Hf5Aas5Bw==,type:str]
  PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:c7lmd4ned2ge1MAVs2xYk1c/jAU=,iv:rzebqZR5muDKVOrPM4d36CdNNYTriNdHUW1OaTri3oI=,tag:48TqZTi7OUQlXnGsLh4/dA==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDc2o4OXkwVlpaaUQ1cURr
        YWVFbFovdTBFdE9mVm85OGYycXpXM0xYMzNvCkZOY253dDhCSXZ0ZC9rb0pHRThM
        TkFpUjdUWXI4WVo5bmJ6aDZlQ0xuQ1UKLS0tIC82OSsrNVYxUitJWXpKcVhNTjNz
        cTl0SXlRY2VhSHBDajUrYlRCQlFteEUKtMJepyrtt8BfrB58JeNetV8yHM6bUGZv
        0LVk58VRDOldCOmYH73hfBnYiBdA9AH31Et29LNLGhvkuIQjclTi5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T14:05:00Z"
  mac: ENC[AES256_GCM,data:uIv9ZaqtwOUYbqYUGaC3X1RjhEX8pNm2VVJLUvf56w2JaXN4boRFMElHHCulEAVH2+1H5zA/tXkBYefwtVjKUGDd67V/qeymhBz+EPNOUbs/UdvSkbl2WdLVd0kAbZMlT+m/c3TgbYOF9C9IRgt6k3ghLLr87/uEZaVjX+6bE9k=,iv:laobevItTwT0bSzDSmneIdOtbsTstr0C7u5p1MgF7Lc=,tag:h2SeZHTm+FNGFfCET5ycnA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
