apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
type: Opaque
stringData:
  SMTP_PASSWORD: ENC[AES256_GCM,data:SAFC3mjDvOoTL72N5VE=,iv:dvpZ0h3Ik+8/FWd/BzG0OMZAxoirOb41+rtu35HcyOk=,tag:s+ksf+SjuMSTHKmS9F6DYQ==,type:str]
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:T+2Xp5qCUIwkGe+U7UPhJrJHD/9HhcKEs/ads1rHFJQ=,iv:bWc8/CxSPU6g2rsEB0p4j7cTmu3nW2ilDvsU4ici4YA=,tag:Kx0SJ/oxp/IlWg5y/hMxeg==,type:str]
  PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:vTa6y3gC8+3Lq/Z57DnhjSdvRkjXcoHux8V+kjY3YI+2yfL5,iv:uKrAFcBkOjDL8KKIDTEKlOAKR95gY6BGULn6wxMQcQk=,tag:ES4y3mHpDvOC6GkR1riZMA==,type:str]
  PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:pZp0g9MgxJhoY//M7B6GToecNso=,iv:gcvY2r9Dt74w98MqypXbXzVSxE+PyjwZnF8emDkONQs=,tag:FfRzsit0NQ4OEXjnMiptNA==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTzNwN0ZCam41TVhUejdk
        OFZleEd1QlhmSEt6dDB4Z3c5SWFtbnFzcmdRCndQTC9KNVlLS2hDOU1ad1hUWGx4
        ZTBIZ1poSjFuSUhwbFR2Zk5zdXZtQWsKLS0tIDRUaEdMclZFdGVaNDl5MGdXMXJh
        VzQ0SU80T2ppZ2Z0TjZob0pqNUZuSkUKtuz77P7OHh6sdcExcZOsFUSDLLcfFWSo
        SewJZTVCIMr/mI3zad5XzCIXHBUMPBBT97V0Z6pSmULRSoa7iaUz+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T23:09:11Z"
  mac: ENC[AES256_GCM,data:tADCSlCxhDSrLyqtfu8JanQ/K/3X4+nuDIwuA7pKwlispFmAuzCHKlSeyOreMs1x4ef2j1c+GHbN2Weu/dNYTJgtCLNx5k+GBJsbNXmYKKO0IC7sD3tw38E1q0eK3Uzx/p4IZHseFzjbpncfq6Vk5z3laO9Exn7tRBUTEe+3byc=,iv:FjUO6SnvaAtw7SVVlCD8j+0ag0/CIa9nOIca8m4Odtc=,tag:XfLlJUor4SqRz4Rq50VXLw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
