apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
type: Opaque
stringData:
  SMTP_PASSWORD: ENC[AES256_GCM,data:Z+jwlUEl6iMcBUbpSRA=,iv:vrrQJz7PDvEk8m97B4zJDQI28UDVMk1jfPP3BrDhaW0=,tag:9uGWWAxLZ7cZlHCii/vqBg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:tbQSzpr6CqZrsESRoNg6jUBey5Lvg54saHO5KT0HM9tLAzW8oBM6cMpJvmFfjoO/Z97AmZQ71lk7pDFOcpFj5K+kTzDm0au4UXRd6bkEW9J12ZN97H0Qxiad,iv:r5FSE3ursLAXGYSLvOCn4kBj4DR8oaOyz+oJ4+X//9U=,tag:Lz68FQ8puoDiIxhHDUaMYA==,type:str]
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:+aPtdyqjrQMWtmIUOv8/OuzvV5f3FVGB3KZFcXzYbSs=,iv:QzY8Izf2npGkQsIwdcYdIzbyqvIqGJIqCGGNUDMBUOg=,tag:wfpcGgSL4I7m9BV/zN5l6A==,type:str]
  PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:2NJGewJEgZXG2fzboW16TywjPKp1kvgfqYRnQ+MK3Pw2v0Ij,iv:AKlIFCNpPhzFydM6qK0g90yl3N3M57JMsi4gViF5bvs=,tag:vLtq/DyRhvy+73sag/FTzA==,type:str]
  PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:rSH0luHF3gaujrdN+wrQGcv8XGE=,iv:PSSPFNZ2FR0uENgCGrPfTlZ8yG69kzeAVGjQKsSMLtY=,tag:TIdWp7MdOGiKOT71SNSZzw==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdXRNQ0VRTkt1SE8zbVFB
        QXJEY1gyODV4TVM3YlZwK0dDYWFIYkZXcjF3ClhxZ2lRSFhtbTRaR3lCUHNtTXZw
        azZYa00zUG5xNUZMQVlkdHpuQWVsVUEKLS0tIFhtU0tOUE4yYys5UlpGbDd2dThs
        cGhKQTgrZEdnYTlKQWhTS010L0NoSUUKwudZFtl09CD58AP/w1Yn2YORhtFunECm
        HJ4eAMOkQBbZSc6hrXYRhzT0Locq1nuoqoHiziq5b9jrxzmsWacwTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T00:45:07Z"
  mac: ENC[AES256_GCM,data:rjGv9s6X2iGvZ5/OagMjrlXhqU+J/Kd1sWgsVxjWIa6JLT85sSDiel6+TGJ/CeV99qu0Pr1ypLPQ/+ki+C04PfCst7utn09jRtsNcHy2tfwvfyPCB1B2v+J+xMZLesadytrWEXiloKr6dlooSO6s+jYN1ss87IKNyK5yayzqH50=,iv:crkt2b1ro957L5J3xQOLvnJMTgG54HLElcFid9+eAJA=,tag:fzX1or2JfKFaC8nWCaIbTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
