apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
type: Opaque
stringData:
  SMTP_PASSWORD: ENC[AES256_GCM,data:1LeYfmexIPE9eZrfvHW1xw==,iv:CV2RCjQtM2F3H4p1BV54OUwu9An7V8cFs5vurnb389U=,tag:kZvBGbnfNNhj03fYmhvLIA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:vV/aoDKZntEz8vtsBbP9UQ/fFE3k69K5HYz15kLm9Z3tq796/Lka2HLBHq/Dn9nd4PI0P/8Z2kXztEdhHaInahP6igNkYvCrgHgAOIheGYQ1L/p2lTmG1uVQ,iv:d/oUA3j58kMi2SeTiqjWUqh0hcWVHpOrJJitDOPbzf8=,tag:3xIOe5KQivuHx0pJdHgg8g==,type:str]
  SSO_CLIENT_SECRET: ENC[AES256_GCM,data:aVUJddAVQBPESR1GfdDGXFArn2pHNFYHrHOrTFJBsxk=,iv:KBXZ96W4HCAL2N4YmTN0UNDKb1CxZ452mM5wB0qpyO0=,tag:wZqwz8ZSd0aFFHdtADwBkw==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMnc3cVV4SFdPbHYyaHFI
        VHZ6NzlZYTZjdWtiVDdxNkxiS3M0dHZMTkZjCituSWlRNGYvenF3QTN2SXZkOUxn
        L2pjMzNTQW80aVFYUVlSaFpyMGlXWFkKLS0tICtsRlFXSEZvbUNJbEVZY0IxVWha
        Rm1KTVlhakZiT0RZL2N4aVhQbGREZUkKGI2f0MVBc8OfO+eDGmB+QsAFe6zIDdb8
        jDUDCmaxqtDZnot2AxjEdEB+S8f0yfF0E8GYzSsHF7SpsIAcJ7cLNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T16:06:32Z"
  mac: ENC[AES256_GCM,data:o65Cf/nsOtwcbE1qhcS4ctoAlhV6FEht7SF7LWHiUOGBiXmcaIfF5LbbC1YSMmRvMWO3TwqTc232EH5AxAQJMiLcBkErZyQx2TLttEHRYKbG0WaZCMQpSb0p/y5UWqPH0VtFTxP6lBh0ZC0hOI3msZEk/ddFLrD96GcpvCDf3J0=,iv:fRy0/RuuRQRJ7M3cMjkJgE/YRSAx8ukg23FKUYtP3nQ=,tag:LUUgi7qhRgNiyRwU01HE5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
