router id 193.37.139.96;

define SUNFLOWER_IPv6 = 2602:f31b:3::1;
define SUNFLOWER_NETv6_2 = 2602:f31b:2::/48;
define SUNFLOWER_NETv6_3 = 2602:f31b:3::/48;
define SUNFLOWER_NETSETv6 = [2602:f31b:2::/48, 2602:f31b:3::/48];
define ROUTINATOR_IP = "10.0.50.1";

protocol static {
  ipv6;
  route SUNFLOWER_NETv6_2 reject;
  route SUNFLOWER_NETv6_3 reject;
};

include "bird.common.conf";

protocol bgp yul {
  local fd00:10::1 as 402919;
  neighbor fd00:10::2 as 402919;

  ipv6 {
    next hop self;
    import filter only_self_net_filter;
    export all;
  };
}

include "peers_yyz/*.conf";
