router id 4029190001;

define SUNFLOWER_IPv6 = 2602:f31b:1::1;
define SUNFLOWER_NETv6 = 2602:f31b:1::/48;
define SUNFLOWER_NETSETv6 = [2602:f31b:1::/48];
define ROUTINATOR_IP = "10.0.12.5";

protocol static {
  ipv6;
  route SUNFLOWER_NETv6 reject;
};

include "bird.common.conf";
include "peers_fsn/*.conf";
