define SUNFLOWER_AS = 402919;

protocol device {
  scan time 10;
}

function is_self_net_v6() -> bool {
  return net ~ SUNFLOWER_NETSETv6;
}

roa6 table roa_v6;

protocol rpki routinator1 {
  roa6 { table roa_v6; };
  remote ROUTINATOR_IP port 3323;
  retry keep 90;
  refresh keep 900;
  expire keep 172800;
}

include "filters/*.conf";

protocol kernel {
  scan time 20;

  ipv6 {
    import none;
    export filter {
      if source = RTS_STATIC then reject;
      krt_prefsrc = SUNFLOWER_IPv6;
      accept;
    };
  };
};

template bgp nyallopeers {
  local as SUNFLOWER_AS;
  path metric on;

  ipv6 {
    import filter common_external_import;
    export filter only_self_net_filter;
  };
}

template bgp bgpexchange from nyallopeers {
  neighbor as 24381;

  bfd graceful;
  bfd {
    interval 10s;
  };
}
