apiVersion: v1
kind: Service
metadata:
  name: nyallo-website
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nyallo-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
