apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-data-pvc
  namespace: teable
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi