resources:
  - ../common
  - anko
  - cim-monday-helper
  - docker-registry
  - dolibarr
  - flaresolverr
  - gatus
  - httpdebug
  - kakigoori
  - mazanoke
  - masto-fe
  - metabase-contrefeves
  - backrest
  - enoko
  - miniqr
  - multi-scrobbler
  - ourfigurecollection
  - pocketid-remilia
  - pocketid-sunflower
  - prettysunflower-website
  - rallly
  - privatebin
  - vlmcsd
  - youtubethumbnails
  - nyallo-website
  - immich-dacostafaro
  - nextcloud-dacostafaro
  - etherpad
