apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: test-secrets-vault
  data:
    - secretKey: ENC[AES256_GCM,data:yh1v6u9kEA==,iv:2aPEJhvVHkT+jsTvEiIrkuXIunNYmc1GOXGLw5D9I/w=,tag:dojfLJUvqT2+myc4pTtR9w==,type:str]
      remoteRef:
        key: ENC[AES256_GCM,data:/tLr1nD4gV3d1oGoO0py,iv:cWnxqlzO09ZdtCKCJBPRH3wUEUsXmXxiiTW1Mlqs4wg=,tag:lU91MCLavytWox/cFKW0pg==,type:str]
        property: ENC[AES256_GCM,data:UAAS4amo8w==,iv:GnBggleQEnfNTUVBlx6pphQrMIEkuJvhxQR9zo4pDJA=,tag:yOaShyHvSC4kZ9dSPqD+6w==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOWNieVZFZGd3Z1o2Tk15
        ODZYSmZkeW96YXBmRUxIQkJucmJxUFMxK1NJCnN0YU9RUGhWTEE1S0dJeTZsVGlG
        NXdMWk9aSTRQQnVOMDVMYUNXbGc3aEkKLS0tIHRSRUNNK0lZcUtCVWZSTWFKZGw0
        Y3pMK0V5MUlDeW5Ca0s1SmNDZGwyNE0KPjuYyXQawdk1JOhwe/C5/2ISh9+UzPGd
        26BwmOUQ+3NlWxDBvh/AHxQO4DFJAJNdDnk/t3tyaU1zw0i0bbkIFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-28T18:16:51Z"
  mac: ENC[AES256_GCM,data:A4zoc5UbzDcGwmu9l0w90IogzOKomLGE2wPFCchZdhqYI50GkJPW5VqMnxmElUlyMi87Xj1cte2HUZnNLv6MxzFIJQB7sNyuJArlNkidZtIkVyCjNxuvG/pXdVoPTGSfpaf+PZSd+p3uakNFprxF85ooOXXgDM0GtpYjAFBih8Y=,iv:sv+yhcBpfQM9UCqp3j4qI3aZmgzYjBGg1HLZA7lwQCQ=,tag:dMBmMlYQOvrq3yYrf49KUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
