apiVersion: v1
kind: Secret
metadata:
  name: planka-secrets
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:0brAgpYlrmkqRtm2hKsCFlrY+GdyPDuDD0tmlWChmdCsDfQ/ZiT05MM05imOEjAo890Ya1A=,iv:qaXshwuIFNYhP5qyoPPIXYknvPrZBkevuHSb253mx0g=,tag:WO91sCZHMt9+/DAJkK1o/A==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:95WVH6wGCY09tyXQEw99IM9JuQvU7AniLhD2fE1azAifgfMZv9XmuC2hNO0UoOnCim7ihwZxkmf9c0B0vgurRICPMZtJLRnhvQkCjKjP9LA9KSKgRXznTIoHa+5kCNsRlbQjLaxAL3wdPSBDhuYusP+EvQ5tBV/8PtBILC75dKk=,iv:fiFfGLsbOZnbINyxsHaU/pLefiJM9rRouFA7w76rlGQ=,tag:4HRQAnVDsEThKNyRDHnA/g==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:rvsKS+emHB4orpJDXu0UcEwW35mdeNBJxQFQmqWtVx4=,iv:umzYaWlQjnSNCLf5EkaeAheLVjzy1dVTbJnoCiCsjjk=,tag:38O9CXE/4K1KrK3go4fQ+g==,type:str]
  DEFAULT_ADMIN_EMAIL: ENC[AES256_GCM,data:Uah7JMavD6XgOYU3409/tW66,iv:0pLndjYGLdGrM/XuLweF8nAFIGBgJ7eSYdqY8uLLGaM=,tag:2+3kj2jr8E5JW+kLHzvsew==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOW9WbXlvQWlqRjRxUTJ4
        cExCK05zQTNQZ1FZWW5HbVJHWnFna1VVandjCnZybjNvU0FUcWFqWWRpVlU1YmUz
        YTJ6eWhhMkNHbFlHa2l0L2NHMEhVRHMKLS0tIFVOTS92aW1oK1pjME1UWWN4YTFS
        MCtFMmRhYzhrb1FpN2lTd1dpYlprSU0K/gf16sM9p7p6SlmXpe7kS2eK3oI083W8
        cKBN6ivsasynW6wK77yP5+DAQKKsLL/pFs4oqbiKZPmkHkNlSEz4fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-21T00:58:15Z"
  mac: ENC[AES256_GCM,data:uJ6jWT+Hk61VjaEWUFDsTevrX9VdHQjMaSFOGG3covb9zLOE7o1drHD+L9LMqn3ABhXMsqZpfLfT+Pk3jLnkGXvDCgDgur1EeUpjjDaPk59Femp/D4Oic5Qm24fS0l97P8WVqb8qXSlL9eodhDtGUldWwh7wwd9fwp70D2qxwI4=,iv:jDBnPoi0b93L07R2Pdkr2NLzhnA+0l4/XkjiLd7EuV4=,tag:ArwjN0KRpi7Un2g8iXfEEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
