apiVersion: v1
kind: Secret
metadata:
    name: planka-secrets
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:FOzM94xm2JWX2RpVU5T+qfHOOs5M3E+K6SRIbD25brU4QHhyzzgac/wizQi89U5njN8JEQY=,iv:UepnUBHMJ58mxHVm9ytVm11CHv9Fc3YoUT4alhWGBO0=,tag:pB8Di29gNM5AT8fqNLfU+A==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:9i8u2k+gNxHAiVVx3hFYe8XgvY/bLoF4IpIm0hqgpDIRnWpGE79GrlyI4IHUjVLYg/kdH8182iQgAAe/dSkagzXSgmMfDSVbF4tfcuZmwj4du3P8XToiz6hy0kJVQfSM8d3vChXY5drqm0qHWGVIhDitIorwvgkSE1YEKvcsqVw=,iv:4Iikza2qqQwt4ayxQLLxprKxhCF2wXEmdt/Ryj4CrWA=,tag:bj1m1YgoFvBacxR1egISGg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:YG8dGtDact/zzc+ANdUXOyFnMNut3htyJTWsmO8VC3k=,iv:bx99u0U1yT+b3XNvEafePyHrPS0AFNQAqwvlXbvv9AU=,tag:XBcYxwKj2Uti3WlRphVlnQ==,type:str]
    DEFAULT_ADMIN_EMAIL: ENC[AES256_GCM,data:h//QNyYrnULWiE3xvb3Gq1He,iv:dF1/qkV2/hr4YYeUZKwTTJOPBkbFPJ8BXix00zYD9Zc=,tag:iVIlLRqm7MD/UbHGkEHS2w==,type:str]
sops:
    age:
        - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveW16Z1A1ejQ2WVI1REVV
            WGVGUHByV2JjQUVuNnpYUTI3amFLd3JwZGlrCmVTSkM1bWtwZXdLN0g1T3J6Njlm
            Y0l2dTI2V3JuQmtHTzRUNXhVN3dXKzgKLS0tIEVaeG5POTRIYnovMUtrNFRzRTZu
            WFNEUUw5TnBleDVkVVg3R3haUGRHZTgKwGlavCVy/MEgSPXbWasag3nogPBwDCG8
            pz9EkuWknG1bc1Fh9M9OEXD7tad/pC3+VlokYRFSXQkNqlnZbHZ+Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-01T15:14:39Z"
    mac: ENC[AES256_GCM,data:XOpoG3RAoll/cgTOx8eHU2pIUavDrQLdSNCYoN3qxkI+WEhcLZ7gnWbIgOamBFEBn/jifjLd/JzkRlpkOhCnsbo9DWcBXL21N0knp3WA4tTCnG07YZYyryYXdYn1I45safEM1d1BYgrLYfYoeewLeZxzVxvDIrYyFBzXJbJlTGU=,iv:n+OSkE9gyJqKU35gcy4GpKWLQ6ojPyaLpeyFRT1xzcY=,tag:0laREBs14MLODZxHJSDYHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
