apiVersion: v1
kind: Secret
metadata:
  name: pocketid-secrets
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:6isygM0W/ixvzdiYXfkKzlJGYraqlo3RZH3ENZtZGhhl8poXhVXQx7AJPaM=,iv:4aUAZB5LsGM+2w1oCjE5+DvlflYWy68TRlVNEQOT64w=,tag:j2st71oHThwSO9lezvUPiw==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dXRDSlVWTXVEQlBBWkZs
        QURjMzV6a0dDcVJ1U01ScVgrL3ZBclJLV0FnCmpmRVdGSG9hQjZUK1o5djdTWkhi
        MSt1M0hvaFY5REtSVVZHY0xjRmtOQTgKLS0tIEJGNVhuR3BiMTUvc2Z6bUpqRFpx
        UDlmemxUcCs4SFl0QTEraWhTTDJWc0kKwHRVOQZBgohqcjvLrKdThzmnCAvrKDPU
        HTB1GMSvzkRwwN0MPKiCcwt7QDbdZUXB6ZDzfkDKV38Hs2eiLQWzSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T03:15:31Z"
  mac: ENC[AES256_GCM,data:DASL0qQaahvbe+LRJYqVM8FW7X+S2FA0kkDPu2FSSiiMivhV+bLm1gH1LDcqgs8IqgAznfIggMlKP4b4bcicX1oguc+ejIZ6pw2uBICOrIPUKM6AkY/CChXeYcvKDdh1arkceBSGOr4tjRrcbdHYGtj9ailMj/ROvaOqMehFOvU=,iv:/IrSV1XtA3RfsKOXeGK7y46n/vVE8A0s2N+VgVgpnos=,tag:FmjE02Sp5qksppTSr9kQvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
