apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-nyallo-pvc
  namespace: redmine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-csi
