apiVersion: v1
kind: Secret
metadata:
  name: kikimungo-secrets
  namespace: redmine
type: Opaque
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:xfsft0lLpjjWbWlhYsw2aaMWEpSBGHmO3sdvdaXRYfxAFzRnoeqOQK31dKQay0IkpoM+UWuKEhO5E8kkqjiJiG1/lkZbJkteg5UdBUBtWBw=,iv:z5jSiOTtJYuogG3k9O7h12hbbs78rjXNzdrZSuBn53o=,tag:BEty7Ms4VTt4kArshbUlmw==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZGlBMFJUdlNLaWRyZCth
        Q2hVVDV2dUlWK0lHSUl4TUpPeHhRQm4vSWhvCjhnZDRQNzZXSW9CK2w3RUlzcmp6
        ZjhpV1pMVElVYVM0YmY4WHJ2YVpIbEkKLS0tIEFaVk1aajUyYzh2NFM2ODkvK2x2
        MVdpN0pZMnhUWlJZWkRaWGlsV21DWmcKcKYbnOj2QvfoZYyef4hENF579GBFRrKS
        yRlNc1tITfnIUeXbJHyAUaOzK7UyARONlfESTPmuuXt3iU2XaGJSUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T14:34:18Z"
  mac: ENC[AES256_GCM,data:D+JOzjaRu7Aiobyp348tTDkVX9lBQxY1rmnY9SnOQr7UtW5G3vIFxYQDHvEF4azfTLHbz17xeS4mW7CTJRp8r3vtX6FflDfvJOuHcmT5dYoEfOkstU0u95XD4fEEu4MmVRKMXs5BgLK5ayS3Z232TgB/FHPqxH12esYnLhu+dKA=,iv:c/+Fz0xzdTm+B/osiQop+bNxHJ0fSHnNbetbPIXhHQs=,tag:xLbsE7DHV4LEGNQL09AP2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
