apiVersion: v1
kind: Secret
metadata:
  name: nyallo-secrets
  namespace: redmine
type: Opaque
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:b7+m7oVgqHztlQwSVWO5vKk73eNBm27L0EvWpYhUOCSMM0pzZ5E7J4pKE6eM2KXFj9ShZLnO75Vra6+FJlR8XPr00vu3fWhjB53PF+j7fhM=,iv:KHck6shVo8Q9DwBDAWRQ9ysVUL45k8ryoGQTirpopIs=,tag:9ttfIafNEdGTBYB+q/ZBag==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVjY1VmJMZmVNa290b1pv
        UHRQa2phaXJZMkNaL2ZLbXRIZG54T0VLTVRRCjQ5S0FpeWFIN3VUNlZ6WG9GcVcv
        RDQ1cTVRcTVPSCt0WkVFVDZHdkZqZ2sKLS0tIDVleHZEclRqRC9SR1NnRHZaSk5k
        c2piQ0JCQ3QzTWFLR3VJM2htUlNCOVEKW96QeBTQR3+enF7hgGvHqG3y5cxKLbIy
        KzYErTZ+5+X+B8iBqBNGwIkk0gUtZKsXUdL3cTb9Hp1UQBA6k/XMdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T14:38:22Z"
  mac: ENC[AES256_GCM,data:GDiWlKJYTg1Rl8RDnf3wrBvceqwsYbA22+O5wOqL+TcEJDsdG7jGX5VSsJ9YTvLP5bfvyr07uKR2SUkxTt/+iIF9gtfqLj6zc47nUES5zcNM8iKGB9WeShwKl+pauf4WjTYnTmsiFaNKCXkgPqmx3bwCrZIy8xvVoBM4K5kvLPA=,iv:DsqisQnRjHYPCTTg41SDNGQLBq3Kkf5dFdjavkKcGmg=,tag:gYLVAPkdXJAHgAwzh53nNw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
