apiVersion: batch/v1
kind: CronJob
metadata:
  name: autoupdate-teable-figurines-currencies
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: autoupdate-teable-figurines-currencies
              image: git.prettysunflower.moe/prettysunflower/autoupdate-teable-figurines-currencies:main
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: autoupdate-teable-figurines-currencies-secret
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 250m
                  memory: 128Mi
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: OnFailure
