apiVersion: v1
kind: Secret
metadata:
  name: autoupdate-teable-figurines-currencies-secret
type: Opaque
data:
  RATES_EXCHANGE_APIKEY: ENC[AES256_GCM,data:Qohfd5Tfet0fL0NNNMlXTkArO7h5/sULdKZWX8wAYru3mQSyirv0RNXZXnL+kbt5,iv:lkhQ6RUr+cvYbNPisvODGyKLxmVv7rQMZr6bbcSM/68=,tag:f5aXlwwIl+Gg/FKfA6IhWQ==,type:str]
stringData:
  TEABLE_APIKEY: ENC[AES256_GCM,data:v9ApF6rFQwsgxx14YDBE91FfzkvAQKfc1/XqbnN7QNr/tgH2uem4uZxoWCWHIwiszc9bwj6VzldfiyRf4xzChiXTSCACv54=,iv:d9DGjTAVlW0rDhi0W/GEXaf6UJU4GVmOc1DudhuVCMo=,tag:a/Yew5/Tkvuy+K331vX6tQ==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Qk9xMjVEQUwrZHhzeDJG
        WE51Y0FnZW1uTWtDek4veTMwK3RrOGJJd2dVCjNjNWRGUi9LNkRUOVFlclFVQ3pM
        ODkwZXVDRjIyem5sRjRsWHhEY2pLQzAKLS0tIGxUVkZZcFpNd0tzS1N4NHhENml0
        T3hQVVRkTzVQck9Pa3dEVjZvbi9HSEkKqclw2dAmL8141XmWl71jnuibcMosqvJA
        iWhOwowidiOCADrYev6O+jYvGh79idBhB2ZuBCNSY7ZHChJpWIWVTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-21T00:58:15Z"
  mac: ENC[AES256_GCM,data:i9AEN/UiQ/rs+25SAy/lBEOpW4NJaO3l+k0b+rTHfFq8zXkNzZlLCU1M12Zzl0QI4A9n5E4KmGsLRZjS9WaJAZ/YLG8aY24Gh5sIGz9I6c2nqTrnol5iItUaHRq8dvur67LbWKZYPnMjw9CwMj7EExIAlrfjI8A17kmHYBAfaE4=,iv:dvFdzzKnYYEKWRd/ufHc5iT0CkqsAkhnRt0rCoGz3Fg=,tag:MqAelu2KsMxY32l/AtTZIw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
