apiVersion: v1
kind: Secret
metadata:
    name: autoupdate-teable-figurines-currencies-secret
type: Opaque
data:
    RATES_EXCHANGE_APIKEY: ENC[AES256_GCM,data:v2B/npqWdOWYIg5KYfsB/osjX74DIE8Ei0wopRwiaE31hgXrAran9hWnV2SrtGhD,iv:7n0r3jmukfwdeyrxpP7oypgwXK8WXjRPTYb92AjQk90=,tag:EbTBGFNKsGigs8ro4ZbAhA==,type:str]
stringData:
    TEABLE_APIKEY: ENC[AES256_GCM,data:c59ObB09TG175k6oZKLk+nHkJOo476H2Tinq1FUYfpoeFUmV8zud49FZETNmEZ/mpmO+esrA79ljIjN0DKsikFbCMjrb3ZQ=,iv:kZOJcPowF6WbPmscF+XrmlEKXIpfn7ohryL7udMTL2Q=,tag:KwRGehug077t8cQ5dk/qXg==,type:str]
sops:
    age:
        - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHeS9qODA3THpwSi9zNEFV
            Vm9paDVDekMwR29hVzRGU0svQzdVMGNSQ1NjClFKS0swNnQwMTlhazN3NmxEWXlH
            dXE4ZExJKytMdmlEaDF1WjJMMG4zUWsKLS0tIEVUdUxxVnFsU1R2WFBuVFB5d3VC
            QldkS2w5VmZLTzc0QzVNbGNvbnNRUkkKq2jlzB7g5My7ZZ0KS/Roa5sEakXTC9T2
            kW/NfQ/h/wTpOmZTt84t1HEc120Nw/YvAd0uJHLZRVjHggbAxOHsog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T05:47:40Z"
    mac: ENC[AES256_GCM,data:dRyv+6xHcAeZe+5iMhHpIe17oN4O6/+Q+gwjq9Gxv6dLip4EuoSKl64OHaUNmx6/f+c87hK0PGsEJrSPg2eeJ6qp1E1F9SdJyupRmPN876dZOehXGYTsyHEcpCCo/5vU962mATnMuQA1OFIeNVGnKTrY5fwHKYrYpsy9kB7p1S0=,iv:AOq2ZPjugPCsaXkm8cbzoLp2gF1+UDreIAeTFJllrNM=,tag:BTfUEPuzG6fMbTrJvLy78Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
