apiVersion: v1
kind: Service
metadata:
  name: caddy-internal
  namespace: caddy
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: caddy-internal
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
    - protocol: TCP
      port: 443
      targetPort: https
      name: https
    - protocol: UDP
      port: 443
      targetPort: https-udp
      name: https-udp
    - protocol: TCP
      port: 25
      targetPort: smtp
      name: smtp
    - protocol: TCP
      port: 1688
      targetPort: kms
      name: kms
