apiVersion: apps/v1
kind: Deployment
metadata:
  name: publicfiles
  labels:
    app.kubernetes.io/name: publicfiles
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: publicfiles
  template:
    metadata:
      labels:
        app.kubernetes.io/name: publicfiles
    spec:
      volumes:
        - name: publicfiles
          persistentVolumeClaim:
            claimName: publicfiles
        - name: config
          configMap:
            name: publicfiles-caddy-config
      containers:
        - image: caddy:latest
          name: caddy
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: publicfiles
            mountPath: "/srv"
          - name: config
            mountPath: /etc/caddy