apiVersion: v1
kind: PersistentVolume
metadata:
  name: publicfiles
spec:
  storageClassName: s3yuyuko
  capacity:
    storage: 10T
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: publicfiles
  csi:
    driver: ru.yandex.s3.csi
    controllerPublishSecretRef:
      name: csi-yuyuko-secret
      namespace: kube-system
    nodePublishSecretRef:
      name: csi-yuyuko-secret
      namespace: kube-system
    nodeStageSecretRef:
      name: csi-yuyuko-secret
      namespace: kube-system
    volumeAttributes:
      capacity: 10Ti
      mounter: geesefs
      options: --memory-limit 1000 --dir-mode 0777 --file-mode 0666
    volumeHandle: publicfiles
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: publicfiles
spec:
  storageClassName: "s3yuyuko"
  resources:
    requests:
      storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  volumeName: publicfiles