apiVersion: v1
kind: Service
metadata:
  name: publicfiles
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: publicfiles
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http