apiVersion: v1
kind: Secret
metadata:
  name: teable-secrets
  namespace: teable
type: Opaque
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:Ox8jXiEgKCKps9uSglV0r51rj3tQQg==,iv:IeoFmFZZlR7qb92riGLoYIGtmEAwwyvGx2WyG8rm0zE=,tag:SSnWh3LkivbFLUWHqYfOQA==,type:str]
  BACKEND_STORAGE_PROVIDER: ENC[AES256_GCM,data:ahg=,iv:qqnV72tJy2IrVE1OOHgne/rrvhoa4rQgxuGic/xDaks=,tag:Qgwusn52PK5Sj5L+uHXOZw==,type:str]
  BACKEND_STORAGE_S3_REGION: ENC[AES256_GCM,data:BS4v7A==,iv:u1uUxVGBTu1YNclMaK6wKUOQreA/kaQX66C55LkfOxk=,tag:aqDieLSC12ru3vSaF6gxFQ==,type:str]
  BACKEND_STORAGE_S3_ENDPOINT: ENC[AES256_GCM,data:rkLgzfHW8atQBIjzGciYaC6n2IDFJg==,iv:jF1cDHWTzaEQJ7pAYCFkTRcAcopo33NakPOaXhtNvOk=,tag:aHrljBpTtrLHu4KrG1a9JA==,type:str]
  BACKEND_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:QFuTyHTAM2BPzo28q98afpDt3DgCWsZYb1q8QmlYUVfs5Ry85WGlwaMn5VnjgaxrCL4HdOYj,iv:0h9ajV44WjshF+b7mixkWNs0f95U1/vFUGm9flBYag0=,tag:vwZKADR/m6JCf70BYQTW9Q==,type:str]
  BACKEND_STORAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:YoaWhKuRsRw6afMW3GBNYrM1IJjf4q2B1L0CN2VWblEAxGdMHpy4wY1ie5cUiOCjghu4FqE8UbuR7rHAAZsMDhOkEke6Uj/O0H2/,iv:jxhcHvDZbdG6kO3nmHvOjtSTplJ4b1es/Rlklv67CSU=,tag:CJTS29kzW01zlfq+GiEDkA==,type:str]
  BACKEND_STORAGE_PUBLIC_BUCKET: ENC[AES256_GCM,data:0/1dZ4n1LAUbjQ/E1JY94Sno8yySiosUvPVVliA=,iv:266uq/mA+2oQF3NV0Nc44ClvSOiGvH6Jkxk0YZ+qHEY=,tag:5D0/0hJx0O3Na1o4lkUlwA==,type:str]
  BACKEND_STORAGE_PRIVATE_BUCKET: ENC[AES256_GCM,data:509mT0OZG30tvY8eSihF7RyucRwcrY5bEKcffg+V,iv:SQMQR+kIzHwrDUY1/1t8LKYX7uL2vC5Xp7aZZUryM3s=,tag:DLaSccG1tq2UIVhhDq1rOA==,type:str]
  BACKEND_MAIL_HOST: ENC[AES256_GCM,data:C3V1AXMPgMESTgjMULiOaqeu4V3iSnoN,iv:caGamB1jWoVb81qzXOC1FcfMXaAKdbmD/BXDNPRZyr8=,tag:JL04jRPEGqslxPkP0D+ZNA==,type:str]
  BACKEND_MAIL_PORT: ENC[AES256_GCM,data:X9/D,iv:sYrdoZlN4lqSPCeQ/PpMFh8/42bw47HZ8Q3nU5Y13aw=,tag:23znFMbNGKbpoaaUajM4kg==,type:str]
  BACKEND_MAIL_SECURE: ENC[AES256_GCM,data:VDIlndA=,iv:C9HpxI6PZauHy5t7IkebqZPwAcoNqbuhm+lcOSbq8jA=,tag:SNT9jJns8ug76oDFCx57Ug==,type:str]
  BACKEND_MAIL_SENDER: ENC[AES256_GCM,data:yOtRA6kciRptcs67/wOHi77bKJh6ZEZANNE=,iv:d3b0OpKHXr7IgjJQf+WeJ/6xsSlwzhpvkZIrwyboxCc=,tag:Z9zPiFI6SSMpPyUEbhlo1A==,type:str]
  BACKEND_MAIL_SENDER_NAME: ENC[AES256_GCM,data:6opiNw==,iv:ilIZu2lvALHuVJ/YJwkh6Bp0IES+1vuFVDbZZn6hEK8=,tag:qhpPMBRi+W05OR/qnmMKwg==,type:str]
  BACKEND_MAIL_AUTH_USER: ENC[AES256_GCM,data:k4kg9nGhCbVTCxDoOnt5Iu8AairmXg==,iv:VT3NlsUS4CLT7udTUnGqL0tEBkZwff/9P/oWLQGUhUU=,tag:TvbUfs6tOUuvvYSoiUvJEg==,type:str]
  BACKEND_MAIL_AUTH_PASS: ENC[AES256_GCM,data:sx7AW1K7SBT4Qg3221fB6A==,iv:je2mhubcdfARvDFo9Z/SHjfUvKxBbQEWq15IfHDWmlk=,tag:S3TJrUb3yT7klUE1JN07Jw==,type:str]
  BACKEND_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:zF69T1wEa029edVmr3Gen3RuJm8f298A8AYQ9MJnJTA=,iv:6/9r/Or7r0205RD2TcWZGAaXkFx7UH//jgemAEhjXaQ=,tag:AHOB6ygYqMhQn4GQH1vXfA==,type:str]
  SANDBOX_JWT_SECRET: ENC[AES256_GCM,data:R6TBUr8lPSJMsHKRpQuHUHQ4gf9vwfCyTBD9visE101+fGcbaDmd8mjS2FnHcXVWdab92twxowLJPsY2D+jo+g==,iv:QShfHgYFe4LhHOcc6/YbrXtKopuZtC8WjP7J6EWGqCc=,tag:ilISFQSJmFLEAUyzt0VuVg==,type:str]
  BACKEND_MAIL_ENCRYPTION_KEY: ENC[AES256_GCM,data:qRBYlsxa8IilbeXvdw4GYA==,iv:RN0sRVM2AMGQibqm+gC+vBUzn8lya7mfG7VLsOE/4bU=,tag:KaeLYvAwofukaemQOvWgfw==,type:str]
  BACKEND_MAIL_ENCRYPTION_IV: ENC[AES256_GCM,data:TMsDpQKDD78BEa+QUZtKtg==,iv:1SQ2yRQ7D0en/w+arD0nbCI1wmGe9dYbD1mvkjLekTw=,tag:SeC/rV7kevW+29ad5bGKpA==,type:str]
  BACKEND_ACCESS_TOKEN_ENCRYPTION_KEY: ENC[AES256_GCM,data:44glPaFlGQrzNvy9sCbo4A==,iv:WunRhhD8qsKS2XjZZeQzMav8qj24Leex6Yc2c/iXX9M=,tag:vuMZfHx/W+SjSlaFKoEwyw==,type:str]
  BACKEND_ACCESS_TOKEN_ENCRYPTION_IV: ENC[AES256_GCM,data:YVPBKV8/au5ACexEZYAPiA==,iv:iq+WuTSoqvumIBHBU882Vsok/v882p9FVFs4QKq7IiI=,tag:vXdJ1FHQgRUXGLegzVS1Xw==,type:str]
  BACKEND_DATA_DB_URL_ENCRYPTION_KEY: ENC[AES256_GCM,data:rM+mxvjBIFvutDzurbQXTw==,iv:jmfphC/SmXBjdI8QgaKUkYU8DK8KUXbTdPySEb7WZ2k=,tag:Fw8/+OwodMejPmcBLuiH3g==,type:str]
  BACKEND_DATA_DB_URL_ENCRYPTION_IV: ENC[AES256_GCM,data:pdFFr7M5eDvOx3D/YMkm,iv:AoUGhj7bj8GHJHX1nmhp7IgQRPD1S6etqNKVN3vILts=,tag:hPIUNL80tki5cuCLZ1CbQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT1RqN0FVRWRoR2wycUVz
        RDJXSHQyQTROZEhMa2doNERjay96aTNBQmhJClgwa1ZqOUpBYlB2YXZzdGRGREZS
        RGViekpuaDlsMUQwN2RJU0E3eXZ4bkEKLS0tIHIxY1Znc1M4eE1JM0RjNE5FMnY2
        TDFWQjR0WXNTemxxeHROdUN5bGdZeW8KNWiOQnUhxYEj2/abZ7r417PrKm5hbP1J
        AQZwR6s4xrZe7yBcC9+0wj7fG+S9xMzphIUXl2LZgTGhIuBmDVl/8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-17T20:26:28Z"
  mac: ENC[AES256_GCM,data:8Ee0rGiNAlCcktR7QEqQxve5s7t8ELobFTtgKlzvvdrDJzDh1aCT3Pi57tE8f38/PgcLg5pqkkFUUGXZz3L1+Xb3nGt91XcrNSV0+4l2sdJZOmvZmdWeep9zldUvuRD95UGdAIB2KphHqZ9tUbsv5kiYekxZoziXNljLcTQBYws=,iv:Jab/RNGiIbnbsi73w/oOHXwe0Dt2wLGqYA89uXiVI5A=,tag:ALouYKWZcE7Gau81fgaotg==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: valkey-secrets
  namespace: teable
type: Opaque
stringData:
  VALKEY_EXTRA_FLAGS: ENC[AES256_GCM,data:IooUPghcNGurlkxk5tQ+lW7z+1oMX5w=,iv:JkA9yjiaUtCpWbsAtcJMyN3A3fXxBebUh8jduu2zNk0=,tag:pTHB1VWJdyvVjDTaLqgfGA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT1RqN0FVRWRoR2wycUVz
        RDJXSHQyQTROZEhMa2doNERjay96aTNBQmhJClgwa1ZqOUpBYlB2YXZzdGRGREZS
        RGViekpuaDlsMUQwN2RJU0E3eXZ4bkEKLS0tIHIxY1Znc1M4eE1JM0RjNE5FMnY2
        TDFWQjR0WXNTemxxeHROdUN5bGdZeW8KNWiOQnUhxYEj2/abZ7r417PrKm5hbP1J
        AQZwR6s4xrZe7yBcC9+0wj7fG+S9xMzphIUXl2LZgTGhIuBmDVl/8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-17T20:26:28Z"
  mac: ENC[AES256_GCM,data:8Ee0rGiNAlCcktR7QEqQxve5s7t8ELobFTtgKlzvvdrDJzDh1aCT3Pi57tE8f38/PgcLg5pqkkFUUGXZz3L1+Xb3nGt91XcrNSV0+4l2sdJZOmvZmdWeep9zldUvuRD95UGdAIB2KphHqZ9tUbsv5kiYekxZoziXNljLcTQBYws=,iv:Jab/RNGiIbnbsi73w/oOHXwe0Dt2wLGqYA89uXiVI5A=,tag:ALouYKWZcE7Gau81fgaotg==,type:str]
  version: 3.13.3
