apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
  namespace: gitea
type: Opaque
stringData:
  GITEA__server__LFS_JWT_SECRET: ENC[AES256_GCM,data:8rbX4sv2ETZ9M4wyhgX4HO9u7YSucRNmLmKlioAfKCQkiueo1JgUb22VXA==,iv:+ykDDWBtvKl3AiUWGuRbkVuqzLlZ3w047ev99dhFtFE=,tag:8FwtkjFbst+MdKJrFG6vrA==,type:str]
  GITEA__mailer__USER: ENC[AES256_GCM,data:neWBAZgenFyI3TVe7+VxhQx0InRDCA==,iv:hBRLUyl1JEKIj+wAi15P45JW5DSNRld9f69sEdHX2FU=,tag:4YagwF5coQDUpWD0Kl/JMg==,type:str]
  GITEA__mailer__PASSWD: ENC[AES256_GCM,data:4YcafYJ1Ns0YORNfyDMK0w==,iv:JKMkE+YFWuGFyvkOoQ3BmDL+6JCKr1u9BF9VtqFOGEg=,tag:8S7lxF3QSjAvlkhex522Cw==,type:str]
  GITEA__storage__MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FLFA7Zc4LtyYXVK6pXwyw2757sm4VlAaOWWNQOpr7z87ds4FrdKeYXZ4pVle06OHETXpdrj0IlJfv/Vj1v1EA9Clva8LXkSruUu3,iv:yvYLTsU/KN8mPu/NdwKJoyRVBz6TPSrs1m9P927XX5M=,tag:Nlm/ue+U4u+bYalP2mD85Q==,type:str]
  GITEA__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:1kHG6pnD9pbEXbK18ymtbomQDeg3s0pcNH2wrLxaPIG/YCm1mpxrrZVWBVfRE4cmYfIHrFgMCc0p1lyEGf+Oh5by7W7YUkucWVq22lxhgyzrxyX3xdSwTUxmDrU8IhKfdQKv3BhrVcT0,iv:/vu+7/BvEg818NvwC6whnRPaj+XvFMZQlv9fbnmkZnU=,tag:AeBZYM3btEBwMG6R3ZY0bQ==,type:str]
  GITEA__security__SECRET_KEY: ENC[AES256_GCM,data:gfJngqmxzJattJIBOBYFWzReDo9fhU8nmsBeX4Yo6zCBGBW+HF9sm7mYkWMwEfuLsZUCujbBnMbt1Tdp8Et0bw==,iv:LWGYPHirMy743bfB1wRpCXrq/vyExVlc2VhsLncfOvQ=,tag:KNA0H5hMmbx3IRf8vkJy5g==,type:str]
  GITEA__oauth2__JWT_SECRET: ENC[AES256_GCM,data:z18vznj4UBieU4Lmr59N3R7xoyN2GguXl9GVTWnCOa0ythVtn8FDz08Tfg==,iv:UPySsUjyGwiFQo1UrwpSi4g3XHoUW5aBYZG9j66ruHY=,tag:iVHUWX46EmzCndwJDerY4Q==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTUhqMkozb29ZVjc0bk50
        dE4xcmpxSTFYMHMwVzJvVEtGalBBUUovMm5jCm5uQnBuYU9uQTE3TmVBNEVCdk1C
        dU5GcTU1TTV2a3RpT0tHT2dmRXVoTUUKLS0tIE91aDYxR0NUc1c4Z1lGd0VZV0dB
        SkNNaUpEREhyTVd2VzUxU2svTmdJNDQKTq0Aph0nuWIH7uJbtZ4+3bPxTDn4rMm1
        zsJiIIyRzuEsIKShirKPFELKnN2GTlOOsCexd3m8wbQut/WyGWJjSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T23:09:10Z"
  mac: ENC[AES256_GCM,data:kWIN74hKXAoR+ZS5PgOGkIm90vclYaA2W30l05s3KlVGA+StXKc7LOJJu+x7tJKrg4VMKEGcjLtVC1/CTO1ISrXB3WBdzTVEBZ3vinttiZ0LDmtUdxAhqGlpHPFkemO3S0ipAMlykImPeCWZYv6PwQKWcTE5IRBUBpA+kYEpoqs=,iv:qCKHscxBWYeamHHRZllz/XEdi4+QugD2X7kVkTLlhXU=,tag:RbPTq8e4luneXbp4NA6DrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea
  namespace: anubis
type: Opaque
stringData:
  ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:6rHyFFkInndNh3zthS0kzANZRV6OaIzRHdc/hjE7fuwM27WYb5dkIlvN5wOt97kxRQnUyVT3IV7bKeKlxj/zrw==,iv:OC/RhvHNz30TKB/daaEV1wti5JfYsVSYcJfogMTzci0=,tag:XM22fuNoqSB6HKseojXAXA==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTUhqMkozb29ZVjc0bk50
        dE4xcmpxSTFYMHMwVzJvVEtGalBBUUovMm5jCm5uQnBuYU9uQTE3TmVBNEVCdk1C
        dU5GcTU1TTV2a3RpT0tHT2dmRXVoTUUKLS0tIE91aDYxR0NUc1c4Z1lGd0VZV0dB
        SkNNaUpEREhyTVd2VzUxU2svTmdJNDQKTq0Aph0nuWIH7uJbtZ4+3bPxTDn4rMm1
        zsJiIIyRzuEsIKShirKPFELKnN2GTlOOsCexd3m8wbQut/WyGWJjSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T23:09:10Z"
  mac: ENC[AES256_GCM,data:kWIN74hKXAoR+ZS5PgOGkIm90vclYaA2W30l05s3KlVGA+StXKc7LOJJu+x7tJKrg4VMKEGcjLtVC1/CTO1ISrXB3WBdzTVEBZ3vinttiZ0LDmtUdxAhqGlpHPFkemO3S0ipAMlykImPeCWZYv6PwQKWcTE5IRBUBpA+kYEpoqs=,iv:qCKHscxBWYeamHHRZllz/XEdi4+QugD2X7kVkTLlhXU=,tag:RbPTq8e4luneXbp4NA6DrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
