---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privatebin-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
