apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-models-cache
  namespace: immich-dacostafaro
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media
  namespace: immich-dacostafaro
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName: nfs-csi
