apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless
    spec:
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-pvc
        - name: run
          emptyDir:
            sizeLimit: 500Mi
            medium: Memory
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.13
          envFrom:
            - configMapRef:
                name: paperless-configmap
            - secretRef:
                name: paperless-secrets
          env:
            - name: S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES
              value: "1"
            - name: S6_READ_ONLY_ROOT
              value: "1"
            - name: PAPERLESS_DBHOST
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: host
            - name: PAPERLESS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: user
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: PAPERLESS_DBNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: dbname
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: paperless-data
              mountPath: "/usr/src/paperless/data"
              subPath: "data"
            - name: paperless-data
              mountPath: "/usr/src/paperless/media"
              subPath: "media"
            - name: paperless-data
              mountPath: "/usr/src/paperless/export"
              subPath: "export"
            - name: paperless-data
              mountPath: "/usr/src/paperless/consume"
              subPath: "consume"
            - name: run
              mountPath: /run
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 90
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1024Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless-valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless-valkey
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless-valkey
    spec:
      volumes:
        - name: valkey-data
          persistentVolumeClaim:
            claimName: paperless-valkey-pvc
      containers:
        - image: valkey/valkey:9.0.3-alpine
          name: valkey
          ports:
            - containerPort: 6379
              protocol: TCP
              name: valkey
          volumeMounts:
            - name: valkey-data
              mountPath: "/data"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless-gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless-gotenberg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless-gotenberg
    spec:
      containers:
        - image: docker.io/gotenberg/gotenberg:8.28
          name: gotenberg
          command:
            [
              "gotenberg",
              "--chromium-disable-javascript=true",
              "--chromium-allow-list=file:///tmp/.*",
            ]
          ports:
            - containerPort: 3000
              name: gotenberg
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless-tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless-tika
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless-tika
    spec:
      containers:
        - image: docker.io/apache/tika:latest
          name: tika
          ports:
            - containerPort: 9998
              name: tika
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
