apiVersion: v1
kind: Secret
metadata:
  name: paperless-secrets
  namespace: paperless
type: Opaque
stringData:
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:+sp41NRPHmmd0ojskNZLY4U0NZSOk6tgSUchVzrwVv1GLAQr88HU1V1XukBIpoUZEHpHV+01XFZLZSrJNfta5w==,iv:B/aIZ1aOhpo3FRqJUTVNZFFjy9XiT31HaTSWGtqg6ko=,tag:9CiTX7JB4eT4NlrI1uW0nw==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4azcvUGRwTDlWNXgveWpL
        ZmpwS0hQZ0ZDeTJEenRnQ3Z6TkhLcnQ3blRRCkttYWNzckVNVWpLUjFOTWM2Q1hG
        YWIrSTFkTUJJeFRjd2gzYjZaQWpOaWMKLS0tIDY3dmVHNkJNaGY5WEhSU3ZqNi8v
        L0xLWUlocmt4NkRaSW1XWlBkT0xrMUUK1F1YWyUEAJEjKyIWWyBHfdAW21zm4/5c
        WgPzyucYXlnnH50OTFKFK802oBigwvbws6yWKdiJ7NZqFaBqKJ/Zzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T23:09:10Z"
  mac: ENC[AES256_GCM,data:VRDWwU4bChj/1xnq3iLPePbQFDlpNQGvLXPPZS+zsKv2OaSVU+b0+5i3FJXRH84dkf7x7wGuV1732ZkMbHHc91lubGN1IrVBuC8MST09ERjOg3X/2lhaHCR5XE8O5KWxG/jReBUn2nwlrIvPIVx8nvNpi9Nbqj3To/ubswBZPO0=,iv:WhYm+htcGLmos1g90MJqIlmIlVcKOAn61m7A2AwEA40=,tag:pvEae58UkrCLpfpQCh8plQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
