apiVersion: apps/v1
kind: Deployment
metadata:
  name: atuin
  namespace: atuin
  labels:
    app.kubernetes.io/name: atuin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: atuin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: atuin
    spec:
      volumes:
        - name: atuin-config
          persistentVolumeClaim:
            claimName: atuin-config-pvc
      containers:
        - name: atuin
          image: ghcr.io/atuinsh/atuin:latest
          args:
            - start
          envFrom:
            - configMapRef:
                name: atuin-configmap
          env:
            - name: ATUIN_DB_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
          ports:
            - containerPort: 8888
              name: http
          volumeMounts:
            - name: atuin-config
              mountPath: "/config"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 90
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 2
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
