apiVersion: v1
kind: Secret
metadata:
  name: atuin-secrets
  namespace: atuin
type: Opaque
stringData:
  ATUIN_HOST: ENC[AES256_GCM,data:xBKvnjAyqArI,iv:nM+NwkKvZzcraZ4eZ1pkChJieML0kLbEfy9QS5/TO20=,tag:3d83Ztk9xy0eDG2aJyqD0A==,type:str]
  ATUIN_PORT: ENC[AES256_GCM,data:HlGgdQ==,iv:Gzg0/EkPOG49sGE8xJYb1jVReLMZnz7bnThFKPtZ5yE=,tag:sLUmNAyEBassu5mtArOH0w==,type:str]
  ATUIN_OPEN_REGISTRATION: ENC[AES256_GCM,data:3NiJTw==,iv:WGOOsRdXrF7KBHqBAOniKRzlDQCA0SPBEY0ZXhSIUZQ=,tag:8vclupfV3q4jilFVqR0q3Q==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Sk9BVG9USjArUUFiVk1Q
        RjVtQjdRWWwrUGczUkRpTDZjWXhjS2szV0M4CnFwV3NxWXRCNmY3R2J2bGg0S1BR
        ZUJCUTNnOWJYL3d6YzNRZHZpbjQ3aEkKLS0tIDY1REs5Q0ltaGNubW51SFpYU2tY
        bGU4eVBVVU04dzFJTFZRMnNvc29uQlkKvqosx7B228HBDWNUAfejlnHqx07tGuGB
        vw9LCbLOXC0M2+uwvIl9dY+i91Pop7gAp6TkyG/rSZPmX0T8DyMCrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T04:53:13Z"
  mac: ENC[AES256_GCM,data:xYG1URQdYWpWhBpOeuSWbpFulfLTbLBtRUdayp/A9yIy59NTpoOGwuTf9c+uQIet2uGBPe4/ceQRan70uomdfgF2kIsvT3OQada1HDAm2zWmwiT7SAE60iXLga9HWzWssycFihAbXFO8dAUUf5gCBLDCBwxmiM+G08jJkoMjqPM=,iv:TfqkQvipTGEs4zmAVQpSYIOQ5fgsc/mP0z8WdTYqLV8=,tag:YFxiKFJRjvyEx7oO3N1WeQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
