apiVersion: v1
kind: Service
metadata:
  name: atuin
  namespace: atuin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: atuin
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
