apiVersion: v1
kind: Service
metadata:
  name: multiscrobbler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: multi-scrobbler
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
