auth_allow_cleartext = no
auth_mechanisms = plain login

userdb passwd-file {
	passwd_file_path = /var/mail/passwd

	fields {
    		uid:default = vmail
		gid:default = vmail
		home:default = /var/mail/vhosts/%{user | domain}/%{user | username}
	}
}

passdb passwd-file {
	default_password_scheme = argon2id
	passwd_file_path = /var/mail/passwd
}
