mail_driver = maildir
mail_home = /var/mail/vhosts/%{user | domain}/%{user | username}
mail_path = /var/mail/vhosts/%{user | domain}/%{user | username}

namespace inbox {
    inbox = yes
}

mail_privileged_group = mail
mail_plugins =
