mail_driver = maildir
mail_home = /var/mail/vhosts/%{user | domain}/%{user | username}
mail_path = /var/mail/vhosts/%{user | domain}/%{user | username}

namespace inbox {
    inbox = yes

    mailbox Trash {
        auto = subscribe
        special_use = \Trash
    }

    mailbox Drafts {
        auto = subscribe
        special_use = \Drafts
    }

    mailbox Sent {
    	auto = subscribe
	special_use = \Sent
    }

    mailbox Spam {
    	auto = subscribe
	special_use = \Junk
    }
}

mail_privileged_group = mail
mail_plugins =
