apiVersion: v1
kind: Service
metadata:
  name: rallly
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rallly
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
