apiVersion: v1
kind: Secret
metadata:
    name: anubis-kakigoori-key
type: Opaque
data:
    ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:Veg5nRqcF9jgQ4WG90dmU98uyE1IaF0QJ3HUeCcPukuCpZ2r54R2KhQxe8WSBRrqLp7fPdkKlkCBk4su9AZknHm5vNV6WgB60Q8ejbLFL9Phtqig3aVgMg==,iv:bjmvPSbvWCQ7zV0nUxygex/OrjkSrHaE1CeHGWPRiYU=,tag:Di84/J5kYjg9YV3EcoRiTw==,type:str]
stringData:
    THOTH_URL: ENC[AES256_GCM,data:p/kpiLtUZffWX9g++ESxzZobiGKv2avwuu3yz2NMrhFAsqB5,iv:2Xmn8fdLwaURdwo4KSGrnmzmT+b3VnNgTBs/2dgjtS4=,tag:8C85BqzTRCsp1kPFwKxXPQ==,type:str]
    THOTH_TOKEN: ENC[AES256_GCM,data:7d78KxoPdavbDlMNN/EVN+ISm2/cwDiN+xu5kzFCUH5eti6FJe+BicB70lAXUIN1hIVkKGfhTex4yvjMohejBydNP6LhjIeW0TKrEQT1nUpYQmVkMvrCUgUi5Ons+MZVrueEyEJ7afQp+sOpVmngdkcOQ82NlWoUibLpNs/Y5p8AQG3pxWOk8IHZmyRFD5G+xd32yMQ2wccFtjakZVXWQVmKhzm8BE3EujwmovOj4FeNkbqHzCHQ5T3pQpp8pFGtNhBDyrR6/5xLWnb3+iePIP16/E7ZdKGFyzdbllmxGaBGzYIygbvNqUv8VAWUo8J6OA2u1qo+Y0mcoeMhTN4SDMT7jY/3FRYqYAVtjgUXkMzaUXCpH5KMN3DtpaDuncUmyIayHaJngu4aylJ05mEcBDzZnrqSgHyOlUk=,iv:vhKsHQJQfaj/oZbZ13h0mwHEftdp7+x1RGYdFBYzAOA=,tag:My/03gEMwRH9D4Hx8WE9Lg==,type:str]
sops:
    age:
        - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbG02cUxSRXVXT0xPeW9l
            K21jaEtiYXFrRm5TM2l0bWwxY3h6bEM2b2c0CkpOZmcySTJlSjlxMlhFUCtJajZL
            b1RSdXdjVkc4elQva0pldTA2VTJwL3MKLS0tIHJlaFdtem00Tm5NLzBPSnFWTmV0
            eUU0NCtUT3k1amhyU1lxM2lvUlRtYW8KG4R1xUDRQz7XT7Mz5GXETPT2JqPtYb5c
            YGrtsvjNczppLK61dTjhf2yvRzZBFFd79BgAZXJ/tQ9nVUSly+RDvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T05:47:40Z"
    mac: ENC[AES256_GCM,data:txE6OL2HL6Q3FzmXUAqV9EigK8jIhG8jZqIZ4P62VpT/1ElCAxvKMufAGzezWG67wBA4NTSkFaLMJaqUS082MEOXeJywjbGwvbKzxJ2tBWs/8INVLKKU4WTMd+kcEUFwpmmvCYX5a8XddxezHALYKPb63UPQ3mnMaPAAD1MOfhE=,iv:vqKIhuqtRC3Iyr1HakrHZXquLr/9G4IVitQAqUxddfw=,tag:OBjKc/+02f4IE/p+5QcgbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
