apiVersion: v1
kind: Secret
metadata:
    name: hcloud
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:ePvAuezoGsHZrWcuxHg5bEvSDJ6PDRfRm+PUizt+Hqnei0S4Womx5zmAWDoIOl2LBH1ZpTspufKypunsHP0L1g==,iv:DAnJQe1TBXo293A1Kandb6Ak5dtKNtpR7+MijuZteHM=,tag:1pE7TbC+ERI3Zc4r2I/TwQ==,type:str]
sops:
    age:
        - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhK1dWM2g1VER1RElXVWxi
            VHQ4enJ0REFWMVQ0c2ZFeGY2eVRlS1NPc25NCnZmbG02WThSL2I3b3ljK203QUhL
            TTZlVWdZdG04eHhnZzNEa1ErS2NYS1EKLS0tIE8wcXY5REIvWUh3YngyTFlDY1Z2
            bmFVUUdJSzRXQWR1cXc3aHhDdWdOalkKTzAI3TPy0rxUEgSMRlzav3IBTjuDPDfT
            aK6LOND16iX3ttulhLKV7kzkGU1337ONqgm6EKrPgir7V815EoYMrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T05:47:40Z"
    mac: ENC[AES256_GCM,data:2oORjjjEIF2WDQLUSQN37elj/klHihxLiwOde0hxrYT0Okc3+WbNQSqmL6CEeIIpxHEhNTXI0G6zI/7JV9JyzOTEOZ1oCusEuM13CUuO4kwR83zOI2tHW2SRGQZgyi+XOCnkCPpV3YHr2pMdgBI93U28hUUUuM0TS5+a2i/cDx0=,iv:pLEAs3mo9mT5YgZAwez/T+afZTkdA3l/iVsso2mvsXg=,tag:0CodIUnnTkO0C4x2IvqeDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
