apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: immich
spec:
  instances: 3

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 18

  storage:
    storageClass: nfs-csi
    size: 15Gi

  postgresql:
    shared_preload_libraries:
      - vchord
      - vector
    extensions:
      - name: vchord
        image:
          reference: tensorchord/vchord-scratch:pg18-v0.5.3
        extension_control_path:
          - /usr/share/postgresql/18
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-db
  namespace: immich
spec:
  name: app
  owner: app
  cluster:
    name: postgres
  extensions:
    - name: vchord
    - name: vector
    - name: earthdistance
    - name: cube
    - name: unaccent
    - name: uuid-ossp
    - name: pg_trgm
