apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-models-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: pv-immich-media
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
    - nolock
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 100.126.243.21/mnt/yuyuko/media/media/images##
    volumeAttributes:
      server: 100.126.243.21
      share: mnt//yuyuko/media/media/images
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: pv-immich-media
  storageClassName: nfs-csi
