apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketid-pvc
  namespace: pocketid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
