apiVersion: v1
kind: Secret
metadata:
  name: kakigoori
  namespace: anubis
type: Opaque
data:
  ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:3m9tMNJ4FqyK2r1E6MH3aJ7KQZ9lyz7Ktp5IMAIa1PFAvhJnK4HHuN3DlyWOzmKF/snnJdYokruhqr+N4Umx0D7BA6jmBUWxPnUJ6s30EkIhTVGwcS5Qww==,iv:QU9UrC3Io00famnz6M1OOPXmqE6ybCypTkEu5OPtdbY=,tag:f3t6t7Okl9Xn7CcOTiesYA==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eWNkZ3E1OWhISHVIZmFS
        OUdhU2NiSkNMZWg5dGttOHVYVXBseXRZVzNFCnVYL0s5RUVQRFpVSVdaTVRTd0lx
        WGFxdnpvUnVYS1JIY0JLTk1hQ3U4dzgKLS0tIFFBUHBBNERTQy8vb1FrVVd4RVhW
        MGx6N2MyZEsyNEI5ZHQ4Zm9BWkZ4c00KESH5F2j0c3NdsMNj7bQItT/O5I1anDTb
        h0T3CQrE5cbmXSZX0V/u5IE6Vry/yXS78xn7ppsdG9gqnlWr9bGY4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T14:10:43Z"
  mac: ENC[AES256_GCM,data:lv4dAVo8GtUCy41oeXzYSIYdotyBCg9IN66Uh5jXjtFbDcmdjyizG6OoctO0S8wLhQNrjM6Sk2sR8NnYm9MgAo73Zm4/02j2DD1pEWUjNb168gb/E7sEcv/HifoS1CclzEBfulFXucKiZpiGxYgJmqcfDGpz8rJm1BT2iCDQP1s=,iv:kdjtOyYp1biVDCxfps4PSTf97muI/f4g+eF+xkKM0cw=,tag:wv6aGRQhbmip5I6TNOUaDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: kakigoori-config
  namespace: kakigoori
type: Opaque
stringData:
  DEBUG: ENC[AES256_GCM,data:GE8HnUY=,iv:SOlxtJ/F5N2qdRA/ax8CBK92Au1sqLoSl1SNYeyAnQo=,tag:IQHJ5gRduPf7+zbNquFTHg==,type:str]
  KAKIGOORI_SECRET_KEY: ENC[AES256_GCM,data:/aX28Xf2jPM8D4gXO0BNYbOgb9j3rryRV/AVOgDUpUu3pGlRxEWLLD8D7t4mqpDi4Qc/rm+1tslp8JYeg/yugfxb,iv:WxoIInF6izI42b0GUj+mEfIoBBPNywEXeJsORwm1wqo=,tag:Mm+RLCMvVKtejex6tq2euQ==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:+CHyZ2LFYuQGk00q4OMQuH7zeCGq/+Jnq/CpbAzs,iv:Zpg7cBfoVJJ4IJds48Jixacu3mrgMq2900XxUVtVz0U=,tag:ADYZ96Tyw99HQ/BU6yzvng==,type:str]
  S3_KEY_ID: ENC[AES256_GCM,data:mzOa1r0FKZXTbeYKV8F7KKAg7mJ+zyRWf2kY7gNwRun7n0eS4tsimY3O+RUis6NEbPJLaPbG,iv:CSo3IhBW6SczemeebpWmsxw6lfyS+Xcumoaq/BCvQfA=,tag:mB5lxKbl0/D0hHIb4R7+5w==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:U5/yBbFRVzRG3InyyFogplQ/OekquWkMxUA4K1Kl+n8HldscVimEDG+EOTOHPEmclU9aPCxNn8L3XviPb9/BVebgkaIPVSCXUGPi,iv:vI+xF4ilYtumT+qPjFzRXjmqqkbtwIuF0uFYNGoKD3A=,tag:Bp9gz+yGL2FdJeJfwuVG0Q==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:fi6EGayrRRfO,iv:7SzbY9hVT0E9nfqyMSLKzgNNWDsVOskLvHW8/0UF5bI=,tag:Cw7Osw3aeR4mv1fEiFOmqQ==,type:str]
  S3_PUBLIC_BASE_PATH: ENC[AES256_GCM,data:WXxqBzfmQKV+58vg+pKFV63sZw8q1LKbderE4g==,iv:DZVDrfCrHJbFq4IToDbLMpAGTIwsvVHAiKa78TGYLo4=,tag:fjSi1+7lYM4poTeK/xsELA==,type:str]
  ALLOWED_HOSTS: ENC[AES256_GCM,data:ZKkUKd1m9Ux3qz+xHkSAUSBM5z/ywNHjnkS2drMJbA==,iv:n8KIMYHkhOSSPtrXqpKHWNQzqrzbZadR3wydPOq3A9Y=,tag:lVukpCRsS98tQdZlAXYeew==,type:str]
  RABBITMQ_HOST: ENC[AES256_GCM,data:TeXw12zO9sM3DF+Mn+UiTTzwZk6bHqU7tL7SD6SebCQtsPirvG4haWtUMDHEEKgZFQ==,iv:1P1WPQEhGj4GyHu9JuiYVwnUuiqPNssZVlaHsq/cCD8=,tag:pdWEETNDLH6o88jlElOqNw==,type:str]
  RABBITMQ_PORT: ENC[AES256_GCM,data:MkQayQ==,iv:pWye+NLqiBOQPlEONGjupt1C/3JbzORVUhYmMo+XFsg=,tag:XAG1kZMzr7ZeaZeC1MCNvw==,type:str]
  RABBITMQ_ADDRESS: ENC[AES256_GCM,data:fLJ9JjAEZUM5DriOLn5A02KCDmA/Qge/ChFtCm2aPdEzzlGVWeiRkvl8PkDTSr5eRInhZ99U16CrSdqC7BNjU/c=,iv:/3QLLymEKE3gIwsBYKTW7Pnzr2m1RxtEY1Giesikvio=,tag:PE6Fn1tf4+Cf0ym+cHaObw==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:GwOwInP7INRJprgUGiH6d3atPPmQvd9TzX8hLImH8z3DLt64gKavl8zWv14MAgkbVdebHg==,iv:KKd773mGh/1L5OKZgEOWLvwyi7qS5VOWFHlUlj5qpug=,tag:f/0Wz17hunATxeUwxIcr6Q==,type:str]
  SENTRY_DSN: ENC[AES256_GCM,data:Faxm9WoNr/LG5ziq1gKhmY3lcsnX9kRf20rkuAsoE0TUUnoPhZd3S1mPFDS7F1IdpU4V52REujPfr53xjF/QkOlm2ZHIo7/uDLGcHHyKhI1ixw2eRg==,iv:wPbZ/P07IUpVsT0SH2Zl6JPQ2HFQPmfX0lT5mhMBaWk=,tag:owPcy9toqk6vkPc69WAHtA==,type:str]
  DB_RECOVERY: ENC[AES256_GCM,data:FHtYsa+FhXPSDv8AKC4ilinoKvw=,iv:Bp28fJURcCBDF0NUtpEFbaCO5ogU3INDQSosw5Dun4E=,tag:iGSNyRqb7Spj6/p79phF/g==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eWNkZ3E1OWhISHVIZmFS
        OUdhU2NiSkNMZWg5dGttOHVYVXBseXRZVzNFCnVYL0s5RUVQRFpVSVdaTVRTd0lx
        WGFxdnpvUnVYS1JIY0JLTk1hQ3U4dzgKLS0tIFFBUHBBNERTQy8vb1FrVVd4RVhW
        MGx6N2MyZEsyNEI5ZHQ4Zm9BWkZ4c00KESH5F2j0c3NdsMNj7bQItT/O5I1anDTb
        h0T3CQrE5cbmXSZX0V/u5IE6Vry/yXS78xn7ppsdG9gqnlWr9bGY4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T14:10:43Z"
  mac: ENC[AES256_GCM,data:lv4dAVo8GtUCy41oeXzYSIYdotyBCg9IN66Uh5jXjtFbDcmdjyizG6OoctO0S8wLhQNrjM6Sk2sR8NnYm9MgAo73Zm4/02j2DD1pEWUjNb168gb/E7sEcv/HifoS1CclzEBfulFXucKiZpiGxYgJmqcfDGpz8rJm1BT2iCDQP1s=,iv:kdjtOyYp1biVDCxfps4PSTf97muI/f4g+eF+xkKM0cw=,tag:wv6aGRQhbmip5I6TNOUaDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
