apiVersion: v1
kind: Secret
metadata:
  name: kakigoori
  namespace: anubis
type: Opaque
data:
  ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:j2zGgJ7D4uULWjIVTV9e5XedP4Ue0Wjcg2ULorMqjUjwuiYqJKBFBPbLHV/u8FMk+DLKY/19w/KW+FwmhjsOCuo9YmsvRLSr8lRIJD6FdQaSgI+mBIkO6Q==,iv:O6HlUbP4pdEsHVKVTxxmZq4ZNkqtqnheXRpPwXeYovI=,tag:wfeS3jLiH0PRpQVLd97cOg==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TVJjL252YjFybXIxOHdn
        Wno3M3NpNFIyUzNwWnRVSzFKZnJmN0lPazIwCktPT1d2bndvOFJzZ0Y3cVVFbi9y
        cU41NWs3LzQrb3pUeWNYSFZFZzN2UXcKLS0tIGcwUjZkS0pIUHRabnZ0ZEEraCs4
        Z1RCaTdBRGJySFhmN0JCT0xkN1R3NUUKztaxZTG1bqI2xLfxOZbqmOGQA9b7c0Jv
        BjcJYHvP0x6IwQ6pETuNQ8SdCv291eY9F4EX2+ESNyT6rtED9NfX0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-04T21:16:11Z"
  mac: ENC[AES256_GCM,data:HamftcLXB4tUaVoFwMzxuD19xTDFLAy767HJIucrpIaGJ/PkYRHe5ljqcJ1gmRU3yGpRInlkzjmvbFJuMX8KBra2GbzrAS6RC0JmWVtMljhFdRArQALcUNfmCVoXxU0OkC0CGhQZJgXTx7PxCgbXVF9BVRXNL0q//+iNOC9oYSY=,iv:2TT4qJLfXl9YZx6ynlILMv9p9wON0iOjL1xF25ruz0o=,tag:XiEbUgfzF4SUMdEMmATQTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: kakigoori-config
  namespace: kakigoori
type: Opaque
stringData:
  DEBUG: ENC[AES256_GCM,data:Je0QpxQ=,iv:xCEV3wbN6MsjUv6OtlL4MkTOCmTGfkVNtteoeVqHZdc=,tag:gqXyXHK7UmMuyFoYTyAM/A==,type:str]
  KAKIGOORI_SECRET_KEY: ENC[AES256_GCM,data:blcaWgSsP8CGsd51CisqBXgs+xWThSxtL17xdPBzTp5ApdsDy6txeBNDGToZy8fcAg4NarRue8dx9MIsJ3+AWhnJ,iv:YsSUHX/+7Fzd+6Ii+JhjXsVPoTtg4eD1RgcOmPK8JyM=,tag:2VDOhJpg821F4KeA5tOrsw==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:wlBS5VBp/LKpJhZjrSYuulpRNysLCjRKddcuoZrJ,iv:CHhSa6JXmVKU6z7sRTfHdQUIzYAhXJIugCTGjb3zDYo=,tag:+G73kwo4MjyBOUeOU8UocA==,type:str]
  S3_KEY_ID: ENC[AES256_GCM,data:bt9e0WhBcN0+50OvIpj3jM4F1ruatOmeD6IeG2T3EUlPjBbqrBXfSlWe0jKXR6KBC/CImi6M,iv:TwiYqiRF4BRNs3gcmyVIkInGdx//6r5mG/ulpkUeBq0=,tag:8DAHpNcVJDSXbkXNXMuy4w==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:1Tfwlfi5UDJbhR5kyJCvET5+S2B2VLkeYHxejOOGg4RHYNU7B5m/R3CbuhBRSc7Yj8vVNS9PFKteca6J18TNagTpqu/aksgGEns2,iv:3dx/xZ0x6HTN8A2F6KhGozcoRQxnWpKPoSyN2AuwcF4=,tag:RGDUTr0UnLauq+5e4FdlXg==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:ecipGElDWxy2,iv:qWFHJg/EDLyLbRPR5hTOFggtBZ5xrjq6T+BDmIePi0E=,tag:R5oLsHMJ8N0Dg5Dx7wdoFg==,type:str]
  S3_PUBLIC_BASE_PATH: ENC[AES256_GCM,data:wuJUz66ICsUSLaYlYYRmECC6x7x0yXUEsUbQFA==,iv:rfBBv+/3DduKVmlk81qJg4jUxXzgyyvTGAslJvkr3UE=,tag:6c1s6MGOLAUw5rJF6G3TzA==,type:str]
  ALLOWED_HOSTS: ENC[AES256_GCM,data:nTP5+BNDfmncEmDpfE+Tp4vfwUgptC2wbUY8HRVFgg==,iv:qqGS8/Vtj9rrvOesvGudBEmBsRJnjp//nueCtvD7RcA=,tag:iNU8c44CGICLs4TLLmIYKQ==,type:str]
  RABBITMQ_HOST: ENC[AES256_GCM,data:9hxBFFn9uzYwsLWaMxQ6UM2NpCKf4L8Tldnj8TXKTMavRe9MnKxz3G7DHSGVQh5J5w==,iv:eKTy65IZvr2i+7eIkoZWiepI0xf6sKa9mgpZ43OYO2A=,tag:epA8MIU+9JnStQmSYJrnjg==,type:str]
  RABBITMQ_PORT: ENC[AES256_GCM,data:n0EDVg==,iv:VQR3A2Q5qbOONKQIZL6WQBQbyQgLrdPOTQDek06+Eyk=,tag:m8Xg/khexR8cLHLd/wr6nw==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:Xq+kxx9me+p6FWhb9Q==,iv:FN/Sk1wsgpJH4Dhbm8qk+6WCba6fMCW8z3f9KUbw4IE=,tag:LECr8UI4nYijvUcGMAvViw==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:gRpsRkkrtxkk,iv:mSfb7Fmsfp62Asf6Z8+KKmA5tkwxq03bwIbp2I6de7A=,tag:Qa8FYL2GhPXkZ20AgpYRqA==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:LgETQKNkVSen,iv:q3lYxQ7BnhnRLHAcChalWC5fd8/km0f8ZF1X54v4HD4=,tag:zAff3cDbIGsxjwXAKsHBLQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:MPVj61+f7SrpOY78BGiTw2zMw3zElEC2n3Wcw9o21g==,iv:ZV3l49ly5ItmtXdxP5f1aFpvViHlnuNVU87MNANI4qc=,tag:Ui+iO7rSx7aS7fDm6EpIxg==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:DaGfyg==,iv:TWhnXI5ADBNPM7WHzk9MqHSpF7VALU/jc0fIjMiApZw=,tag:/PKLg65ojlKPe1THjStflQ==,type:str]
  SENTRY_DSN: ENC[AES256_GCM,data:jAZpmxd9n4OCUUZ0vkL6L/9EuZanIqMXAQaNueA6U+oInd5IWrk7Vwke9txtqsuALdAldPseBFvMXl28Do612DF1L02i+Cg7SbZVSz/XQjT0PMkkcQ==,iv:yBWfYfG+VUNxA+zUr2vhkyFiE53JK4MScmD9XzAbqm4=,tag:rGeixqgwIBY1PW/5O6ZYAQ==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TVJjL252YjFybXIxOHdn
        Wno3M3NpNFIyUzNwWnRVSzFKZnJmN0lPazIwCktPT1d2bndvOFJzZ0Y3cVVFbi9y
        cU41NWs3LzQrb3pUeWNYSFZFZzN2UXcKLS0tIGcwUjZkS0pIUHRabnZ0ZEEraCs4
        Z1RCaTdBRGJySFhmN0JCT0xkN1R3NUUKztaxZTG1bqI2xLfxOZbqmOGQA9b7c0Jv
        BjcJYHvP0x6IwQ6pETuNQ8SdCv291eY9F4EX2+ESNyT6rtED9NfX0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-04T21:16:11Z"
  mac: ENC[AES256_GCM,data:HamftcLXB4tUaVoFwMzxuD19xTDFLAy767HJIucrpIaGJ/PkYRHe5ljqcJ1gmRU3yGpRInlkzjmvbFJuMX8KBra2GbzrAS6RC0JmWVtMljhFdRArQALcUNfmCVoXxU0OkC0CGhQZJgXTx7PxCgbXVF9BVRXNL0q//+iNOC9oYSY=,iv:2TT4qJLfXl9YZx6ynlILMv9p9wON0iOjL1xF25ruz0o=,tag:XiEbUgfzF4SUMdEMmATQTw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
