---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotosocial-pvc
  namespace: gotosocial
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: nfs-csi
