apiVersion: v1
kind: Secret
metadata:
  name: gotosocial-secrets
  namespace: gotosocial
type: Opaque
stringData:
  GTS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:EmKjZIo2Tty8Cz1YvS9l5ZEk43xzMG9LauRhR6+4A7M=,iv:BGXUX+ywBoXluA+xJ2cSbSqIQtqI87FBEpvPnY6MJZA=,tag:XAN6D8XuOwI0YFeyoO8Bsg==,type:str]
  GTS_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:pkHs9Xo4me8wq5HaS+/5aYsNQG4=,iv:mJose7cD/2QqI/Ut8HTe/Tj6p9VIc6LVuFdG8GKPXxc=,tag:U3bc0d8885icudf21IQCPQ==,type:str]
  GTS_STORAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:DLTzNCi2rv1fTxWdIFlDXlrPmgYgUH4nmmkx62qJjDzzFnYzkY2rxDU=,iv:6Gt7Nn7+2OOxHPgwkAiDuWXsPo5xatAO4wx7luPikNM=,tag:IucEmEmtgLB4CHS4hN0OBA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTGtSdkZ4RE5tYmNUamMr
        OXF2elBoSUcrcmZXcDdVK1lsc1ZaY3dWakNVCkhrY2hwZTh1UHdZNE1GRTNLTmdr
        cG5CZC9xUUpKd2RFZVlGZXNsVkVUN2cKLS0tIGFLdmpzVFFTV1pXOEowK1VidXFW
        MG80bmVuQTdsdTFKMHViYUE4RkNVU00KoTwBvpAihmecMNj4XurL9QW9kivTUUhU
        oSjjpLNLwKUmVQQc1XMcI1q4JWZiVjce7LMyjFEozFw1VW1ES+gbpQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T21:08:04Z"
  mac: ENC[AES256_GCM,data:a/uaLCyB96jLRVZV95KdsNNfGee/BXSv6G9RgOPSn3hRKeUyShrJlxgZwMLOFdMtMUfVojI/Wxq9lL/Bhot3P/mcxKMCT74a9Jdq22kscxPVvaoIUFJ2isSHxOjnE983uhua3tRVtDQ2S+dWKbyJ6CSdg0231+fAmAZz0W03PFI=,iv:KCVg+ChWLHDq5xXW0OxFkd4GTRH2sANczvxvjyZ8xWc=,tag:tonnBJTZAwN4mNU1uJRPVg==,type:str]
  version: 3.13.1
