apiVersion: v1
kind: Secret
metadata:
  name: gotosocial-secrets
  namespace: gotosocial
type: Opaque
stringData:
  GTS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:5an9ggSSLoSir00Snf7KeclXOf4jky6KHf/ii9fevBY=,iv:tQQSQwrhmm9SAMjVU1eApIy4JXM0uQ4mHs2f8gpFDGA=,tag:dvPGcdXcr01yedU+yPAWWw==,type:str]
sops:
  age:
    - recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK2dCNGNPWGNUZmxwZmJo
        RGhoMzM3aGVtWitIanhLckRsa1ZYdkVIYVNvCnlHaHE0OUtlcHJmWHMyTnF3SGp5
        NjMvWDlud3V3dElISHJxdE1iejVtQ3cKLS0tIFlGN1pjbUJPL0VFRHZMVUFQR2F3
        bTRIb0pOcmladC9WUTRJdlQxVWYvLzgK4zCHWTPFaYgqKlxs57TQrGjxl0O5p/GP
        YddmLXr3qIeaZYS7IhCo+EiSkS5WILU/YOViAEB6rMcLrN/OavBppg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T16:52:32Z"
  mac: ENC[AES256_GCM,data:2AbUBXUwBVfvpX5oJRB2JLq/jzPmOm7MjrRE77izylU5hGoccBNj+TgNTUlSvPdkfXHJugc8fq8y2sdGug0Wc2DSnKexRzduiS9IsC9zwlPogYCiyQi7UG1Gx9jcFKv/4huFYMKrK+UAbmUOqtyeYrPvTdUHGNrQ8kBevJBzU4I=,iv:AKEDyITHS7XCiSnA1V0QSLT6lyasNIRHVm2Jxh+b2bI=,tag:4bIh7SXGL3lZCP/QLSTQCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
