apiVersion: v1
kind: Secret
metadata:
  name: gotosocial-secrets
  namespace: gotosocial
type: Opaque
stringData:
  GTS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:rBNF9jScnR5AtCw2AKJ6O2M7y0s0jEp/MYbrd4qwl5w=,iv:PRMZbUqxGvewq21mVexGd/DGh+1ccRLOnqwf36UvHaU=,tag:1hlso+HAwZz2328rZfjSXw==,type:str]
  GTS_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:EdveJiSmkDvt/JBHyJ+UUG9EgOU=,iv:FKSA35mAnFhGRQ95RBgYx7pjB+J6RkLC60bFHQnpb6E=,tag:LqL53k0t0a0sWvHkIX8sJw==,type:str]
  GTS_STORAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:8x6M90kORHBJKef97wDROEppLGchadwE7rtLpiVO8Wkp4X1qKmkDyhk=,iv:8PcGhPDg5xyLSvWOeSjXh3tmjDe96NuJHDYqtS95+Zw=,tag:hBpKZfVs70PZKfqiI/rgXA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUzFUYjJKNlZpajdsSktM
        MkNVWWIvdW93UzRwdFgvV2loZzhUZEQrUEhjCi9RdW4yNTBWL3dEbzVnK3M0OEky
        c1loa3grdXZ5QnZsL0ZVM2JPc3E4Qk0KLS0tIHU4U25mbWdKR0I4UmRpdlNRd3lV
        aXR0UE1CTXpZMXlmUVZrTm00b0F3VkkK94yrqpoJgePIONIqiPZRBagoTMNVKnjz
        YxrxYkckLWycpxiSpd8WqAGZx0fT0OFSEpT7aN36XSc5KMFpRCOrRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1r0tjhg6uexyj0p7fp0ftv5h7r7e3ptzkk2797pznfvrvsm576u0s37yyaw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T21:23:00Z"
  mac: ENC[AES256_GCM,data:Ot9MGsckn5WH0vv+jOqBnUnqdQxoHY2ZuciPl+06lSsJvAQiph1PWvrIugLzMTsRCfs+bO2BvdHdSCz5jGZDINpML6jXTi/1V9y709nG8HFomTlG72GzJ0mgFD8qoG3bvJGIG1bYowpAvccZw3NHkJYT7kltlH877IfeUDi4GU8=,iv:t6Nu52GVoocMil/LUGjmIkI29PKxsY+2yY95DXN8VM4=,tag:OLeox8xLt5V2+99CGKWhcw==,type:str]
  version: 3.13.1
