apiVersion: v1
kind: Service
metadata:
  name: gotosocial
  namespace: gotosocial
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gotosocial
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
