apiVersion: v1
kind: Service
metadata:
  name: dolibarr
  namespace: dolibarr
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dolibarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
