apiVersion: v1
kind: Service
metadata:
  name: glance
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: glance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http