ssl = required

ssl_server_cert_file = {{ certificates_path }}/certificates/remilia.ch.crt
ssl_server_key_file = {{ certificates_path }}/certificates/remilia.ch.key

{% for domain, _ in domains.items() %}
local_name mail.{{ domain }} {
    ssl_server_cert_file = {{ certificates_path }}/certificates/{{ domain }}.crt
	ssl_server_key_file = {{ certificates_path }}/certificates/{{ domain }}.key
}
{% endfor %}


ssl_client_ca_dir = /etc/ssl/certs
ssl_server_dh_file = /usr/share/dovecot/dh.pem
