(mtls) {
	tls {
		client_auth {
			mode require_and_verify
			trust_pool inline {
				trust_der "MIICdjCCAh2gAwIBAgIUHiHQAvrpRlbJHqK8E3lHTTMWfnMwCgYIKoZIzj0EAwIwgY8xCzAJBgNVBAYTAkNBMQ8wDQYDVQQIDAZRdWViZWMxETAPBgNVBAcMCE1vbnRyZWFsMRgwFgYDVQQKDA9wcmV0dHlzdW5mbG93ZXIxGDAWBgNVBAMMD3ByZXR0eXN1bmZsb3dlcjEoMCYGCSqGSIb3DQEJARYZY2VydHNAcHJldHR5c3VuZmxvd2VyLm1vZTAgFw0yNTA5MTAxNzIwNTVaGA8yMTI1MDgxNzE3MjA1NVowgY8xCzAJBgNVBAYTAkNBMQ8wDQYDVQQIDAZRdWViZWMxETAPBgNVBAcMCE1vbnRyZWFsMRgwFgYDVQQKDA9wcmV0dHlzdW5mbG93ZXIxGDAWBgNVBAMMD3ByZXR0eXN1bmZsb3dlcjEoMCYGCSqGSIb3DQEJARYZY2VydHNAcHJldHR5c3VuZmxvd2VyLm1vZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCI+XWx6xISyCdJ5FLVWBcEWMzojd7lREtoJRDEioHKmwH9KUTZZrLcRTLPnrWfBXd2mOiW4ZyVws3eO2hGoQO6jUzBRMB0GA1UdDgQWBBT33CLQzLPAg3kLE+rATFweBHeG8DAfBgNVHSMEGDAWgBT33CLQzLPAg3kLE+rATFweBHeG8DAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cAMEQCIEaoNbs2Rdti41MrW+LswhvOUlq5Vv1Tc5uNYiFIfXSPAiA13e88WHiIYHgHoAIRWYwgNMu+sQiJoompo5XCXFd4QA=="
			}
		}
	}
}
