photos.dacostafaro.com {
	reverse_proxy immich.immich-dacostafaro.svc.yuiman.prettysunflower.moe
}

nextcloud.dacostafaro.com {
	header {
		Permissions-Policy interest-cohort=()
		Strict-Transport-Security max-age=31536000;
	}

	reverse_proxy nextcloud.nextcloud-dacostafaro.svc.yuiman.prettysunflower.moe
}
