restic.download-ram.zip {
	import porkbun

	tls {
		client_auth {
			mode require_and_verify
			trust_pool inline {
				trust_der "MIIB/DCCAYKgAwIBAgIIDasSkT1BMQUwCgYIKoZIzj0EAwMwIDEeMBwGA1UEAxMVbWluaWNhIHJvb3QgY2EgMGRhYjEyMCAXDTI1MTIxMjE3MTAwOFoYDzIxMjUxMjEyMTcxMDA4WjAgMR4wHAYDVQQDExVtaW5pY2Egcm9vdCBjYSAwZGFiMTIwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAARffjd8s8TkazuvyBcJXxdjW5SHU/abiudJMWE2vutoCKppyQU0VYEf6d9Su4Nzy8MSe0P9iazkBwybTqsDf+Rl1G+PuBiIsbmSnhpDhVcSp6+C9H1v7mvmfAK2I1yjfFmjgYYwgYMwDgYDVR0PAQH/BAQDAgKEMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBQ559+3k54wEENE2CaHqxCjD4BeDDAfBgNVHSMEGDAWgBQ559+3k54wEENE2CaHqxCjD4BeDDAKBggqhkjOPQQDAwNoADBlAjA07KZTE9VcEdJm0DW91ttwiihaUyGPJUoh+F+IH6U1Z0yNAXzYHwCFAmSWI2ZMfDICMQCu8GTP0V4rAVGPFaWq41FxwEuVbQC/KXFULTjrSRgNHL3/t5pQx5EIZuYDARYsxr8="
			}
		}
	}

	respond /metrics 403 {
		close
	}

	reverse_proxy 100.126.243.21:9732
}
