nyallo.net, www.nyallo.net {
	import porkbun
	log

	handle /as402919 {
		redir https://as402919.nyallo.net
	}

	reverse_proxy nyallo-website.default.svc.yuiman.prettysunflower.moe
}

dolibarr.nyallo.net {
	import porkbun
	log

	reverse_proxy dolibarr.dolibarr.svc.yuiman.prettysunflower.moe
}

redmine.nyallo.net {
	import porkbun
	log

	reverse_proxy nyallo.redmine.svc.yuiman.prettysunflower.moe
}

redmine.kikimungo.nyallo.net {
	import porkbun
	log

	reverse_proxy kikimungo.redmine.svc.yuiman.prettysunflower.moe
}

auth.nyallo.net {
	import porkbun
	log

	reverse_proxy server.nyallo-authentik.svc.yuiman.prettysunflower.moe
}

as402919.nyallo.net {
	import porkbun
	log

	rewrite /as402919{uri}
	reverse_proxy nyallo-website.default.svc.yuiman.prettysunflower.moe
}
