nyallo.net, www.nyallo.net {
	import porkbun

	reverse_proxy nyallo-website.default.svc.yuiman.prettysunflower.moe
}

dolibarr.nyallo.net {
	import porkbun

	reverse_proxy dolibarr.dolibarr.svc.yuiman.prettysunflower.moe
}

redmine.nyallo.net {
	import porkbun

	reverse_proxy nyallo.redmine.svc.yuiman.prettysunflower.moe
}

redmine.kikimungo.nyallo.net {
	import porkbun

	reverse_proxy kikimungo.redmine.svc.yuiman.prettysunflower.moe
}
