remilia.ch, www.remilia.ch {
	import bunny
	log

	handle / {
		redir https://prettysunflower.moe
	}

	@infra path_regexp /infra/?$

	handle @infra {
		redir https://git.prettysunflower.moe/prettysunflower/infra
	}

	reverse_proxy 100.106.176.41
}

wiki.remilia.ch {
	import bunny
	log

	reverse_proxy outline.outline.svc.sekibanki.prettysunflower.moe {
		header_up Host "wiki.prettysunflower.moe"
	}
}

papers.remilia.ch {
	import bunny
	log

	handle /share/* {
		reverse_proxy paperless.paperless.svc.sekibanki.prettysunflower.moe
	}

	handle {
		abort
	}
}
