remilia.ch, www.remilia.ch {
	import bunny
	log

	handle / {
		redir https://prettysunflower.moe
	}

	reverse_proxy 100.106.176.41
}

wiki.remilia.ch {
	import bunny
	log

	reverse_proxy outline.outline.svc.sekibanki.prettysunflower.moe {
		header_up Host "wiki.prettysunflower.moe"
	}
}
