apiVersion: v1
kind: Service
metadata:
  name: ourfigurecollection
  namespace: ourfigurecollection
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ourfigurecollection
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: static
  namespace: ourfigurecollection
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ourfigurecollection
  ports:
    - protocol: TCP
      port: 80
      targetPort: static
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: ourfigurecollection
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: valkey
  ports:
    - protocol: TCP
      port: 6379
      targetPort: valkey
      name: valkey
---
apiVersion: v1
kind: Service
metadata:
  name: ourfigurecollection
  namespace: anubis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: anubis-ourfigurecollection
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
