protocol bgp bgpexchange_fra_rs1 from bgpexchange {
  source address 2a0e:8f01:1000:24::270;
  neighbor 2a0e:8f01:1000:24::1;
}

protocol bgp bgpexchange_fra_rs2 from bgpexchange {
  source address 2a0e:8f01:1000:24::270;
  neighbor 2a0e:8f01:1000:24::2;
};
