[working-directory('caddy')]
xcaddy:
    xcaddy build \
        --output caddy-bin \
        --with github.com/caddy-dns/porkbun \
        --with github.com/caddy-dns/bunny \
        --with github.com/mholt/caddy-l4

fmt:
    #!/usr/bin/env sh
    for f in caddy/sites/*.conf; do
    	caddy fmt --overwrite "$f"
    done

template $listen: fmt
    gomplate

[working-directory('caddy')]
adapt $listen: (template listen)
    ./caddy-bin adapt --config ./Caddyfile --adapter caddyfile

update_internal:
    caddy_json=$(just adapt "tailscale") && curl \
        -X POST \
        -H "Content-Type: application/json" \
        --data "$caddy_json" \
        http://internal.okina.hosts.prettysunflower.moe:2019/load

update_public:
    caddy_json=$(just adapt "public") && curl \
        -X POST \
        -H "Content-Type: application/json" \
        --data "$caddy_json" \
        http://fsn.okina.hosts.prettysunflower.moe:2019/load


deploy: update_internal update_public
