---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
    - image: busybox
      name: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: data
          mountPath: "/data"
        # - name: olddata
        #   mountPath: "/olddata"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: znc-pvc
    # - name: olddata
    #   persistentVolumeClaim:
    #     claimName: gitea-pvc
