define BOGON_PREFIXES = [
  ::/8+,                         # RFC 4291 IPv4-compatible, loopback, et al
  0100::/64+,                    # RFC 6666 Discard-Only
  2001:2::/48+,                  # RFC 5180 BMWG
  2001:10::/28+,                 # RFC 4843 ORCHID
  2001:db8::/32+,                # RFC 3849 documentation
  3fff::/20+,                    # RFC 9637 documentation
  2002::/16+,                    # RFC 7526 6to4 anycast relay
  3ffe::/16+,                    # RFC 3701 old 6bone
  5f00::/16+,                    # RFC 9602 SRv6
  fc00::/7+,                     # RFC 4193 unique local unicast
  fe80::/10+,                    # RFC 4291 link local unicast
  fec0::/10+,                    # RFC 3879 old site local unicast
  ff00::/8+                      # RFC 4291 multicast
];

function reject_bogon_prefixes() {
  if (net ~ BOGON_PREFIXES) then {
    print "Reject: Bogon prefix: ", net, " ", bgp_path;
    reject;
  }
}
