define IX_NETS = [
  2a0e:8f01:1000:24::/64,	# bgpexchange_fra
  2a0e:8f01:1000:11::/64,	# bgpexchange_ams
  2a0e:8f01:1000:33::/64,	# bgpexchange_yyz
  2401:2060:b109:156::/64,	# bgpexchange_nyc
  2a0e:8f01:1000:83::/64,	# bgpexchange_dfw
  2a0e:8f01:1000:40::/64,	# bgpexchange_mia
  2a0e:8f01:1000:22::/64,	# bgpexchange_sjc
  2401:2060:b109:90::/64,	# bgpexchange_atl
  2a0e:8f01:1000:32::/64,	# bgpexchange_mkc
  2a0e:8f01:1000:3::/64		# bgpexchange_lax
];

function reject_ix_nets() {
  if net ~ IX_NETS then {
    print "Reject: IX Net: ", net, " ", bgp_path.last;
    reject;
  }
}
