function reject_self_net() {
  if net ~ SUNFLOWER_NETSETv6 then {
    print "Reject: self net: ", net, " ", bgp_path.last;
    reject;
  }
}

filter reject_self_net_filter {
  if net ~ SUNFLOWER_NETSETv6 then {
    print "Reject: self net: ", net, " ", bgp_path.last;
    reject;
  }
  accept;
}

function only_self_net() {
  if net !~ SUNFLOWER_NETSETv6 then {
    print "Reject: not self net: ", net, " ", bgp_path.last;
    reject;
  }
}

filter only_self_net_filter {
  if net !~ SUNFLOWER_NETSETv6 then {
    print "Reject: not self net: ", net, " ", bgp_path.last;
    reject;
  }
  accept;
}
