function strip_too_many_communities() {
  if ( ( bgp_community.len + bgp_ext_community.len + bgp_large_community.len ) >= 100 ) then {
    bgp_community.empty;
    bgp_ext_community.empty;
    bgp_large_community.empty;
  }
}
