filter common_external_import {
  reject_self_net();
  reject_invalid_rpki();
  reject_bogon_asns();
  reject_bogon_prefixes();
  reject_small_prefixes();
  reject_ix_nets();
  reject_long_aspaths();
  reject_transit_paths();

  honor_graceful_shutdown();
  strip_too_many_communities();

  accept;
}
