apiVersion: v1
kind: Service
metadata:
  name: znc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: znc
  ports:
    - protocol: TCP
      port: 4921
      targetPort: 4921
      name: https
    - protocol: TCP
      port: 4922
      targetPort: 4922
      name: http
