apiVersion: v1
kind: Service
metadata:
  name: znc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: znc
  ports:
    - protocol: TCP
      port: 4921
      targetPort: https
      name: https
    - protocol: TCP
      port: 4922
      targetPort: http
      name: http
