apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: znc
  labels:
    app.kubernetes.io/name: znc
spec:
  replicas: 1
  serviceName: "znc"
  selector:
    matchLabels:
      app.kubernetes.io/name: znc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: znc
    spec:
      volumes:
        - name: znc-config
          persistentVolumeClaim:
            claimName: znc-pvc
      containers:
        - name: znc
          image: znc:1.10.1
          imagePullPolicy: Always
          ports:
            - containerPort: 4921
              name: https
            - containerPort: 4922
              name: http
          volumeMounts:
            - name: znc-config
              mountPath: "/znc-data"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
