---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: seaweedfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64M
  storageClassName: seaweedfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-tigris-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50G
  storageClassName: tigris